
		ORG $8000

		BANK_START $02

		SECTION_START	02

		FAR_PTR	_room86
		.BYTE	$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$01,$02,$14,$B0,$0E,$04,$01,$02,$03,$01,$0E,$04,$14,$B0,$03,$01
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01
		.BYTE	$01,$0E,$04,$01,$02,$03,$01,$14,$B0,$01,$02,$03,$01,$0E,$04,$01
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01
		.BYTE	$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01
		.BYTE	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
		.BYTE	$D0,$D4,$D5,$D1,$D0,$D4,$D5,$D1,$D0,$D4,$D5,$D1,$D0,$D4,$D5,$D1
		.BYTE	$D3,$E3,$0F,$D2,$D3,$DB,$0F,$D2,$D3,$E3,$6F,$D2,$D3,$E3,$DA,$D2
		FAR_PTR	_room87
		.BYTE	$DA,$DA,$E3,$DD,$DE,$E3,$DB,$E3,$DB,$DC,$DB,$DC,$E4,$E4,$E3,$DC
		.BYTE	$DF,$DF,$E3,$E5,$DF,$E3,$E5,$E3,$E5,$DC,$E5,$DC,$D0,$D1,$E5,$DC
		.BYTE	$DA,$DA,$E3,$DA,$DA,$E3,$DB,$E4,$DD,$DE,$DB,$DC,$D2,$D3,$DA,$DC
		.BYTE	$D6,$D5,$D4,$D5,$D4,$E3,$DB,$D0,$D4,$D6,$D4,$D6,$D6,$D6,$D5,$D4
		.BYTE	$29,$00,$00,$29,$D8,$E3,$DB,$D9,$00,$29,$00,$00,$29,$00,$00,$29
		.BYTE	$01,$07,$08,$01,$D2,$D5,$D4,$D3,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$01,$02,$03,$01,$00,$00,$29,$00,$03,$01,$0E,$04,$01,$02,$03,$01
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01
		.BYTE	$01,$2E,$2E,$01,$2E,$2E,$01,$2E,$D0,$D4,$D5,$D1,$01,$2E,$2E,$01
		.BYTE	$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$D9,$DA,$DA,$D9,$01,$2D,$2D,$01
		.BYTE	$D4,$D5,$D4,$D6,$D6,$D6,$D5,$D4,$D3,$DB,$DB,$D2,$D6,$D6,$D5,$D4
		.BYTE	$DB,$DD,$DE,$DB,$DD,$DE,$DB,$DB,$E3,$DC,$DD,$DE,$E0,$E1,$E2,$DB
		.BYTE	$E5,$DF,$DF,$DF,$DF,$DF,$DF,$DF,$E3,$DC,$E5,$DF,$E8,$E9,$EA,$DC
		.BYTE	$E0,$E1,$E3,$DB,$DD,$DE,$E0,$E1,$E3,$DC,$D0,$D1,$DD,$DE,$DA,$DC
		.BYTE	$E8,$E9,$E4,$DC,$E5,$DF,$E8,$E9,$E3,$DC,$D2,$D3,$E0,$E1,$E2,$DC
		FAR_PTR	_room88
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$C5,$C6,$C7,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$C8,$C9,$CA,$CB,$CC,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$CD,$F0,$F1,$F2,$F3,$CE,$CF,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$18,$1A,$F8,$FA,$FB,$FC,$FD,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$C1,$C1,$C1,$C1,$C1,$C1,$C1,$C1,$C1,$00
		.BYTE	$BE,$00,$00,$00,$00,$00,$00,$C2,$C2,$C2,$C2,$C2,$C2,$C2,$00,$00
		.BYTE	$BE,$BE,$BE,$00,$00,$00,$00,$C0,$C0,$C0,$C0,$C0,$C0,$C0,$00,$BE
		.BYTE	$BE,$BE,$BE,$BE,$BE,$BE,$00,$C0,$C0,$C0,$C0,$C0,$C0,$C0,$BE,$BE
		.BYTE	$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF
		.BYTE	$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69
		FAR_PTR	_room89
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$00,$00,$00,$00,$00,$00,$C1,$C1,$C1,$C1,$C1,$C1,$C1,$C1,$C1,$00
		.BYTE	$BE,$00,$00,$00,$00,$00,$00,$C2,$C2,$C2,$C2,$C2,$C2,$C2,$00,$00
		.BYTE	$BE,$BE,$BE,$00,$00,$00,$00,$C0,$C0,$C0,$C0,$C0,$C0,$C0,$00,$BE
		.BYTE	$BE,$BE,$BE,$BE,$BE,$BE,$00,$C0,$C0,$C0,$C0,$C0,$C0,$C0,$BE,$BE
		.BYTE	$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF,$BF
		.BYTE	$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69,$69
		FAR_PTR	_room8A
		.BYTE	$01,$0E,$04,$01,$02,$09,$20,$0E,$04,$01,$02,$09,$01,$00,$00,$00
		.BYTE	$01,$07,$08,$01,$05,$09,$20,$07,$08,$0F,$05,$09,$01,$00,$00,$00
		.BYTE	$01,$02,$03,$01,$0E,$09,$20,$02,$03,$01,$0E,$09,$01,$00,$00,$00
		.BYTE	$01,$05,$06,$01,$07,$09,$20,$05,$06,$01,$07,$09,$01,$00,$00,$00
		.BYTE	$01,$2E,$2C,$01,$2E,$09,$20,$2E,$2C,$01,$2E,$09,$01,$00,$00,$00
		.BYTE	$01,$2D,$2D,$01,$2D,$09,$20,$2D,$2D,$01,$2D,$09,$01,$00,$00,$00
		.BYTE	$01,$03,$03,$01,$A2,$A1,$A0,$A0,$B1,$A0,$A0,$A1,$A2,$00,$00,$00
		.BYTE	$01,$05,$06,$01,$00,$00,$21,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$01,$0E,$04,$01,$00,$22,$1E,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$01,$07,$08,$01,$00,$A9,$AA,$AB,$00,$00,$00,$00,$A9,$AA,$AB,$1F
		.BYTE	$01,$2C,$2C,$01,$00,$18,$19,$1A,$00,$00,$00,$00,$18,$19,$1A,$00
		.BYTE	$01,$2D,$2D,$01,$00,$1B,$1C,$1D,$00,$00,$00,$00,$1B,$1C,$1D,$00
		.BYTE	$D4,$D5,$D4,$D6,$D5,$D4,$D6,$D5,$D4,$D5,$D4,$D5,$D4,$D6,$D5,$D1
		.BYTE	$E0,$E1,$E2,$DB,$DD,$DE,$E0,$E1,$E2,$DA,$DC,$E5,$E0,$E1,$E2,$D7
		.BYTE	$E8,$E9,$EA,$DC,$E5,$DF,$E8,$E9,$EA,$E5,$DC,$E5,$E8,$E9,$EA,$D8
		FAR_PTR	_room8B
		.BYTE	$20,$00,$01,$0E,$D7,$E4,$E4,$E3,$DC,$DD,$DE,$E3,$DD,$DE,$E3,$D7
		.BYTE	$20,$00,$01,$07,$D8,$D0,$D1,$E5,$DC,$E5,$DF,$E3,$E5,$DF,$E3,$D8
		.BYTE	$20,$00,$01,$02,$D7,$D2,$D3,$DA,$DC,$DD,$DE,$E3,$DB,$DB,$E3,$D7
		.BYTE	$20,$00,$01,$05,$D8,$E5,$DF,$DF,$DB,$E5,$DF,$E4,$E5,$DF,$E3,$D8
		.BYTE	$20,$00,$01,$0E,$D7,$DA,$DA,$DB,$DC,$DC,$DA,$DA,$DB,$DA,$E4,$D7
		.BYTE	$20,$00,$01,$07,$D8,$E0,$E1,$E2,$DC,$E0,$E1,$E1,$E1,$E2,$DD,$D8
		.BYTE	$20,$00,$01,$02,$D9,$E8,$E9,$EA,$DC,$E8,$E9,$E9,$E9,$EA,$DB,$D8
		.BYTE	$20,$00,$01,$05,$D2,$D5,$D4,$D6,$D6,$D6,$D5,$D4,$D5,$D4,$D6,$D3
		.BYTE	$21,$00,$01,$0E,$00,$E7,$00,$00,$29,$E7,$00,$29,$00,$E7,$29,$00
		.BYTE	$23,$00,$01,$07,$08,$29,$05,$06,$01,$07,$08,$01,$05,$06,$01,$1F
		.BYTE	$00,$00,$01,$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$00
		.BYTE	$00,$00,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$00
		.BYTE	$D0,$D4,$D5,$D1,$EB,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$ED
		.BYTE	$D7,$E3,$E4,$D7,$10,$11,$0A,$0B,$11,$11,$0A,$0B,$11,$11,$11,$12
		.BYTE	$D8,$E3,$0F,$D8,$00,$00,$0C,$0D,$29,$00,$0C,$0D,$00,$00,$29,$00
		FAR_PTR	_room8C
		.BYTE	$D7,$E3,$E4,$E4,$D7,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$D8,$E3,$DA,$DA,$D8,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$D7,$E4,$DD,$DE,$D9,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$D8,$E0,$E2,$D0,$D3,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$D9,$E8,$EA,$D9,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$D2,$D4,$D6,$D3,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$20,$00,$29,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$20,$08,$01,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$21,$03,$01,$00,$00,$29,$00,$00,$29,$00,$00,$29,$00,$00,$29,$00
		.BYTE	$23,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$1F
		.BYTE	$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$D0,$D4,$D6,$D6,$D6,$D6,$D5,$D1
		.BYTE	$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$D9,$DA,$DD,$DE,$DD,$DE,$DB,$D9
		.BYTE	$D0,$D4,$D6,$D6,$D6,$D6,$D6,$D6,$D3,$E0,$E1,$E2,$E0,$E2,$DC,$D8
		.BYTE	$D9,$DA,$DA,$DA,$DD,$DE,$DF,$DF,$DF,$E8,$E9,$EA,$E8,$EA,$DC,$D7
		.BYTE	$00,$00,$29,$00,$00,$29,$00,$00,$29,$00,$00,$29,$00,$00,$DC,$D8
		FAR_PTR	_room8D
		.BYTE	$20,$09,$09,$09,$09,$01,$02,$03,$01,$09,$04,$09,$02,$03,$09,$03
		.BYTE	$20,$09,$09,$09,$09,$01,$05,$06,$01,$09,$08,$09,$05,$06,$09,$07
		.BYTE	$20,$09,$09,$09,$09,$01,$0E,$04,$01,$09,$03,$09,$0E,$04,$09,$02
		.BYTE	$20,$09,$09,$09,$09,$01,$07,$08,$01,$09,$06,$09,$07,$08,$09,$05
		.BYTE	$20,$09,$09,$09,$09,$01,$02,$03,$01,$09,$2C,$09,$2C,$2C,$09,$03
		.BYTE	$20,$09,$09,$09,$09,$01,$05,$06,$01,$09,$2D,$09,$2D,$2D,$09,$07
		.BYTE	$A2,$A1,$A1,$A2,$09,$01,$2E,$2E,$01,$09,$A2,$A1,$A0,$A0,$A1,$A2
		.BYTE	$20,$09,$09,$09,$09,$01,$2D,$2D,$01,$09,$00,$29,$00,$00,$29,$05
		.BYTE	$21,$09,$A2,$A1,$A1,$A0,$B1,$A0,$A0,$A1,$A0,$A0,$A0,$A2,$01,$2C
		.BYTE	$23,$09,$29,$00,$00,$29,$00,$00,$29,$00,$00,$29,$00,$00,$01,$2D
		.BYTE	$00,$09,$01,$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$2E,$2E,$01,$2C
		.BYTE	$00,$09,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D
		.BYTE	$D0,$D6,$D6,$D5,$D4,$D5,$D4,$D6,$D5,$D4,$D6,$D5,$D4,$D6,$D5,$D1
		.BYTE	$D9,$DF,$E0,$E1,$E1,$E1,$E1,$E1,$E1,$E2,$DB,$DD,$DE,$E5,$DF,$D7
		.BYTE	$D8,$E3,$E8,$E9,$E9,$E9,$E9,$E9,$E9,$EA,$DC,$DA,$DA,$E3,$E3,$D8
		FAR_PTR	_room8E
		.BYTE	$04,$01,$01,$0E,$09,$01,$02,$03,$01,$09,$04,$09,$02,$03,$01,$03
		.BYTE	$08,$01,$01,$07,$09,$01,$05,$06,$01,$09,$08,$09,$05,$06,$01,$07
		.BYTE	$03,$01,$01,$02,$09,$01,$0E,$04,$01,$09,$03,$09,$0E,$04,$01,$02
		.BYTE	$06,$01,$01,$05,$09,$01,$07,$08,$01,$09,$06,$09,$07,$08,$01,$05
		.BYTE	$04,$01,$01,$2C,$09,$01,$2E,$2E,$01,$09,$2C,$09,$2C,$2C,$01,$03
		.BYTE	$08,$01,$01,$2D,$09,$01,$2D,$2D,$01,$09,$2D,$09,$2D,$2D,$01,$07
		.BYTE	$03,$01,$01,$2D,$09,$01,$A2,$B1,$A0,$A1,$A0,$A1,$A0,$A2,$01,$02
		.BYTE	$06,$01,$01,$2D,$09,$01,$2D,$2D,$29,$09,$2D,$29,$2D,$2D,$01,$05
		.BYTE	$2C,$01,$A2,$A0,$A1,$A0,$B1,$A0,$A0,$A1,$2D,$01,$2D,$2D,$01,$03
		.BYTE	$2D,$01,$29,$00,$00,$29,$00,$00,$29,$00,$2D,$01,$A9,$AA,$AB,$07
		.BYTE	$2C,$01,$01,$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$18,$19,$1A,$2C
		.BYTE	$2D,$01,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$1B,$1C,$1D,$2D
		.BYTE	$D6,$D6,$D6,$D5,$D4,$D5,$D4,$D6,$D5,$D4,$D6,$D5,$D4,$D6,$D5,$D4
		.BYTE	$E3,$DF,$E0,$E1,$E1,$E1,$E1,$E1,$E1,$E2,$DB,$DD,$DE,$E5,$DF,$DD
		.BYTE	$E3,$E3,$E8,$E9,$E9,$E9,$E9,$E9,$E9,$EA,$DC,$DA,$DA,$E3,$E3,$DB
		FAR_PTR	_room8F
		.BYTE	$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$09,$01,$00,$09,$00
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$09,$01,$00,$09,$00
		.BYTE	$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$A2,$A1,$A0,$A0,$A1,$A2
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$00,$09,$00
		.BYTE	$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$A2,$B1,$A1,$A2
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$00,$00,$00
		.BYTE	$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$0F,$00,$00
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$00,$00,$00
		.BYTE	$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$D0,$D4,$D6,$D6
		.BYTE	$01,$07,$A9,$AA,$AB,$06,$01,$07,$08,$01,$05,$06,$D9,$DA,$DA,$DA
		.BYTE	$01,$2C,$18,$19,$1A,$2C,$01,$2C,$2C,$01,$2C,$2C,$D7,$DD,$DE,$DB
		.BYTE	$01,$2D,$1B,$1C,$1D,$2D,$01,$2D,$2D,$01,$2D,$2D,$D8,$E3,$E3,$DC
		.BYTE	$D6,$D6,$D6,$D5,$D4,$D5,$D4,$D6,$D6,$D5,$D4,$D5,$D3,$D6,$D6,$D5
		.BYTE	$E0,$E1,$E2,$DB,$DD,$DE,$E0,$E1,$E2,$DB,$DD,$DE,$E0,$E1,$E2,$DB
		.BYTE	$E8,$E9,$EA,$DC,$E5,$DF,$E8,$E9,$EA,$DC,$E5,$DF,$E8,$E9,$EA,$DC
		FAR_PTR	_room90
		.BYTE	$01,$03,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01
		.BYTE	$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01
		.BYTE	$01,$02,$03,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01
		.BYTE	$01,$05,$06,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$D4,$D5,$D4,$D6,$D6,$D6,$D5,$D1,$03,$01,$0E,$04,$A3,$A4,$A4,$A5
		.BYTE	$E0,$E1,$E2,$E3,$E0,$E1,$E2,$D9,$06,$01,$07,$08,$10,$11,$11,$12
		.BYTE	$E8,$E9,$EA,$E3,$E8,$E9,$EA,$D7,$2C,$01,$2E,$2C,$01,$2E,$2E,$01
		.BYTE	$DA,$DD,$DE,$E3,$DD,$DE,$DA,$D8,$2D,$01,$2D,$2D,$01,$2D,$2D,$01
		.BYTE	$DF,$DF,$DF,$E3,$E5,$DF,$DF,$D9,$03,$01,$03,$03,$01,$03,$03,$01
		.BYTE	$E0,$E2,$DB,$E3,$E2,$E3,$D0,$D3,$00,$2B,$00,$00,$2B,$00,$00,$2B
		.BYTE	$E8,$EA,$DC,$E4,$EA,$E3,$D9,$84,$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF
		.BYTE	$DF,$DF,$DF,$DF,$DF,$E3,$D2,$D4,$D6,$D6,$D6,$D6,$D5,$D4,$D6,$D6
		.BYTE	$DD,$DE,$DF,$E3,$DD,$DE,$DC,$DD,$DE,$E3,$DC,$DD,$DE,$E3,$DC,$DD
		FAR_PTR	_room91
		.BYTE	$02,$03,$01,$0E,$04,$09,$09,$03,$04,$01,$02,$03,$01,$0E,$04,$01
		.BYTE	$05,$06,$01,$07,$08,$09,$09,$07,$08,$01,$05,$06,$01,$07,$08,$01
		.BYTE	$0E,$04,$01,$02,$03,$09,$09,$02,$03,$01,$0E,$04,$01,$02,$03,$01
		.BYTE	$07,$08,$01,$05,$06,$09,$09,$05,$06,$01,$07,$08,$01,$05,$06,$01
		.BYTE	$02,$03,$01,$0E,$A2,$A1,$A1,$A2,$04,$01,$02,$03,$01,$2C,$2C,$01
		.BYTE	$05,$06,$01,$07,$00,$29,$29,$07,$08,$01,$05,$06,$01,$2D,$2D,$01
		.BYTE	$0E,$04,$01,$02,$03,$01,$01,$02,$03,$01,$2E,$2E,$01,$2C,$D0,$D1
		.BYTE	$07,$08,$01,$05,$06,$01,$01,$05,$06,$01,$2D,$2D,$01,$2D,$D9,$D7
		.BYTE	$02,$03,$01,$0E,$04,$01,$01,$2C,$2E,$01,$2E,$2E,$D0,$D6,$D3,$D8
		.BYTE	$05,$06,$01,$07,$08,$01,$01,$2D,$2D,$01,$2D,$2D,$D9,$E1,$E2,$D9
		.BYTE	$03,$03,$01,$03,$D0,$D5,$D4,$D5,$D4,$D6,$D6,$D6,$D3,$E9,$EA,$D7
		.BYTE	$00,$00,$2B,$00,$D2,$D6,$D1,$DF,$DB,$DB,$DA,$E3,$DB,$DA,$E3,$D8
		.BYTE	$FF,$FF,$FF,$FF,$FF,$BD,$D9,$DA,$DC,$DD,$DE,$E3,$DD,$DE,$D0,$D3
		.BYTE	$D6,$D6,$D6,$D6,$D6,$D5,$D3,$E2,$DC,$DA,$DA,$E4,$DA,$DA,$D9,$84
		.BYTE	$DE,$E3,$DC,$DD,$DE,$E3,$E8,$EA,$DC,$DD,$DE,$DB,$DD,$DE,$D2,$D4
		FAR_PTR	_room92
		.BYTE	$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E
		.BYTE	$05,$06,$0F,$07,$08,$01,$05,$06,$01,$07,$08,$0F,$05,$06,$01,$07
		.BYTE	$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02
		.BYTE	$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05
		.BYTE	$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E
		.BYTE	$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07
		.BYTE	$0E,$04,$A3,$A4,$A4,$A5,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02
		.BYTE	$07,$08,$10,$11,$11,$12,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05
		.BYTE	$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$A6,$A7,$A7,$A8,$01,$0E
		.BYTE	$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$13,$28,$28,$15,$01,$07
		.BYTE	$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02
		.BYTE	$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05
		.BYTE	$0E,$03,$2B,$0E,$03,$2B,$0E,$03,$2B,$0E,$03,$2B,$0E,$03,$2B,$0E
		.BYTE	$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF
		.BYTE	$D6,$D5,$D4,$D5,$D4,$D6,$D5,$D4,$D6,$D5,$D4,$D5,$D4,$D6,$D5,$D4
		FAR_PTR	_room93
		.BYTE	$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03
		.BYTE	$08,$01,$05,$06,$0F,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06
		.BYTE	$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04
		.BYTE	$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08
		.BYTE	$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03
		.BYTE	$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06
		.BYTE	$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$0F,$0E,$04
		.BYTE	$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08
		.BYTE	$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03
		.BYTE	$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06
		.BYTE	$03,$01,$A3,$A4,$A4,$A5,$03,$01,$2C,$2C,$01,$2C,$D0,$D4,$D5,$D1
		.BYTE	$06,$01,$10,$11,$11,$12,$06,$01,$2D,$2D,$01,$2D,$D9,$E0,$E2,$D9
		.BYTE	$03,$2B,$0E,$03,$2B,$0E,$03,$2B,$D0,$D4,$D6,$D6,$D3,$E8,$EA,$D2
		.BYTE	$FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF,$BD,$DA,$DA,$DB,$DD,$DE,$DA,$DA
		.BYTE	$D6,$D5,$D4,$D5,$D4,$D6,$D5,$D4,$D3,$E0,$E2,$DC,$E0,$E1,$E2,$DB
		FAR_PTR	_room94
		.BYTE	$20,$01,$02,$09,$01,$0E,$04,$01,$02,$09,$01,$0E,$04,$01,$02,$09
		.BYTE	$20,$01,$05,$09,$0F,$07,$08,$01,$05,$09,$01,$07,$08,$01,$05,$09
		.BYTE	$20,$01,$0E,$09,$01,$02,$03,$01,$0E,$09,$01,$02,$03,$01,$0E,$09
		.BYTE	$20,$01,$07,$09,$01,$05,$06,$01,$07,$09,$01,$05,$06,$01,$07,$09
		.BYTE	$20,$01,$02,$09,$0F,$0E,$04,$01,$A2,$A1,$B1,$A2,$04,$01,$02,$09
		.BYTE	$20,$01,$05,$09,$01,$07,$08,$01,$00,$00,$29,$07,$08,$01,$05,$26
		.BYTE	$20,$01,$A2,$A1,$B1,$A2,$03,$01,$0E,$04,$01,$02,$03,$01,$A9,$AA
		.BYTE	$20,$01,$00,$00,$29,$05,$06,$01,$07,$08,$01,$05,$06,$01,$18,$19
		.BYTE	$21,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$00,$00
		.BYTE	$23,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06
		.BYTE	$D0,$D6,$D1,$03,$0F,$02,$03,$01,$0E,$D0,$D5,$D1,$2C,$01,$2C,$2C
		.BYTE	$D9,$DF,$D2,$D1,$01,$05,$06,$01,$D0,$D3,$DF,$D9,$2D,$01,$2D,$2D
		.BYTE	$D8,$E3,$D0,$D3,$2B,$0E,$03,$2B,$D2,$D1,$DF,$D2,$D6,$D6,$D6,$D6
		.BYTE	$D7,$E4,$D9,$84,$FE,$FF,$FE,$FF,$BD,$D7,$DA,$DB,$DD,$DE,$DA,$DA
		.BYTE	$D8,$E1,$D2,$D5,$D4,$D6,$D5,$D4,$D5,$D3,$E2,$DC,$E0,$E1,$E2,$E0
		FAR_PTR	_room95
		.BYTE	$01,$09,$04,$01,$02,$09,$01,$0E,$04,$01,$09,$09,$01,$0E,$04,$01
		.BYTE	$01,$09,$08,$01,$05,$09,$01,$07,$08,$01,$09,$09,$01,$07,$08,$01
		.BYTE	$01,$09,$03,$01,$0E,$09,$01,$02,$03,$01,$09,$09,$01,$02,$03,$01
		.BYTE	$01,$09,$06,$01,$07,$09,$01,$05,$06,$01,$09,$09,$01,$05,$06,$01
		.BYTE	$01,$09,$04,$01,$02,$09,$01,$0E,$04,$01,$09,$09,$01,$0E,$04,$01
		.BYTE	$01,$09,$08,$01,$05,$26,$01,$07,$08,$01,$09,$26,$01,$07,$08,$01
		.BYTE	$AB,$09,$03,$01,$A9,$AA,$AB,$02,$03,$01,$A9,$AA,$AB,$02,$03,$01
		.BYTE	$1A,$09,$06,$01,$18,$19,$1A,$05,$06,$01,$18,$19,$1A,$05,$06,$01
		.BYTE	$29,$09,$04,$01,$00,$00,$29,$0E,$04,$01,$09,$00,$29,$0E,$04,$01
		.BYTE	$01,$09,$08,$01,$05,$06,$01,$07,$08,$01,$09,$06,$01,$07,$08,$01
		.BYTE	$A2,$A1,$A0,$B1,$A0,$A0,$A0,$A0,$B1,$A0,$A1,$A2,$01,$2C,$2C,$01
		.BYTE	$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01
		.BYTE	$D5,$D4,$D5,$D4,$D6,$D6,$D5,$D4,$D5,$D4,$D6,$D6,$D5,$D4,$D5,$D4
		.BYTE	$E3,$DA,$DA,$DA,$DA,$DA,$E3,$DA,$DA,$DA,$DA,$DA,$E3,$DA,$DA,$DA
		.BYTE	$E1,$E2,$E0,$E1,$E2,$E0,$E1,$E2,$E0,$E1,$E2,$E0,$E1,$E2,$E0,$E1
		FAR_PTR	_room96
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$90,$91,$49,$49
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$90,$91,$49,$49,$8F,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$90
		.BYTE	$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$8F,$49,$49,$49,$49
		.BYTE	$49,$49,$49,$90,$91,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$49,$49,$49,$49,$49,$8F,$49,$85,$49,$49,$49,$49,$49,$49,$49,$49
		.BYTE	$F4,$BC,$F4,$49,$49,$49,$86,$87,$49,$49,$49,$90,$91,$49,$49,$8F
		.BYTE	$F4,$BC,$F4,$16,$16,$16,$00,$00,$86,$27,$16,$16,$16,$16,$16,$16
		.BYTE	$F4,$BC,$F4,$BC,$F4,$82,$82,$82,$82,$82,$82,$82,$82,$82,$82,$82
		.BYTE	$BC,$F4,$BC,$F4,$17,$17,$17,$17,$17,$17,$17,$17,$17,$17,$17,$17
		.BYTE	$F4,$BC,$F4,$BC,$F4,$BC,$F4,$BC,$F4,$BC,$F4,$BC,$F4,$BC,$F4,$BC
		FAR_PTR	_room97
		.BYTE	$01,$09,$01,$09,$06,$01,$09,$06,$01,$09,$08,$01,$05,$09,$01,$00
		.BYTE	$01,$09,$01,$09,$04,$01,$09,$04,$01,$09,$03,$01,$03,$09,$01,$00
		.BYTE	$01,$09,$01,$09,$08,$01,$09,$08,$01,$09,$06,$01,$07,$09,$01,$00
		.BYTE	$01,$09,$01,$09,$03,$01,$09,$03,$01,$09,$04,$01,$02,$09,$01,$00
		.BYTE	$01,$09,$01,$09,$06,$01,$09,$0F,$01,$09,$08,$01,$0F,$09,$01,$00
		.BYTE	$01,$09,$01,$09,$04,$01,$09,$04,$01,$09,$03,$01,$03,$09,$01,$00
		.BYTE	$01,$09,$01,$09,$08,$01,$09,$08,$A2,$A1,$A0,$B1,$A0,$A1,$A2,$00
		.BYTE	$01,$09,$01,$09,$03,$01,$09,$03,$29,$2A,$00,$29,$00,$2A,$01,$00
		.BYTE	$A2,$A1,$A0,$A1,$A0,$A2,$09,$05,$01,$09,$08,$01,$05,$2A,$01,$00
		.BYTE	$29,$09,$29,$09,$00,$29,$09,$03,$01,$09,$03,$01,$03,$2A,$01,$1F
		.BYTE	$01,$09,$01,$09,$04,$01,$09,$04,$01,$09,$03,$01,$03,$09,$01,$24
		.BYTE	$01,$09,$01,$09,$08,$01,$09,$08,$01,$09,$06,$01,$05,$09,$01,$00
		.BYTE	$A2,$A1,$B1,$A1,$A0,$A2,$09,$03,$01,$09,$03,$01,$0E,$09,$01,$00
		.BYTE	$01,$06,$01,$07,$08,$01,$09,$06,$01,$09,$06,$01,$07,$09,$01,$00
		.BYTE	$01,$0E,$01,$02,$03,$01,$09,$04,$01,$09,$03,$01,$03,$09,$03,$03
		FAR_PTR	_room98
		.BYTE	$01,$07,$08,$01,$09,$06,$01,$00,$20,$09,$00,$01,$07,$01,$0F,$00
		.BYTE	$01,$02,$03,$01,$09,$04,$01,$00,$20,$09,$00,$01,$02,$01,$00,$00
		.BYTE	$01,$05,$06,$01,$09,$08,$01,$00,$20,$09,$00,$01,$05,$01,$0F,$00
		.BYTE	$01,$03,$04,$01,$09,$03,$01,$00,$20,$26,$00,$01,$03,$01,$00,$00
		.BYTE	$01,$07,$08,$01,$09,$0F,$01,$00,$A9,$AA,$AB,$01,$07,$01,$0F,$00
		.BYTE	$01,$02,$03,$01,$09,$04,$01,$00,$18,$19,$1A,$01,$02,$01,$00,$00
		.BYTE	$01,$05,$A2,$A0,$A1,$A2,$01,$00,$20,$00,$00,$01,$D0,$D4,$D5,$D4
		.BYTE	$01,$03,$00,$29,$00,$00,$01,$00,$20,$00,$00,$01,$D9,$E0,$E1,$E2
		.BYTE	$01,$07,$08,$01,$05,$06,$01,$00,$21,$00,$00,$01,$D7,$E8,$E9,$EA
		.BYTE	$01,$02,$A9,$AA,$AB,$04,$01,$22,$1E,$25,$00,$01,$D8,$E0,$E1,$E2
		.BYTE	$01,$2C,$18,$19,$1A,$2C,$01,$00,$AC,$AD,$AE,$01,$D7,$E8,$E9,$EA
		.BYTE	$01,$2D,$1B,$1C,$1D,$2D,$01,$00,$1B,$1C,$1D,$01,$D8,$E0,$E1,$E2
		.BYTE	$D0,$D6,$D5,$D4,$D5,$D4,$D6,$D5,$D4,$D5,$D4,$D5,$D3,$E8,$E9,$EA
		.BYTE	$D9,$DB,$DA,$DA,$E3,$E3,$DB,$E3,$DC,$E3,$DB,$DB,$E3,$E0,$E1,$E2
		.BYTE	$D8,$E5,$DF,$E8,$E9,$EA,$E3,$E3,$DC,$E5,$DF,$DB,$E3,$E8,$E9,$EA
		FAR_PTR	_room99
		.BYTE	$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03
		.BYTE	$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06
		.BYTE	$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04
		.BYTE	$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08
		.BYTE	$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03
		.BYTE	$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06
		.BYTE	$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$0E,$04
		.BYTE	$06,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$07,$08
		.BYTE	$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$2C,$2C,$01,$2E,$2E
		.BYTE	$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D
		.BYTE	$D0,$D4,$D5,$D1,$EB,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC,$ED
		.BYTE	$D9,$DA,$DB,$D7,$10,$11,$0A,$0B,$11,$11,$0A,$0B,$11,$11,$11,$12
		.BYTE	$D8,$DD,$DE,$D8,$00,$00,$0C,$0D,$00,$29,$0C,$0D,$00,$00,$29,$00
		.BYTE	$D7,$DA,$DA,$D7,$07,$08,$29,$05,$06,$01,$08,$29,$05,$06,$01,$07
		.BYTE	$D8,$E0,$E2,$D8,$02,$03,$01,$0E,$04,$01,$03,$01,$0E,$04,$01,$02
		FAR_PTR	_room9A
		.BYTE	$01,$02,$01,$0E,$04,$A2,$A1,$A0,$A0,$A1,$A2,$01,$00,$09,$01,$00
		.BYTE	$01,$05,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$0E,$09,$01,$02
		.BYTE	$01,$0E,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$A2,$A1,$A0,$A0
		.BYTE	$01,$07,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$00,$09,$29,$00
		.BYTE	$01,$02,$01,$0E,$04,$01,$02,$03,$01,$0E,$04,$01,$A2,$A1,$A0,$A0
		.BYTE	$01,$05,$01,$07,$08,$01,$05,$06,$01,$07,$08,$01,$00,$00,$29,$00
		.BYTE	$01,$0E,$01,$02,$03,$01,$0E,$04,$01,$02,$03,$01,$2E,$2C,$2C,$2E
		.BYTE	$01,$07,$01,$05,$06,$01,$07,$08,$01,$05,$06,$01,$2D,$2D,$2D,$2D
		.BYTE	$01,$2E,$01,$2E,$2E,$01,$2E,$2E,$01,$2C,$2C,$01,$D0,$D4,$D5,$D4
		.BYTE	$01,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$2D,$2D,$01,$D7,$E0,$E1,$E1
		.BYTE	$D0,$D4,$D5,$D4,$D5,$D4,$D5,$D4,$D5,$D4,$D5,$D1,$D8,$E8,$E9,$E9
		.BYTE	$D7,$E0,$E1,$E2,$DD,$DE,$E0,$E1,$E1,$E2,$DB,$D7,$D7,$E3,$DA,$DC
		.BYTE	$D8,$E8,$E9,$EA,$E5,$DF,$E8,$E9,$E9,$EA,$DB,$D8,$D8,$E3,$DF,$DC
		.BYTE	$D7,$E3,$DA,$DC,$DA,$DC,$DA,$DC,$DA,$DC,$DB,$D7,$D7,$E3,$DA,$DC
		.BYTE	$D8,$E3,$DF,$DC,$DF,$DC,$DF,$DC,$DF,$DC,$DB,$D8,$D8,$E3,$DF,$DC
		FAR_PTR	_room9B
		.BYTE	$34,$34,$34,$34,$34,$34,$45,$34,$34,$34,$34,$34,$34,$34,$34,$34
		.BYTE	$34,$44,$34,$34,$34,$34,$34,$34,$34,$45,$34,$34,$34,$34,$34,$44
		.BYTE	$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34
		.BYTE	$34,$34,$34,$34,$34,$34,$34,$44,$34,$34,$45,$34,$34,$45,$34,$34
		.BYTE	$34,$45,$34,$34,$45,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34
		.BYTE	$45,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34,$34
		.BYTE	$34,$34,$34,$34,$34,$34,$45,$34,$34,$34,$44,$34,$34,$34,$34,$45
		.BYTE	$34,$44,$34,$34,$34,$34,$34,$45,$34,$34,$34,$34,$45,$34,$34,$34
		.BYTE	$34,$34,$34,$34,$34,$34,$45,$34,$34,$34,$34,$34,$34,$34,$34,$34
		.BYTE	$35,$36,$35,$36,$35,$36,$35,$36,$35,$36,$35,$36,$35,$36,$35,$36
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
		.BYTE	$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A
		.BYTE	$38,$39,$39,$37,$38,$39,$39,$38,$39,$37,$39,$38,$39,$39,$38,$37
		.BYTE	$39,$39,$38,$37,$39,$38,$39,$39,$38,$37,$39,$39,$39,$38,$39,$37
		.BYTE	$38,$39,$39,$37,$38,$39,$39,$38,$39,$37,$39,$38,$39,$39,$38,$37
		FAR_PTR	_room9C
		.BYTE	$49,$49,$49,$49,$4B,$4A,$34,$4A,$47,$44,$34,$49,$4C,$4A,$4A,$4A
		.BYTE	$49,$49,$49,$49,$49,$4B,$34,$47,$44,$34,$34,$4C,$4A,$4A,$4A,$4A
		.BYTE	$49,$49,$46,$34,$45,$34,$2F,$34,$45,$34,$2F,$34,$34,$4A,$47,$34
		.BYTE	$49,$49,$49,$46,$34,$34,$30,$33,$33,$33,$30,$34,$34,$47,$44,$45
		.BYTE	$4A,$4A,$4A,$47,$2F,$31,$30,$3D,$3D,$3D,$30,$32,$2F,$48,$49,$49
		.BYTE	$4A,$4A,$47,$34,$30,$3B,$30,$3D,$3D,$3D,$30,$3C,$30,$44,$48,$49
		.BYTE	$4A,$47,$2F,$31,$30,$3B,$30,$3D,$3D,$3D,$30,$3C,$30,$32,$2F,$48
		.BYTE	$47,$34,$30,$3B,$30,$3B,$30,$3D,$3D,$3D,$30,$3C,$30,$3C,$30,$34
		.BYTE	$34,$34,$30,$3B,$30,$3B,$30,$3D,$3D,$3D,$30,$3C,$30,$3C,$30,$44
		.BYTE	$35,$36,$30,$3B,$30,$3B,$30,$3D,$3D,$3D,$30,$3C,$30,$3C,$30,$36
		.BYTE	$00,$00,$41,$42,$41,$42,$41,$40,$40,$40,$41,$43,$41,$43,$41,$00
		.BYTE	$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A,$3A
		.BYTE	$38,$39,$39,$37,$38,$39,$39,$38,$39,$37,$39,$38,$39,$39,$38,$37
		.BYTE	$39,$39,$38,$37,$39,$38,$39,$39,$38,$37,$39,$39,$39,$38,$39,$37
		.BYTE	$38,$39,$39,$37,$38,$39,$39,$38,$39,$37,$39,$38,$39,$39,$38,$37

		SECTION_END		02, "ROOM DATA C"

		SECTION_START	02A

_msg_frame_tiles_list:
		.BYTE	$A2,$A5,$A3,$A4,$40,$A4,$A0,$A5,$A1

		SECTION_END		02A, "PRG7 MSG FRAME TILES"

		SECTION_START	03

#if LANGUAGE = LANG_EN

_dictionary:
		DICT_REC	_dict80
		DICT_REC	_dict81
		DICT_REC	_Clock_Tower
		DICT_REC	_Western__World
		DICT_REC	_Future_World
		DICT_REC	_There_s_no_Time
		DICT_REC	_Water_Rabbit_ddt
		DICT_REC	_Newscaster_ddt
		DICT_REC	_restaurant
		DICT_REC	_e_amusement
		DICT_REC	__everyone
		DICT_REC	_warehouse
		DICT_REC	__downtown
		DICT_REC	__give_you
		DICT_REC	I_think_I
		DICT_REC	_Welcome
		DICT_REC	_Are_you_
		DICT_REC	_There_s_
		DICT_REC	_through_
		DICT_REC	_Monterey
		DICT_REC	_Rescue_
		DICT_REC	_Rangers
		DICT_REC	__coming
		DICT_REC	__prison
		DICT_REC	_should_
		DICT_REC	_ghosts
		DICT_REC	_Let_s_
		DICT_REC	_o_find
		DICT_REC	_escape
		DICT_REC	_Fatcat
		DICT_REC	_Gadget
		DICT_REC	_Zipper
		DICT_REC	__stop_
		DICT_REC	__time_
		DICT_REC	__found
		DICT_REC	_could_
		DICT_REC	_help_dot
		DICT_REC	_about_
		DICT_REC	__first
		DICT_REC	__park_exc
		DICT_REC	__will_
		DICT_REC	_must_
		DICT_REC	__bomb
		DICT_REC	_from_
		DICT_REC	_Let_s
		DICT_REC	__trap
		DICT_REC	_Woah_exc
		DICT_REC	_This_
		DICT_REC	__got_
		DICT_REC	__some
		DICT_REC	__made
		DICT_REC	_come_
		DICT_REC	_dictB4
		DICT_REC	_that_
		DICT_REC	__your
		DICT_REC	__has
		DICT_REC	_less
		DICT_REC	_apo_ll_
		DICT_REC	_the_
		DICT_REC	_Chip
		DICT_REC	_Dale
		DICT_REC	_have
		DICT_REC	_here
		DICT_REC	_Look
		DICT_REC	_open
		DICT_REC	_self
		DICT_REC	_sure
		DICT_REC	_this
		DICT_REC	_What
		DICT_REC	_with
		DICT_REC	__can
		DICT_REC	__say
		DICT_REC	_apo_ve_
		DICT_REC	__for
		DICT_REC	_and_
		DICT_REC	_any_
		DICT_REC	_ever
		DICT_REC	_ight
		DICT_REC	__you
		DICT_REC	_are_
		DICT_REC	_dictD0
		DICT_REC	__cut
		DICT_REC	_exc__
		DICT_REC	_is_
		DICT_REC	_ast
		DICT_REC	_ing
		DICT_REC	_lue
		DICT_REC	_not
		DICT_REC	_now
		DICT_REC	_n_apo_t
		DICT_REC	_one
		DICT_REC	_out
		DICT_REC	_We_
		DICT_REC	_was
		DICT_REC	_You
		DICT_REC	_be_
		DICT_REC	__to
		DICT_REC	__go
		DICT_REC	_dot_dot_dot
		DICT_REC	_my_
		DICT_REC	_of_
		DICT_REC	_a_
		DICT_REC	_col_
		DICT_REC	_ed
		DICT_REC	_do
		DICT_REC	_he
		DICT_REC	_if
		DICT_REC	_in
		DICT_REC	_is
		DICT_REC	_it
		DICT_REC	_me
		DICT_REC	_No
		DICT_REC	_no
		DICT_REC	_on
		DICT_REC	_or
		DICT_REC	_ut
		DICT_REC	_we
		DICT_REC	_dot_dot

; 2 RAM buffer slots
; 9 free slots
; 119 used slots
; 128 total slots

		DICT_DATA	_Clock_Tower
		.BYTE	_C,_l,_o,_c,_k,__,_T,_o,_w,_e,_r,_EOL
		DICT_DATA	_Western__World
		.BYTE	_W,_e,_s,_t,_e,_r,_n,__,_W,_o,_r,_l,_d,_EOL
		DICT_DATA	_Future_World
		.BYTE	_F,_u,_t,_u,_r,_e,__,_W,_o,_r,_l,_d,_EOL
		DICT_DATA	_There_s_no_Time
		.BYTE	_T,_h,_e,_r,_e,_apo,_s,__,_n,_o,__,_t,_i,_m,_e,__,_EOL
		DICT_DATA	_Water_Rabbit_ddt
		.BYTE	_W,_a,_t,_e,_r,__,_R,_a,_b,_b,_i,_t,_ddt,_EOL
		DICT_DATA	_Newscaster_ddt
		.BYTE	_N,_e,_w,_s,_c,_a,_s,_t,_e,_r,_ddt,_EOL
		DICT_DATA	_restaurant
		.BYTE	__,_r,_e,_s,_t,_a,_u,_r,_a,_n,_t,_EOL
		DICT_DATA	_e_amusement
		.BYTE	_e,__,_a,_m,_u,_s,_e,_m,_e,_n,_t,_EOL
		DICT_DATA	__everyone
		.BYTE	__,_e,_v,_e,_r,_y,_o,_n,_e,_exc,_EOL
		DICT_DATA	_warehouse
		.BYTE	_w,_a,_r,_e,_h,_o,_u,_s,_e,_EOL
		DICT_DATA	__downtown
		.BYTE	__,_d,_o,_w,_n,_t,_o,_w,_n,_EOL
		DICT_DATA	__give_you
		.BYTE	__,_g,_i,_v,_e,__,_y,_o,_u,_EOL
		DICT_DATA	I_think_I
		.BYTE	_I,__,_t,_h,_i,_n,_k,__,_I,_EOL
		DICT_DATA	_Welcome
		.BYTE	_W,_e,_l,_c,_o,_m,_e,_col,_EOL
		DICT_DATA	_Are_you_
		.BYTE	_A,_r,_e,__,_y,_o,_u,__,_EOL
		DICT_DATA	_There_s_
		.BYTE	_T,_h,_e,_r,_e,_apo,_s,__,_EOL
		DICT_DATA	_through_
		.BYTE	_t,_h,_r,_o,_u,_g,_h,__,_EOL
		DICT_DATA	_Monterey
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_EOL
		DICT_DATA	_Rescue_
		.BYTE	_R,_e,_s,_c,_u,_e,__,_EOL
		DICT_DATA	_Rangers
		.BYTE	_R,_a,_n,_g,_e,_r,_s,_EOL
		DICT_DATA	__coming
		.BYTE	__,_c,_o,_m,_i,_n,_g,_EOL
		DICT_DATA	__prison
		.BYTE	__,_p,_r,_i,_s,_o,_n,_EOL
		DICT_DATA	_should_
		.BYTE	_s,_h,_o,_u,_l,_d,__,_EOL
		DICT_DATA	_ghosts
		.BYTE	_g,_h,_o,_s,_t,_s,_EOL
		DICT_DATA	_Let_s_
		.BYTE	_L,_e,_t,_apo,_s,__,_EOL
		DICT_DATA	_o_find
		.BYTE	_o,__,_f,_i,_n,_d,_EOL
		DICT_DATA	_escape
		.BYTE	_e,_s,_c,_a,_p,_e,_EOL
		DICT_DATA	_Fatcat
		.BYTE	_F,_a,_t,_c,_a,_t,_EOL
		DICT_DATA	_Gadget
		.BYTE	_G,_a,_d,_g,_e,_t,_EOL
		DICT_DATA	_Zipper
		.BYTE	_Z,_i,_p,_p,_e,_r,_EOL
		DICT_DATA	__stop_
		.BYTE	__,_s,_t,_o,_p,__,_EOL
		DICT_DATA	__time_
		.BYTE	__,_t,_i,_m,_e,__,_EOL
		DICT_DATA	__found
		.BYTE	__,_f,_o,_u,_n,_d,_EOL
		DICT_DATA	_could_
		.BYTE	_c,_o,_u,_l,_d,__,_EOL
		DICT_DATA	_help_dot
		.BYTE	__,_h,_e,_l,_p,_dot,_EOL
		DICT_DATA	_about_
		.BYTE	_a,_b,_o,_u,_t,__,_EOL
		DICT_DATA	__first
		.BYTE	__,_f,_i,_r,_s,_t,_EOL
		DICT_DATA	__park_exc
		.BYTE	__,_p,_a,_r,_k,_exc,_EOL
		DICT_DATA	__will_
		.BYTE	__,_w,_i,_l,_l,__,_EOL
		DICT_DATA	_must_
		.BYTE	_m,_u,_s,_t,__,_EOL
		DICT_DATA	__bomb
		.BYTE	__,_b,_o,_m,_b,_EOL
		DICT_DATA	_from_
		.BYTE	_f,_r,_o,_m,__,_EOL
		DICT_DATA	_Let_s
		.BYTE	_L,_e,_t,_apo,_s,_EOL
		DICT_DATA	__trap
		.BYTE	__,_t,_r,_a,_p,_EOL
		DICT_DATA	_Woah_exc
		.BYTE	_W,_o,_a,_h,_exc,_EOL
		DICT_DATA	_This_
		.BYTE	_T,_h,_i,_s,__,_EOL
		DICT_DATA	__got_
		.BYTE	__,_g,_o,_t,__,_EOL
		DICT_DATA	__some
		.BYTE	__,_s,_o,_m,_e,_EOL
		DICT_DATA	__made
		.BYTE	__,_m,_a,_d,_e,_EOL
		DICT_DATA	_come_
		.BYTE	_c,_o,_m,_e,__,_EOL
; unused entry, same as __some!
		DICT_DATA	_dictB4
		.BYTE	__,_s,_o,_m,_e,_EOL
;
		DICT_DATA	_that_
		.BYTE	_t,_h,_a,_t,__,_EOL
		DICT_DATA	__your
		.BYTE	__,_y,_o,_u,_r,_EOL
		DICT_DATA	__has
		.BYTE	__,_h,_a,_s,_EOL
		DICT_DATA	_less
		.BYTE	_l,_e,_s,_s,_EOL
		DICT_DATA	_apo_ll_
		.BYTE	_apo,_l,_l,__,_EOL
		DICT_DATA	_the_
		.BYTE	_t,_h,_e,__,_EOL
		DICT_DATA	_Chip
		.BYTE	_C,_h,_i,_p,_EOL
		DICT_DATA	_Dale
		.BYTE	_D,_a,_l,_e,_EOL
		DICT_DATA	_have
		.BYTE	_h,_a,_v,_e,_EOL
		DICT_DATA	_here
		.BYTE	_h,_e,_r,_e,_EOL
		DICT_DATA	_Look
		.BYTE	_L,_o,_o,_k,_EOL
		DICT_DATA	_open
		.BYTE	_o,_p,_e,_n,_EOL
		DICT_DATA	_self
		.BYTE	_s,_e,_l,_f,_EOL
		DICT_DATA	_sure
		.BYTE	_s,_u,_r,_e,_EOL
		DICT_DATA	_this
		.BYTE	_t,_h,_i,_s,_EOL
		DICT_DATA	_What
		.BYTE	_W,_h,_a,_t,_EOL
		DICT_DATA	_with
		.BYTE	_w,_i,_t,_h,_EOL
		DICT_DATA	__can
		.BYTE	__,_c,_a,_n,_EOL
		DICT_DATA	__say
		.BYTE	__,_s,_a,_y,_EOL
		DICT_DATA	_apo_ve_
		.BYTE	_apo,_v,_e,__,_EOL
		DICT_DATA	__for
		.BYTE	__,_f,_o,_r,_EOL
		DICT_DATA	_and_
		.BYTE	_a,_n,_d,__,_EOL
		DICT_DATA	_any_
		.BYTE	_a,_n,_y,__,_EOL
		DICT_DATA	_ever
		.BYTE	_e,_v,_e,_r,_EOL
		DICT_DATA	_ight
		.BYTE	_i,_g,_h,_t,_EOL
		DICT_DATA	__you
		.BYTE	__,_y,_o,_u,_EOL
		DICT_DATA	_are_
		.BYTE	_a,_r,_e,__,_EOL
; copy of _can entry, unused
		DICT_DATA	_dictD0
		.BYTE	__,_c,_a,_n,_EOL
;
		DICT_DATA	__cut
		.BYTE	__,_c,_u,_t,_EOL
		DICT_DATA	_exc__
		.BYTE	_exc,__,__,_EOL
		DICT_DATA	_is_
		.BYTE	_i,_s,__,_EOL
		DICT_DATA	_ast
		.BYTE	_a,_s,_t,_EOL
		DICT_DATA	_ing
		.BYTE	_i,_n,_g,_EOL
		DICT_DATA	_lue
		.BYTE	_l,_u,_e,_EOL
		DICT_DATA	_not
		.BYTE	_n,_o,_t,_EOL
		DICT_DATA	_now
		.BYTE	_n,_o,_w,_EOL
		DICT_DATA	_n_apo_t
		.BYTE	_n,_apo,_t,_EOL
		DICT_DATA	_one
		.BYTE	_o,_n,_e,_EOL
		DICT_DATA	_out
		.BYTE	_o,_u,_t,_EOL
		DICT_DATA	_We_
		.BYTE	_W,_e,__,_EOL
		DICT_DATA	_was
		.BYTE	_w,_a,_s,_EOL
		DICT_DATA	_You
		.BYTE	_Y,_o,_u,_EOL
		DICT_DATA	_be_
		.BYTE	_b,_e,__,_EOL
		DICT_DATA	__to
		.BYTE	__,_t,_o,_EOL
		DICT_DATA	__go
		.BYTE	__,_g,_o,_EOL
		DICT_DATA	_dot_dot_dot
		.BYTE	_dot,_dot,_dot,_EOL
		DICT_DATA	_my_
		.BYTE	_m,_y,__,_EOL
		DICT_DATA	_of_
		.BYTE	_o,_f,__,_EOL
		DICT_DATA	_a_
		.BYTE	_a,__,_EOL
		DICT_DATA	_col_
		.BYTE	_col,__,_EOL
		DICT_DATA	_ed
		.BYTE	_e,_d,_EOL
		DICT_DATA	_do
		.BYTE	_d,_o,_EOL
		DICT_DATA	_he
		.BYTE	_h,_e,_EOL
		DICT_DATA	_if
		.BYTE	_i,_f,_EOL
		DICT_DATA	_in
		.BYTE	_i,_n,_EOL
		DICT_DATA	_is
		.BYTE	_i,_s,_EOL
		DICT_DATA	_it
		.BYTE	_i,_t,_EOL
		DICT_DATA	_me
		.BYTE	_m,_e,_EOL
		DICT_DATA	_No
		.BYTE	_N,_o,_EOL
		DICT_DATA	_no
		.BYTE	_n,_o,_EOL
		DICT_DATA	_on
		.BYTE	_o,_n,_EOL
		DICT_DATA	_or
		.BYTE	_o,_r,_EOL
		DICT_DATA	_ut
		.BYTE	_u,_t,_EOL
		DICT_DATA	_we
		.BYTE	_w,_e,_EOL
		DICT_DATA	_dot_dot
		.BYTE	_dot,_dot,_EOL
; empty available entries
;		DICT_DATA	_dictF6
;		DICT_DATA	_dictF7
;		DICT_DATA	_dictF8
;		DICT_DATA	_dictF9
;		DICT_DATA	_dictFA
;		DICT_DATA	_dictFB
;		DICT_DATA	_dictFC

_msg00:
		.BYTE	_Newscaster_ddt,_RET
		.BYTE	_S,_p,_e,_c,_i,_a,_l,__,_B,_u,_l,_l,_e,_t,_in,_ddt,_WAIT
		.BYTE	_P,_o,_l,_i,_c,_e,__say,_RET
		.BYTE	_a_,_do,_w,_n,_t,_o,_w,_n,_restaurant,__has,_RET
		.BYTE	_r,_e,_c,_e,_i,_v,_ed,__,_a_,_b,_o,_m,_b,__,_t,_h,_r,_e,_a,_t,_dot,_WAIT
		.BYTE	_U,_n,_less,__,_the_,_t,_i,_me,__bomb,__can,_RET
		.BYTE	_be_,_f,_o,_u,_n,_d,_col_,_the_,_r,_e,_s,_t,_a,_u,_r,_a,_n,_t,_RET
		.BYTE	_could_,_be_,_d,_e,_s,_t,_r,_o,_y,_ed,_dot,_WAIT
		.BYTE	_STOP
_msg01:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Woah_exc,__,__,_A,__time_,_b,_o,_m,_b,_exc,_WAIT
		.BYTE	_STOP
_msg02:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_Chip,_exc__,_What,__,_is_,_it,_que,_WAIT
		.BYTE	_STOP
_msg03:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_There_s_,_a_,_t,_i,_me,__bomb,_RET
		.BYTE	_in,__,_a_,_r,_e,_s,_t,_a,_u,_r,_a,_n,_t,__downtown,_exc,_WAIT
		.BYTE	_W,_e,_apo_ve_,_g,_o,_t,__to,__,_f,_in,_d,__,_it,_exc,_WAIT
		.BYTE	_STOP
_msg04:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_This_,_is_,_a,_n,__,_e,_me,_r,_g,_e,_n,_c,_y,_exc,_WAIT
		.BYTE	_There_s_no_Time,_t,_o,__,_was,_t,_e,_exc,_RET
		.BYTE	_Let_s_,_g,_o,_col_,_M,_a,_t,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg05:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_W,_e,_apo_ve_,_g,_o,_t,__,_a_,_b,_o,_m,_b,__to,__,_f,_in,_d,_exc,_WAIT
		.BYTE	_STOP
_msg06:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_W,_e,_apo_ll_,_g,_o,__,_a,_he,_a,_d,_RET
		.BYTE	_t,_o,__,_in,_v,_e,_s,_t,_i,_g,_a,_t,_e,_exc,_WAIT
		.BYTE	_Look,__for,__,_u,_s,_RET
		.BYTE	_and_,_we,_apo_ll_,_g,_i,_v,_e,__you,_RET
		.BYTE	_any_,_c,_lue,_s,__,_we,_apo_ve_,_f,_o,_u,_n,_d,_dot,_WAIT
		.BYTE	_STOP
_msg07:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_O,_r,__give_you,__some,_help_dot,_dot_dot,_WAIT
		.BYTE	_N,_ever,__,_w,_o,_u,_l,_d,__,_o,_apo,__made,__,_it,_RET
		.BYTE	_through_,_the_,_b,_a,_t,_t,_l,_e,__,_of_,_t,_he,_RET
		.BYTE	_b,_r,_i,_e,__,_with,_out,__,_a_,_b,_it,__,_o,_apo,_help_dot,_WAIT
		.BYTE	_A,_h,_h,_col_,_t,_h,_o,_s,_e,__,_we,_r,_e,__,_the_,_d,_a,_y,_s,_dsh,_dsh,_WAIT
		.BYTE	_STOP
_msg08:
		.BYTE	_Zipper,_ddt,_RET
		.BYTE	_dot_dot_dot,__,_dot_dot,__,_dot_dot_dot,_dot_dot,__,_dot_dot,_WAIT
		.BYTE	_STOP
_msg09:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_R,_ight,_col_,_Zipper,_exc,_RET
		.BYTE	_There_s_no_Time,_t,_o,__,_l,_o,_s,_e,_exc,_WAIT
		.BYTE	_Dale,_col_,_y,_o,_u,__,_come_,_with,__,_me,_exc,_WAIT
		.BYTE	_STOP
_msg0A:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_No,_w,_exc,_que,__,__,_B,_ut,__,_I,__,_was,__,_about_,_RET
		.BYTE	_t,_o,__,_s,_t,_a,_r,_t,__,_my_,_a,_f,_t,_e,_r,_no,_on,__,_n,_a,_p,_exc,_WAIT
		.BYTE	_STOP
_msg0B:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_No,__can,__,_do,_col_,_Dale,_exc,_WAIT
		.BYTE	_STOP
_msg0C:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_O,_K,_col_,_P,_a,_r,_t,_n,_e,_r,_exc__,_Let_s_,_g,_o,_exc,_WAIT
		.BYTE	_STOP
_msg0D:
		.BYTE	_RET
		.BYTE	_Rescue_,_Rangers,__,_a,_w,_a,_y,_exc,_WAIT
		.BYTE	_STOP
_msg0E:
		.BYTE	_Newscaster_ddt,_RET
		.BYTE	_A,_l,_s,_o,__,_in,__,_the_,_n,_e,_w,_s,_dot_dot_dot,_WAIT
		.BYTE	_Fatcat,_col,_RET
		.BYTE	_the_,_not,_or,_i,_o,_u,_s,__,_f,_e,_l,_in,_e,__,_f,_e,_l,_on,_col,_WAIT
		.BYTE	_escape,_d,__,_from_,_p,_r,_is,_on,_RET
		.BYTE	_l,_ast,__,_n,_ight,_dot_dot_dot,_WAIT
		.BYTE	_STOP
_msg0F:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_A,_l,_l,__,_r,_ight,_col_,_s,_p,_i,_l,_l,__,_it,_exc,_RET
		.BYTE	_W,_h,_o,__,_s,_e,_t,__,_the_,_t,_i,_me,__bomb,_que,_WAIT
		.BYTE	_STOP
_msg10:
		.BYTE	_Water_Rabbit_ddt,_RET
		.BYTE	_I,__,_d,_i,_d,_exc,_WAIT
		.BYTE	_Fatcat,__,_a,_s,_k,_ed,__,_me,_RET
		.BYTE	_t,_o,__,_c,_r,_e,_a,_t,_e,__,_a_,_d,_i,_v,_e,_r,_s,_i,_on,_col,_RET
		.BYTE	_and_,_it,__,_w,_or,_k,_ed,_exc,_WAIT
		.BYTE	_STOP
_msg11:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_No,__,_w,_a,_y,_exc,_RET
		.BYTE	_Fatcat,_apo,_s,__,_in,__prison,_exc,_WAIT
		.BYTE	_STOP
_msg12:
		.BYTE	_Water_Rabbit_ddt,_RET
		.BYTE	_No,_t,__,_any_,_m,_or,_e,_exc,_RET
		.BYTE	_H,_e,__,_b,_r,_o,_k,_e,__,_out,__,_l,_ast,__,_n,_ight,_exc,_WAIT
		.BYTE	_H,_e,_apo,_s,__,_p,_l,_a,_n,_n,_ing,__to,__,_s,_t,_e,_a,_l,_RET
		.BYTE	_the_,_U,_r,_n,__,_of_,_the_,_P,_h,_a,_r,_a,_o,_h,_exc,_RET
		.BYTE	_H,_e,__,_p,_r,_o,_b,_a,_b,_l,_y,__has,__,_it,__,_a,_l,_r,_e,_a,_d,_y,_exc,_WAIT
		.BYTE	_You,_apo,_r,_e,__to,_o,__,_l,_a,_t,_e,_exc,_WAIT
		.BYTE	_STOP
_msg13:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_S,_o,__,_w,_here,_apo,_s,__,_the_,_b,_o,_m,_b,_exc,_que,_WAIT
		.BYTE	_STOP
_msg14:
		.BYTE	_Water_Rabbit_ddt,_RET
		.BYTE	_F,_in,_d,__,_it,__your,_self,_exc,_RET
		.BYTE	_H,_a_,_h,_a_,_h,_a,_exc,_WAIT
		.BYTE	_STOP
_msg15:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Gadget,_col,_RET
		.BYTE	_have,__you,__found,__,_the_,_b,_o,_m,_b,_que,_WAIT
		.BYTE	_STOP
_msg16:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_H,_e,_r,_e,_apo,_s,__,_the_,_b,_o,_m,_b,_exc,_WAIT
		.BYTE	_Look,_col_,_it,__has,_RET
		.BYTE	_b,_lue,__,_and_,_r,_ed,__,_w,_i,_r,_e,_s,__coming,_RET
		.BYTE	_out,__,_of_,_it,_exc,_WAIT
		.BYTE	_We_,_have,__to,__cut,_RET
		.BYTE	_one,__,_of_,_the_,_w,_i,_r,_e,_s,_RET
		.BYTE	_t,_o,__,_d,_e,_f,_u,_s,_e,__,_it,_exc,_WAIT
		.BYTE	_STOP
_msg17:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_B,_ut,_col_,_u,_h,_col_,_w,_h,_a,_t,__,_h,_a,_p,_p,_e,_n,_s,_RET
		.BYTE	_if,__,_we,__cut,__,_the_,_w,_r,_on,_g,__,_one,_que,_WAIT
		.BYTE	_STOP
_msg18:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_W,_e,_apo,_r,_e,__,_do,_o,_me,_d,_exc,_WAIT
		.BYTE	_STOP
_msg19:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_U,_h,__,_o,_h,_dot,_WAIT
		.BYTE	_STOP
_msg1A:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_W,_h,_i,_c,_h,__,_one,__,_should_,_I,__cut,_que,_WAIT
		.BYTE	_R,_ed,__,_or,__,_b,_lue,_que,__,__,_H,_u,_r,_r,_y,_exc,_RET
		.BYTE	_RET
		.BYTE	__,_rar,_R,_ed,__,__,_B,_lue,_RET
		.BYTE	_STOP
_msg1B:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_Are_you_,_sure,_que,_RET
		.BYTE	__,_rar,_Y,_e,_s,__,__,_No,_RET
		.BYTE	_STOP
_msg1C:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_O,_K,_col_,_here,__go,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg1D:
		.BYTE	_RET
		.BYTE	_B,_O,_O,_O,_O,_M,_exc,_exc,_exc,_WAIT
		.BYTE	_STOP
_msg1E:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_J,_u,_s,_t,__,_k,_i,_d,_d,_ing,_dot,_RET
		.BYTE	_We_,_c,_ut,__,_the_,_r,_ight,__,_one,_exc,_WAIT
		.BYTE	_STOP
_msg1F:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	I_think_I,_apo,_m,__go,_n,_n,_a_,_f,_a,_in,_t,_exc,_WAIT
		.BYTE	_STOP
_msg20:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_H,_e,_y,_exc__,_W,_here,_apo,_s,__,_Dale,_que,_WAIT
		.BYTE	_STOP
_msg21:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_O,_h,_col_,_he,__,_p,_a,_s,_s,_ed,__,_out,_dot,_WAIT
		.BYTE	_STOP
_msg22:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_W,_he,_w,_exc__,_I,__,_g,_u,_e,_s,_s,_RET
		.BYTE	_that_,_was,__,_the_,_r,_ight,__,_one,_dot,_WAIT
		.BYTE	_STOP
_msg23:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_I,_t,__,_must_,_have,__,_b,_e,_e,_n,_RET
		.BYTE	_a_,_f,_a,_k,_e,__bomb,_dot,_WAIT
		.BYTE	_STOP
_msg24:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_H,_u,_r,_r,_y,_exc__,_Fatcat,_apo,_s,__,_do,_n,_e,__,_s,_t,_o,_l,_e,_n,_RET
		.BYTE	_the_,_U,_r,_n,__,_of_,_the_,_P,_h,_a,_r,_a,_o,_h,_exc,_WAIT
		.BYTE	_I,_t,_apo,_s,__,_on,__,_a_,_s,_h,_i,_p,_RET
		.BYTE	_about_,_t,_o,__,_l,_e,_a,_v,_e,__,_p,_or,_t,_exc,_WAIT
		.BYTE	_STOP
_msg25:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_No,_w,__,_w,_h,_a,_t,__,_do,_e,_s,__,_Fatcat,__,_w,_a,_n,_t,_RET
		.BYTE	_with,__,_the_,_U,_r,_n,__,_of_,_the_,_P,_h,_a,_r,_a,_o,_h,_que,_WAIT
		.BYTE	_STOP
_msg26:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_W,_h,_o,__,_k,_now,_s,_que,_WAIT
		.BYTE	_W,_e,_apo_ve_,_j,_u,_s,_t,__got_,_RET
		.BYTE	_t,_o,__,_g,_e,_t,__,_it,__,_b,_a,_c,_k,_exc,_WAIT
		.BYTE	_STOP
_msg27:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_T,_he,__,_U,_r,_n,__,_of_,_the_,_P,_h,_a,_r,_a,_o,_h,_RET
		.BYTE	_is_,_m,_is,_s,_ing,_WAIT
		.BYTE	_and_,_we,__,_do,_n_apo_t,__,_have,__,_any_,_l,_e,_a,_d,_s,_exc,_WAIT
		.BYTE	_STOP
_msg28:
		.BYTE	_Zipper,_ddt,_RET
		.BYTE	_dot_dot_dot,_dot_dot,__,_dot_dot_dot,__,_dot_dot_dot,_dot_dot,__,_dot_dot,_WAIT
		.BYTE	_STOP
_msg29:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_M,_on,_t,_e,_y,_exc,_RET
		.BYTE	_What,_apo,_s,__,_Zipper,__say,_ing,_exc,_que,_WAIT
		.BYTE	_STOP
_msg2A:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_W,_e,_l,_l,_col_,_l,_u,_v,_col_,_he,__say,_s,_WAIT
		.BYTE	_that_,_Fatcat,__,_and_,_h,_is_,_he,_n,_c,_h,_me,_n,_RET
		.BYTE	_he,_a,_d,_ed,__,_in,_t,_o,__,_a_,_warehouse,_RET
		.BYTE	_b,_y,__,_the_,_do,_c,_k,_s,_exc,_WAIT
		.BYTE	_STOP
_msg2B:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_R,_e,_a,_l,_l,_y,_que,_RET
		.BYTE	_Are_you_,_sure,_col_,_Zipper,_que,_WAIT
		.BYTE	_STOP
_msg2C:
		.BYTE	_Zipper,_ddt,_RET
		.BYTE	_dot_dot_dot,_WAIT
		.BYTE	_STOP
_msg2D:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_A,_l,_l,__,_r,_ight,_exc,_RET
		.BYTE	_C,_apo,_m,_on,_exc__,_Let_s_,_g,_o,_exc,_WAIT
		.BYTE	_Fatcat,__,_b,_e,_t,_t,_e,_r,__,_w,_a,_t,_c,_h,__,_out,_exc,_WAIT
		.BYTE	_STOP
_msg2E:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Woah_exc,_RET
		.BYTE	_I,_t,_apo,_s,__,_p,_it,_c,_h,__,_d,_a,_r,_k,__,_in,__,_here,_exc,_WAIT
		.BYTE	_I,__can,_apo,_t,__,_s,_e,_e,_RET
		.BYTE	_a_,_b,_l,_o,_o,_m,_in,_apo,__,_t,_h,_ing,_exc,_WAIT
		.BYTE	_STOP
_msg2F:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_H,_e,_y,_exc__,_T,_he,__,_do,_or,__,_s,_h,_ut,__,_it,_self,_exc,_WAIT
		.BYTE	_STOP
_msg30:
		.BYTE	_A,_h,_h,_h,__,_h,_a_,_h,_a_,_h,_a,_dot,_RET
		.BYTE	_Welcome,_RET
		.BYTE	_my_,_l,_it,_t,_l,_e,__,_Rescue_,_Rangers,_exc,_WAIT
		.BYTE	_I,_apo_ve_,_w,_a,_it,_ed,_RET
		.BYTE	_a_,_l,_on,_g,__time_,_f,_or,__,_this,_exc,_WAIT
		.BYTE	_STOP
_msg31:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_Fatcat,_que,_que,_WAIT
		.BYTE	_STOP
_msg32:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_T,_he,__,_one,__,_and_,_on,_l,_y,_exc,_WAIT
		.BYTE	_STOP
_msg33:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Fatcat,_exc__,_You,__,_s,_t,_o,_l,_e,_RET
		.BYTE	_the_,_U,_r,_n,__,_of_,_the_,_P,_h,_a,_r,_a,_o,_h,_exc,_WAIT
		.BYTE	_RET
		.BYTE	_STOP
_msg34:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_T,_h,_a,_t,_apo,_s,__,_r,_ight,_exc,_WAIT
		.BYTE	_A,_n,_d,__,_it,_apo,_s,__,_f,_u,_l,_l,__,_of_,_RET
		.BYTE	_a,_n,_c,_i,_e,_n,_t,__,_e,_v,_i,_l,__,_s,_p,_i,_r,_it,_s,_exc,_WAIT
		.BYTE	_W,_he,_n,__,_I,__,_r,_e,_l,_e,_a,_s,_e,__,_t,_he,_m,_col,_RET
		.BYTE	_I,_apo_ll_,_r,_u,_l,_e,__,_the_,_w,_or,_l,_d,_exc,_WAIT
		.BYTE	_STOP
_msg35:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_You,_apo_ll_,_n,_ever,__,_g,_e,_t,__,_a,_w,_a,_y,_RET
		.BYTE	_with,__,_this,_col_,_Fatcat,_exc,_WAIT
		.BYTE	_STOP
_msg36:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_A,_n,_d,__,_w,_h,_a,_t,__will_,_y,_o,_u,__,_do,_RET
		.BYTE	_t,_o,__stop_,_me,_exc,_que,_WAIT
		.BYTE	_You,_apo,_r,_e,__,_in,__,_a,_RET
		.BYTE	_g,_i,_a,_n,_t,__,_r,_e,_f,_r,_i,_g,_e,_r,_a,_t,_or,_exc,_WAIT
		.BYTE	_You,_apo_ll_,_be_,_f,_r,_o,_z,_e,_n,__,_s,_o,_l,_i,_d,_RET
		.BYTE	_in,__,_t,_h,_r,_e,_e,__,_m,_in,_ut,_e,_s,_exc,_RET
		.BYTE	_H,_a_,_h,_a_,_h,_a,_exc,_WAIT
		.BYTE	_STOP
_msg37:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_A,_w,_col_,_n,_ut,_s,_exc,_RET
		.BYTE	_What,__,_are_,_we,__go,_n,_n,_a_,_do,__,_now,_que,_WAIT
		.BYTE	_STOP
_msg38:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	I_think_I,__,_s,_e,_e,__,_a,_n,__,_open,_ing,_exc,_RET
		.BYTE	_O,_v,_e,_r,__,_t,_here,_exc,_WAIT
		.BYTE	_M,_a,_y,_be_,_RET
		.BYTE	_we,__can,__,_escape,__,_through_,_it,_exc,_RET
		.BYTE	_H,_u,_r,_r,_y,_exc,_WAIT
		.BYTE	_STOP
_msg39:
		.BYTE	_You,_apo_ll_,_be_,_f,_r,_o,_z,_e,_n,__,_s,_o,_l,_i,_d,_RET
		.BYTE	_in,__,_t,_h,_r,_e,_e,__,_m,_in,_ut,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg3A:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_C,_r,_i,_k,_e,_y,_exc,_RET
		.BYTE	_There_s_,_ghosts,__,_ever,_y,_w,_here,_exc,_WAIT
		.BYTE	_Fatcat,__,_m,_u,_s,_t,_apo,_v,_e,_RET
		.BYTE	_open,_ed,__,_the_,_u,_r,_n,_exc,_WAIT
		.BYTE	_STOP
_msg3B:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Look,_exc__,_T,_he,_y,_apo,_r,_e,__coming,_RET
		.BYTE	_from_,_the_,_warehouse,_exc,_WAIT
		.BYTE	_STOP
_msg3C:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_You,__,_m,_dsh,_m,_dsh,_me,_a,_n,__,_the_,_w,_dsh,_warehouse,_RET
		.BYTE	_is_,_h,_dsh,_h,_a,_u,_n,_t,_ed,_dot_dot_dot,_que,_WAIT
		.BYTE	_STOP
_msg3D:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_P,_u,_l,_l,__your,_self,__to,_g,_e,_t,_he,_r,_col,_RET
		.BYTE	_Dale,_exc__,_You,_apo,_r,_e,__,_a_,_R,_a,_n,_g,_e,_r,_exc,_RET
		.BYTE	_RET
		.BYTE	_STOP
_msg3E:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_Y,_e,_a,_h,_col_,_and_,_t,_h,_dsh,_t,_h,_dsh,_t,_h,_o,_s,_e,_RET
		.BYTE	_are_,_g,_h,_dsh,_g,_h,_dsh,_ghosts,_exc,_WAIT
		.BYTE	_STOP
_msg3F:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_We_,_d,_i,_d,__,_it,_exc__,_A,_l,_l,__,_the_,_ghosts,_RET
		.BYTE	_should_,_d,_is,_a,_p,_p,_e,_a,_r,__,_s,_o,_on,_exc,_WAIT
		.BYTE	_STOP
_msg40:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_D,_on,_apo,_t,__you,__,_Rescue_,_R,_o,_d,_e,_n,_t,_s,_RET
		.BYTE	_ever,__,_l,_e,_a,_r,_n,_que,_WAIT
		.BYTE	_STOP
_msg41:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_U,_h,__,_o,_h,_dot,__,__,_I,_t,_apo,_s,__,_Fatcat,_exc,_WAIT
		.BYTE	_STOP
_msg42:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_C,_o,_me,__,_out,__,_here,__,_and_,_f,_a,_c,_e,__,_u,_s,_exc,_RET
		.BYTE	_Are_you_,_a_,_c,_a,_t,__,_or,__,_a_,_m,_o,_u,_s,_e,_exc,_que,_WAIT
		.BYTE	_STOP
_msg43:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_No,_t,__,_s,_o,__,_f,_ast,_col_,_Rangers,_exc,_WAIT
		.BYTE	_I,_f,__you,__,_d,_are_,_t,_o,__,_f,_a,_c,_e,__,_me,_col,_RET
		.BYTE	_come_,_t,_o,__,_the_,_a,_m,_u,_s,_e,_me,_n,_t,__park_exc,_RET
		.BYTE	_I,_apo_ll_,_be_,_w,_a,_it,_ing,_exc,_WAIT
		.BYTE	_STOP
_msg44:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_O,_o,_h,__,_that_,_Fatcat,_exc,_RET
		.BYTE	_We_,_g,_o,_t,_t,_a_,_s,_t,_o,_p,__,_h,_i,_m,_exc,_WAIT
		.BYTE	_STOP
_msg45:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_W,_a,_it,_col_,_Dale,_exc,_RET
		.BYTE	_I,_t,__,_s,_me,_l,_l,_s,__,_l,_i,_k,_e,__,_a_,_t,_r,_a,_p,__to,__,_me,_exc,_WAIT
		.BYTE	_STOP
_msg46:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_You,_apo,_r,_e,__,_do,_o,_me,_d,_col,_RET
		.BYTE	_Rescue_,_Rangers,_exc,_WAIT
		.BYTE	_I,__,_c,_on,_t,_r,_o,_l,_RET
		.BYTE	_this,__,_e,_n,_t,_i,_r,_e_amusement,__park_exc,_RET
		.BYTE	_You,_apo_ll_,_n,_ever,__,_c,_a,_p,_t,_u,_r,_e,__,_me,_exc,_WAIT
		.BYTE	_STOP
_msg47:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_O,_h,__,_y,_e,_a,_h,_que,_RET
		.BYTE	_D,_on,_apo,_t,__,_b,_e,_t,__,_on,__,_it,_col_,_Fatcat,_exc,_WAIT
		.BYTE	_STOP
_msg48:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_H,_a,_exc__,_You,__,_n,_e,_ed,__,_t,_h,_r,_e,_e,__,_k,_e,_y,_s,_RET
		.BYTE	_t,_o,__,_e,_n,_t,_e,_r,__,_my_,_c,_on,_t,_r,_o,_l,__,_r,_o,_o,_m,_col,_WAIT
		.BYTE	_and_,_t,_he,_y,_apo,_r,_e,__,_a,_l,_l,__,_h,_i,_d,_d,_e,_n,_RET
		.BYTE	_in,__,_d,_if,_f,_e,_r,_e,_n,_t,__,_p,_a,_r,_t,_s,_RET
		.BYTE	_of_,_the_,_p,_a,_r,_k,_exc__,_H,_a,_v,_e,__,_f,_u,_n,_exc,_WAIT
		.BYTE	_STOP
_msg49:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_W,_e,_apo_ve_,_g,_o,_t,__to,__,_g,_e,_t,__,_the_,_k,_e,_y,_s,_exc,_WAIT
		.BYTE	_STOP
_msg4A:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_R,_ight,_o,_col_,_Dale,_exc,_RET
		.BYTE	_W,_here,__,_should_,_we,__go,__first,_que,_WAIT
		.BYTE	__,_rar,_Clock_Tower,_RET
		.BYTE	__,__,_Western__World,_RET
		.BYTE	__,__,_Future_World,_RET
		.BYTE	_STOP
_msg4B:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_Are_you_,_sure,_que,_RET
		.BYTE	__,_rar,_Y,_e,_s,__,__,_No,_RET
		.BYTE	_STOP
_msg4C:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Let_s_,_g,_o,__to,__,_t,_he,_RET
		.BYTE	_dict80,__first,_exc,_WAIT
		.BYTE	_STOP
_msg4D:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_We_,_f,_o,_u,_n,_d,__,_the_,_k,_e,_y,_exc,_RET
		.BYTE	_W,_here,__to,__,_n,_e,_x,_t,_exc,_que,_WAIT
		.BYTE	__,_rar,_dict80,_RET
		.BYTE	__,__,_dict81,_RET
		.BYTE	_STOP
_msg4E:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_dict80,_exc,__,_H,_u,_r,_r,_y,_exc,_WAIT
		.BYTE	_STOP
_msg4F:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_W,_e,_apo_ve_,_g,_o,_t,__,_t,_w,_o,__,_k,_e,_y,_s,_exc,_WAIT
		.BYTE	_T,_h,_a,_t,__,_me,_a,_n,_s,__,_the_,_l,_ast,__,_one,_RET
		.BYTE	_must_,_be_,_in,_RET
		.BYTE	_dict80,_exc,_WAIT
		.BYTE	_STOP
_msg50:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_R,_ight,_exc__,_Let_s_,_g,_o,_exc,_WAIT
		.BYTE	_STOP
_msg51:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_S,_h,_h,_h,_exc,_RET
		.BYTE	_Fatcat,__,_is_,_r,_ight,__,_in,_s,_i,_d,_e,_exc,_WAIT
		.BYTE	_STOP
_msg52:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_Let_s_,_u,_s,_e,__,_the_,_k,_e,_y,_s,_exc,_WAIT
		.BYTE	_STOP
_msg53:
		.BYTE	_Zipper,_ddt,_RET
		.BYTE	_dot_dot,__,_dot_dot_dot,__,_dot_dot,_WAIT
		.BYTE	_STOP
_msg54:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_I,_t,_apo,_s,__,_u,_n,_l,_o,_c,_k,_ed,_exc,_RET
		.BYTE	_O,_p,_e,_n,__,_the_,_do,_or,_exc,_WAIT
		.BYTE	_STOP
_msg55:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_W,_e,_apo_ve_,_g,_o,_t,__you,__,_now,_col_,_Fatcat,_exc,_RET
		.BYTE	_T,_he,__,_Rescue_,_Rangers,__,_are_,_here,_exc,_WAIT
		.BYTE	_STOP
_msg56:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_H,_e,_y,_exc__,_H,_e,_apo,_s,__go,_n,_e,_exc,_RET
		.BYTE	_W,_here,_apo,_d,__,_he,__go,_exc,_que,_WAIT
		.BYTE	_STOP
_msg57:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_Look,_col_,_ever,_y,_one,_exc,_RET
		.BYTE	_A,__,_s,_e,_c,_r,_e,_t,__,_p,_a,_s,_s,_a,_g,_e,_exc__,_Let_s_,_g,_o,_exc,_WAIT
		.BYTE	_STOP
_msg58:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_B,_e,__,_c,_a,_r,_e,_f,_u,_l,_exc__,_This_,_could_,_RET
		.BYTE	_be_,_o,_u,_r,__,_l,_ast,__,_s,_t,_a,_n,_d,_exc,_WAIT
		.BYTE	_STOP
_msg59:
		.BYTE	_RET
		.BYTE	_Let_s_,_g,_o,__,_Rescue_,_Rangers,_exc,_WAIT
		.BYTE	_STOP
_msg5A:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_Welcome,__,_Rescue_,_Rangers,_exc,_RET
		.BYTE	_I,_apo_ve_,_b,_e,_e,_n,__,_w,_a,_it,_ing,__for,__you,_exc,_WAIT
		.BYTE	_STOP
_msg5B:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_You,_apo_ll_,_n,_ever,__,_g,_e,_t,__,_a,_w,_a,_y,_col,_RET
		.BYTE	_Fatcat,_exc,_WAIT
		.BYTE	_STOP
_msg5C:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_S,_u,_r,_r,_e,_n,_d,_e,_r,_exc,_WAIT
		.BYTE	_STOP
_msg5D:
		.BYTE	_Fatcat,_ddt,_RET
		.BYTE	_You,_apo_ll_,_n,_ever,__,_d,_e,_f,_e,_a,_t,__,_me,_col,_RET
		.BYTE	_Rescue_,_Rangers,_exc,_WAIT
		.BYTE	_I,__,_have,__,_the_,_u,_l,_t,_i,_m,_a,_t,_e,__,_we,_a,_p,_on,_ddt,_RET
		.BYTE	_the_,_Fatcat,__,_R,_o,_b,_o,_t,_exc,_WAIT
		.BYTE	_STOP
_msg5E:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_D,_i,_d,__you,__,_he,_a,_r,__some,_t,_h,_ing,_exc,_que,_WAIT
		.BYTE	_STOP
_msg5F:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_Look,__,_out,__everyone,_WAIT
		.BYTE	_STOP
_msg60:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_T,_he,__,_c,_e,_i,_l,_ing,_exc,_RET
		.BYTE	_S,_he,_apo,_s,__,_g,_i,_v,_ing,__,_w,_a,_y,_exc,_WAIT
		.BYTE	_STOP
_msg61:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_G,_o_find,__,_c,_o,_v,_e,_r,_col_,_ever,_y,_one,_exc,_WAIT
		.BYTE	_Dale,__,_and_,_I,__will_,_t,_r,_a,_c,_k,_RET
		.BYTE	_Fatcat,_exc,_WAIT
		.BYTE	_STOP
_msg62:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_T,_a,_k,_e,__,_c,_are_,_of_,_y,_o,_u,_r,_s,_e,_l,_v,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg63:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_Chip,__,_and_,_Dale,__,_are_,_t,_r,_a,_p,_p,_ed,_RET
		.BYTE	_in,_s,_i,_d,_e,_exc,_WAIT
		.BYTE	_W,_e,_apo_ve_,_l,_o,_s,_t,__,_the_,_l,_a,_d,_s,__for,_ever,_dot,_WAIT
		.BYTE	_STOP
_msg64:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_Chip,_exc__,_Dale,_exc,_RET
		.BYTE	_T,_h,_a,_n,_k,__go,_o,_d,_n,_e,_s,_s,__you,_apo,_r,_e,__,_s,_a,_f,_e,_exc,_WAIT
		.BYTE	_STOP
_msg65:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_We_,_a,_l,_m,_o,_s,_t,__,_d,_i,_d,_n_apo_t,__,_m,_a,_k,_e,__,_it,_exc,_WAIT
		.BYTE	_STOP
_msg66:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_A,_n,_d,__,_we,__,_n,_ever,__,_d,_i,_d,__,_c,_a,_p,_t,_u,_r,_e,_RET
		.BYTE	_Fatcat,_dot,_WAIT
		.BYTE	_H,_e,__,_must_,_s,_t,_i,_l,_l,_RET
		.BYTE	_be_,_t,_r,_a,_p,_p,_ed,__,_in,_s,_i,_d,_e,_dot,_WAIT
		.BYTE	_STOP
_msg67:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_B,_ut,__,_if,__,_I,__,_k,_now,__,_Fatcat,_col_,_he,__,_h,_a,_d,_RET
		.BYTE	_h,_is_,_escape,__,_we,_l,_l,__,_p,_l,_a,_n,_n,_ed,_dot,_WAIT
		.BYTE	_STOP
_msg68:
		.BYTE	_Monterey,_ddt,_RET
		.BYTE	_W,_e,_l,_l,_col_,_if,__,_not,_h,_ing,__,_e,_l,_s,_e,_col,_WAIT
		.BYTE	_we,__made,_RET
		.BYTE	_that_,_b,_l,_ight,_e,_r,_apo,_s,__,_l,_if,_e,_RET
		.BYTE	_a_,_l,_it,_t,_l,_e,__,_less,__,_c,_u,_s,_h,_y,_col_,_e,_h,_que,_WAIT
		.BYTE	_STOP
_msg69:
		.BYTE	_Dale,_ddt,_RET
		.BYTE	_You,__,_s,_a,_i,_d,__,_it,_exc,_WAIT
		.BYTE	_STOP
_msg6A:
		.BYTE	_Gadget,_ddt,_RET
		.BYTE	_A,_n,_d,__,_if,_RET
		.BYTE	_he,__,_ever,__,_s,_h,_o,_w,_s,__,_u,_p,__,_a,_g,_a,_in,_dot_dot_dot,_WAIT
		.BYTE	_STOP
_msg6B:
		.BYTE	_Chip,_ddt,_RET
		.BYTE	_T,_he,_n,__,_I,__,_g,_u,_e,_s,_s,__,_we,_apo_ll_,_j,_u,_s,_t,__,_have,_RET
		.BYTE	_t,_o,__,_t,_e,_a,_c,_h,__,_h,_i,_m,__,_a,_not,_he,_r,__,_less,_on,_exc,_WAIT
		.BYTE	_R,_ight,__,_Rangers,_que,_exc,_WAIT
		.BYTE	_STOP
_msg6C:
		.BYTE	_RET
		.BYTE	_R,_ight,_exc__,_W,_a,_t,_c,_h,__,_out,_col_,_Fatcat,_exc,_WAIT
		.BYTE	_RET
		.BYTE	_W,_e,_apo,_r,_e,__,_the_,_Rescue_,_Rangers,_exc,_WAIT
		.BYTE	_STOP

#endif

		SECTION_END		03, "MESSAGES DICT AND DATA"

		SECTION_START	04

byte_3A72C:
		.BYTE	$01,$00

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub06_B_A:
		LDA		#$04
		STA		_players_vars0A,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub04_A:
		LDA		#$03
		STA		_players_vars0A,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0A_B:
		LDA		#$00
		STA		_players_vars0A,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_obj_insert:
		LDA		_obj_x_lo_poss,X
		STA		_players_x_poss,X
		LDA		_obj_y_lo_poss,X
		STA		_players_y_poss,X
		LDA		#$00
		STA		_obj_x_hi_poss,X
		STA		_obj_y_hi_poss,X
		STA		_scr_idxBs,X
		STA		_obj_spr_idxs,X
		STA		_scr_idxCs,X
		STA		_scr_vars20,X
		STA		_obj_flips,X
		STA		_players_x_deltas,X
		STA		_players_vars0A,X
		STA		_players_vars0F,X
		STA		_players_vars0D,X
		STA		_players_vars0C,X
		STA		_players_vars07,X
		STA		_players_vars10,X
		LDA		#$80
		STA		_scr_vars21,X
		LDA		_players_nums,X
		STA		_obj_spr_libs,X
		LDA		_obj_x_lo_poss,X
		BMI		loc_3A780
		LDA		#$40
		STA		_obj_flips,X
loc_3A780:
		LDA		#$02
		STA		_scr_params,X
		LDA		_players_lives,X
		BNE		loc_3A78C
		JMP		_players_obj_insert_A
loc_3A78C:
		LDA		_players_max_hps,X
		STA		_obj_hps,X
		LDA		#$06
		STA		_obj_widths,X
		LDA		#$16
		STA		_obj_heights,X
		LDY		#$05
		LDA		_room_flags
		AND		#$04
		BEQ		loc_3A7A5
		LDY		#$04
loc_3A7A5:
		TYA
		STA		_players_states,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_manager:
		LDX		_scr_idx
		BNE		locret_3A7DC
		LDA		_nmi_frames_counter
		AND		#$01
		TAY
		LDA		_players_lives,Y
		BNE		loc_3A7BB
		LDA		byte_3A72C,Y
		TAY
loc_3A7BB:
		STY		byte_AB
		JSR		_players_animA
loc_3A7C0:
		LDX		_scr_idx
		LDA		_players_states,X
		CMP		#$18
		BCS		loc_3A7CB
		JSR		_players_animB
loc_3A7CB:
		INC		_scr_idx
		LDA		_scr_idx
		CMP		#$02
		BCC		loc_3A7C0
		JSR		_players_animC
		LDX		#$00
		STX		_scr_idx
		STX		byte_E3
locret_3A7DC:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB:
		LDA		_obj_heights,X
		BEQ		_j_players_animB_sub0129
		LDA		_players_vars07,X
		PHA
		AND		#$F7
		STA		_players_vars07,X
		PLA
		AND		#$08
		BEQ		loc_3A7F1
		JMP		_players_animB_sub58
loc_3A7F1:
		LDA		_players_vars0D,X
		BNE		_j_players_animB_sub0129
		LDA		_obj_flips,X
		AND		#$04
		BNE		_j_players_animB_sub0129
		JSR		_players_animB_A
		BCC		_j_players_animB_sub0129
		TYA
		STA		_scr_idxAs,X
		LDA		_scr_params,Y
		AND		#$0F
		JSR		_switch
		.WORD	_players_animB_sub0129
		.WORD	_players_animB_sub0129
		.WORD	_players_animB_sub0129
		.WORD	_players_animB_sub3
		.WORD	_players_animB_sub58
		.WORD	_players_animB_sub58
		.WORD	_players_animB_sub67
		.WORD	_players_animB_sub67
		.WORD	_players_animB_sub58
		.WORD	_players_animB_sub0129
		.WORD	_players_animB_subA

; =============== S U B R O U T I N E =======================================
_j_players_animB_sub0129:
		JMP		_players_animB_sub0129

; =============== S U B R O U T I N E =======================================
_players_animB_sub3:
		JSR		_get_box_bonus_special_pickup
		BMI		_j_players_animB_sub0129
		LDX		_scr_idx
		LDA		_scr_idxCs,X
		AND		#$20
		BNE		_j_players_animB_sub0129
		LDY		_scr_idxAs,X
		LDA		_obj_damages,Y
		CMP		#_OBJ_DMG_STUN
		BEQ		_players_animB_sub3_A
		LDA		#$00
		STA		_obj_hps,Y
		STA		_obj_damages,Y
		LDA		_pads,X
		AND		#$02
		BEQ		_players_animB_sub3_A
		LDA		_scr_idxBs,X
		AND		#$40
		BNE		_players_animB_sub3_A
		LDA		_scr_idxBs,Y
		AND		#$20
		BNE		_players_animB_sub3_A
		LDA		#$04
		STA		_players_vars0B,X
		LDA		#$10
		STA		_players_states,X
		LDA		#$00
		STA		_players_anim_idxs,X
		JSR		_players_animB_sub3_B
		STX		_tmp_ptrE
		STY		_tmp_ptrE+1
		TYA
		TAX
		JSR		_scr_destr_jump
		LDX		_tmp_ptrE
		LDY		_tmp_ptrE+1
		JSR		_players_pickup_obj_flags_update
		JMP		_players_animB_sub0129

; =============== S U B R O U T I N E =======================================
_players_animB_sub58:
		LDX		_scr_idx
		LDA		_scr_idxCs,X
		AND		#$20
		BNE		_players_animB_sub0129

; =============== S U B R O U T I N E =======================================
_players_animB_sub3_A:
		JSR		_players_animB_sub3_B
		LDA		#$00
		STA		_obj_y_deltas,X
		LDA		#$0E
		STA		_players_states,X
		BNE		_players_animB_sub0129

; =============== S U B R O U T I N E =======================================
_players_animB_sub67:
		LDX		_scr_idx
		LDA		_obj_damages,X
		CMP		#_OBJ_DMG_STUN
		BEQ		_players_animB_sub0129
		LDY		_scr_idxAs,X
		LDA		_obj_damages,Y
		BEQ		_players_animB_sub0129
		LDA		#$20
		STA		_obj_x_deltas,X
		JSR		_players_animB_sub67_A
		JSR		_players_animB_sub0129_sub06_B_A
		LDA		_players_vars07,X
		ORA		#$80
		STA		_players_vars07,X
		BNE		_players_animB_sub0129

; =============== S U B R O U T I N E =======================================
_players_animB_subA:
		LDX		_scr_idx
		LDY		_scr_idxAs,X
		LDA		#$00
		STA		_obj_hps,Y
		LDA		_scr_idx
		STA		_scr_idxAs,Y

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129:
		LDX		_scr_idx
		LDA		_players_vars07,X
		AND		#$80
		BEQ		loc_3A8D1
		JSR		_players_animB_sub0129_A
loc_3A8D1:
		LDX		_scr_idx
		LDA		#$00
		STA		_players_vars09,X
		LDA		#$80
		STA		_scr_vars21,X
		LDA		_obj_x_lo_poss,X
		STA		_players_x_poss,X
		LDA		_obj_y_lo_poss,X
		STA		_players_y_poss,X
		LDA		_players_vars07,X
		AND		#$40
		BEQ		loc_3A8FA
		LDA		_pads,X
		AND		#$0C
		ORA		#$C0
		STA		_pads,X
		LDA		_pads+4,X
		AND		#$0C
		STA		_pads+4,X
loc_3A8FA:
		LDA		_players_states,X
		LDY		#<[loc_3A935-1]
		LDX		#>[loc_3A935-1]
		JSR		_switch_param_ret
		.WORD	_players_animB_sub0129_sub00
		.WORD	_players_animB_sub0129_sub01
		.WORD	_players_animB_sub0129_sub02
		.WORD	_players_animB_sub0129_sub03
		.WORD	_players_animB_sub0129_sub04
		.WORD	_players_animB_sub0129_sub05
		.WORD	_players_animB_sub0129_sub06
		.WORD	_players_animB_sub0129_sub07
		.WORD	_players_animB_sub0129_sub08
		.WORD	_players_animB_sub0129_sub09
		.WORD	_players_animB_sub0129_sub0A
		.WORD	_players_animB_sub0129_sub0B
		.WORD	_players_animB_sub0129_sub0C
		.WORD	_players_animB_sub0129_sub0D
		.WORD	_players_animB_sub0129_sub0E
		.WORD	_players_animB_sub0129_sub0F
		.WORD	_players_animB_sub0129_sub10
		.WORD	_players_animB_sub0129_sub11
		.WORD	_players_animB_sub0129_sub12
		.WORD	_players_animB_sub0129_sub13
		.WORD	_players_animB_sub0129_sub05
		.WORD	_players_animB_sub0129_sub15
		.WORD	_players_animB_sub0129_sub16
		.WORD	_players_animB_sub0129_sub17
		.WORD	nullsub10
loc_3A935:
		LDX		_scr_idx
		LDA		_players_states,X
		CMP		#$14
		BCS		loc_3A940
		JSR		_players_animB_sub0129_B
loc_3A940:
		JSR		_players_animB_sub0129_C
		LDA		#$00
		STA		_players_vars0E,X
		LDA		_players_vars0D,X
		CMP		#$02
		BCS		loc_3A980
		LDA		_players_vars0A,X
		CMP		#$03
		BEQ		loc_3A980
		BCS		loc_3A958
		JSR		_players_animB_sub0129_D
loc_3A958:
		LDA		_obj_x_lo_poss,X
		PHA
		LDA		_obj_x_deltas,X
		PHA
		CLC
		ADC		_players_x_deltas,X
		STA		_obj_x_deltas,X
		BEQ		loc_3A973
		BPL		loc_3A970
		JSR		_players_animB_sub0129_E
		JMP		loc_3A973
loc_3A970:
		JSR		_players_animB_sub0129_F
loc_3A973:
		LDX		_scr_idx
		PLA
		STA		_obj_x_deltas,X
		PLA
		SEC
		SBC		_obj_x_lo_poss,X
		STA		_players_x_speeds,X
loc_3A980:
		LDA		#$00
		STA		_players_x_deltas,X
		LDA		_obj_heights,X
		PHA
		LDX		_scr_idx
		LDA		_players_vars0D,X
		BEQ		loc_3A9A9
		LSR
		LSR
		AND		#$03
		TAY
		LDA		byte_3B40F,Y
		STA		_obj_spr_idxs,X
		INC		_players_vars0D,X
		LDA		_players_vars0D,X
		AND		#$0F
		STA		_players_vars0D,X
		LDA		#$16
		STA		_obj_heights,X
		JMP		loc_3A9E9
loc_3A9A9:
		LDY		_players_anim_idxs,X
		LDA		_scr_idxBs,X
		AND		#$40
		BNE		loc_3A9C4
		CPY		#$00
		BNE		loc_3A9C5
		DEC		_scr_vars20,X
		LDA		_scr_vars20,X
		AND		#$70
		BNE		loc_3A9CA
		LDY		#$02
		BNE		loc_3A9CA
loc_3A9C4:
		INY
loc_3A9C5:
		LDA		#$00
		STA		_scr_vars20,X
loc_3A9CA:
		LDA		byte_3B3EF,Y
		STA		_obj_spr_idxs,X
		BPL		loc_3A9DD
		AND		#$7F
		STA		_obj_heights,X
		JSR		_scr_param_80_set
		JMP		loc_3A9EC
loc_3A9DD:
		CPY		#$24
		LDY		#$16
		BCC		loc_3A9E5
		LDY		#$10
loc_3A9E5:
		TYA
		STA		_obj_heights,X
loc_3A9E9:
		JSR		_scr_param_80_clear
loc_3A9EC:
		PLA
		CMP		_obj_heights,X
		BCS		loc_3AA1C
		JSR		_players_animB_sub0129_G
		BPL		loc_3AA08
		LDY		_scr_idxBs,X
		TYA
		AND		#$40
		BEQ		loc_3AA1C
		TYA
		AND		#$0F
		TAX
		JSR		_players_animB_sub0129_G
		BMI		loc_3AA1C
loc_3AA08:
		CLC
		LDX		_scr_idx
		LDA		_obj_y_lo_poss,X
		SBC		_obj_heights,X
		STA		_obj_y_lo_poss,Y
		LDA		_obj_y_hi_poss,X
		SBC		#$00
		STA		_obj_y_hi_poss,Y
loc_3AA1C:
		LDX		_scr_idx
		LDA		_players_vars0F,X
		BEQ		loc_3AA36
		DEC		_players_vars0F,X
		BNE		loc_3AA36
		JSR		_scr_flips_10_clear
		LDA		_obj_hps,X
		BEQ		loc_3AA36
		LDA		_scr_idxBs,X
		BMI		loc_3AA36
		JSR		_scr_flips_04_clear
loc_3AA36:
		LDA		_players_vars07,X
		AND		#$40
		BEQ		nullsub10
		LDA		_obj_flips,X
		AND		#$20
		ORA		_obj_x_hi_poss,X
		BEQ		nullsub10
		LDA		#$80
		STA		_stage_flags

; =============== S U B R O U T I N E =======================================
nullsub10:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub00:
		JSR		_players_animB_sub0129_sub00_A
		BCS		_players_animB_sub0129_sub01_B

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub02_A:
		LDX		_scr_idx
		LDA		#$14
		STA		_players_anim_idxs,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0A_A:
		LDA		#$00
		STA		_obj_y_deltas,X
		LDA		#$01
		STA		_players_states,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub01:
		JSR		_players_animB_sub0129_sub01_A
		BCS		_players_animB_sub0129_sub01_B
		JMP		_players_animB_sub0129_sub01_C

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub01_B:
		LDA		#_apu_mus72_idx
		JSR		_apu_se_req
		LDA		#$00
		STA		_players_vars0B,X
		LDA		#$02
		STA		_players_states,X
		LDA		#$1E
		STA		_players_anim_idxs,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub02:
		JSR		_players_animB_sub0129_sub00_A
		BCC		_players_animB_sub0129_sub02_A
		LDA		_pads+4,X
		AND		#$01
		BEQ		loc_3AA88
		JMP		_players_animB_sub0129_sub02_B
loc_3AA88:
		LDA		_pads,X
		AND		#$C0
		BNE		loc_3AA97
		INC		_players_vars0B,X
		LDA		_players_vars0B,X
		CMP		#$05
		BCS		loc_3AA97
		RTS
loc_3AA97:
		LDA		_pads,X
		AND		#$20
		BEQ		_players_animB_sub0129_sub02_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub02_C:
		LDA		#$03
		STA		_players_states,X
		LDA		#$00
		STA		_players_vars0B,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub03:
		JSR		_players_animB_sub0129_sub00_A
		BCC		_players_animB_sub0129_sub02_A
		STA		_tmp_ptrE+1
		JSR		_players_animB_sub0129_sub03_A
		BCC		nullsub11
		LDA		_pads,X
		AND		#$20
		BEQ		_players_animB_sub0129_sub02_D
		LDA		_tmp_ptrE+1
		CMP		#$02
		BEQ		nullsub11
		LDA		_pads+4,X
		AND		#$01
		BEQ		nullsub11
		LDY		#$D0
		JSR		_obj_to_tile_collision_test_down
		BCS		nullsub11
		JMP		_players_animB_sub0129_sub02_A

; =============== S U B R O U T I N E =======================================
nullsub11:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub02_D:
		LDA		#$05
		STA		_players_states,X
		LDA		#$00
		STA		_players_anim_idxs,X
		LDA		#$00
		STA		_players_vars0B,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub04:
		LDX		_scr_idx
		LDA		#$00
		STA		_players_anim_idxs,X
		JMP		_players_animB_sub0129_sub04_A

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05:
		JSR		_players_animB_sub0129_sub00_A
		BCS		loc_3AAF3
		LDA		_players_states,X
		CMP		#$14
		BCS		loc_3AAF9
		JMP		_players_animB_sub0129_sub02_A
loc_3AAF3:
		JSR		_players_animB_sub0129_sub01_C
		BEQ		loc_3AAF9
		RTS
loc_3AAF9:
		LDA		_pads,X
		AND		#$20
		BNE		_players_animB_sub0129_sub02_C
		LDA		_pads+4,X
		AND		#$01
		BEQ		loc_3AB08
		JMP		_players_animB_sub0129_sub02_B
loc_3AB08:
		LDA		_pads,X
		AND		#$C0
		BEQ		_players_animB_sub0129_sub02_D
		JMP		loc_3AB70

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub06:
		LDX		_scr_idx
		LDA		_obj_flips,X
		ORA		#$8C
		STA		_obj_flips,X
		JSR		_players_animB_sub0129_sub04_A
		INC		_players_states,X
		JSR		_native_obj_disable_from_idxCs_40_flag

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub07:
		LDX		_scr_idx
		LDA		_scr_idxBs,X
		AND		#$0F
		TAY
		LDA		_obj_hps,Y
		BNE		loc_3AB4B
		LDA		_scr_idxBs,Y
		AND		#$BF
		STA		_scr_idxBs,Y
		LDA		_scr_idxBs,X
		AND		#$7F
		STA		_scr_idxBs,X
		LDA		_obj_flips,X
		AND		#$D3
		STA		_obj_flips,X
		JMP		_players_animB_sub0129_sub06_B
loc_3AB4B:
		LDA		_scr_idxBs,X
		BMI		loc_3AB53
		JMP		_players_animB_sub0129_sub06_B
loc_3AB53:
		JSR		_players_animB_sub0129_sub06_C
		LDA		_obj_x_lo_poss,X
		STA		_players_x_poss,X
		LDA		_obj_y_lo_poss,X
		STA		_players_y_poss,X
		LDA		#_OBJ_DMG_NONE
		LDY		_obj_damages,X
		STA		_obj_damages,X
		CPY		#_OBJ_DMG_STUN
		BNE		loc_3AB70
		LDA		#$0C
		BNE		loc_3AB72
loc_3AB70:
		LDA		#$04
loc_3AB72:
		STA		_tmp_ptr0
		LDA		_players_vars0B,X
		INC		_players_vars0B,X
		LSR
		LSR
		AND		#$06
		CLC
		ADC		_tmp_ptr0
		STA		_players_anim_idxs,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub02_B:
		LDX		_scr_idx
		LDA		#$92
		STA		_obj_y_deltas,X
		LDA		#$08
		STA		_players_states,X
		LDA		#$14
		STA		_players_anim_idxs,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub08:
		JSR		_players_animB_sub0129_sub08_A
		BEQ		loc_3ABC6
		LDA		_pads,X
		AND		#$01
		BEQ		loc_3ABC6
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub09:
		LDX		_scr_idx
		LDA		#$1A
		STA		_players_anim_idxs,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub09_A:
		LDA		#$B0
		STA		_obj_y_deltas,X
		LDA		#$0A
		STA		_players_states,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0A:
		JSR		_players_animB_sub0129_sub08_A
		BEQ		loc_3ABB3
		RTS
loc_3ABB3:
		LDA		_obj_flips,X
		AND		#$7F
		STA		_obj_flips,X
		LDA		_obj_hps,X
		BNE		loc_3ABC3
		JMP		_players_animB_sub0129_sub0A_A
loc_3ABC3:
		JSR		_players_animB_sub0129_sub0A_B
loc_3ABC6:
		JSR		_players_animB_sub0129_sub00_A
		BCS		loc_3ABCE
		JMP		_players_animB_sub0129_sub02_A
loc_3ABCE:
		JMP		_players_animB_sub0129_sub02_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub06_B:
		LDA		#$00
		STA		_players_vars0F,X
		LDA		_obj_flips,X
		EOR		#$40
		STA		_obj_flips,X
		LDA		#$40
		STA		_obj_x_deltas,X
		LDA		_obj_flips,X
		AND		#$40
		BNE		loc_3ABEE
		LDA		#$C0
		STA		_obj_x_deltas,X
loc_3ABEE:
		JSR		_players_animB_sub0129_sub06_B_A
		LDA		_obj_damages,X
		CMP		#_OBJ_DMG_STUN
		BEQ		loc_3AC00
		LDA		#_OBJ_DMG_NONE
		STA		_obj_damages,X
		JMP		_players_animB_sub0129_sub09_A
loc_3AC00:
		LDA		#_apu_mus28_idx
		JSR		_apu_se_req
		LDX		_scr_idx
		LDA		#$0B
		STA		_players_states,X
		LDA		#$18
		STA		_players_vars0B,X
		LDA		_obj_flips,X
		AND		#$7F
		STA		_obj_flips,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0B:
		LDX		_scr_idx
		LDA		_players_vars0E,X
		BNE		loc_3AC38
		DEC		_players_vars0B,X
		BEQ		loc_3AC2D
		LDA		_players_vars0B,X
		LSR
		LSR
		AND		#$02
		CLC
		ADC		#$24
		STA		_players_anim_idxs,X
		RTS
loc_3AC2D:
		LDA		#_OBJ_DMG_NONE
		STA		_obj_damages,X
		JSR		_players_animB_sub0129_sub0A_B
		JMP		_players_animB_sub0129_sub02_D
loc_3AC38:
		LDA		#_apu_mus2B_idx
		JSR		_apu_se_req
		LDA		#_OBJ_DMG_NONE
		STA		_obj_damages,X
		JSR		_players_animB_sub0129_sub04_A
		INC		_players_states,X
		LDA		#$28
		STA		_players_anim_idxs,X
		LDA		#$01
		STA		_players_vars0B,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0C:
		LDX		_scr_idx
		DEC		_players_vars0B,X
		BEQ		loc_3AC57
		RTS
loc_3AC57:
		LDA		#$00
		STA		_obj_y_deltas,X
		INC		_players_states,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0D:
		JSR		_players_animB_sub0129_sub00_A
		BCS		loc_3AC6A
		JSR		_players_animB_sub0129_sub01_A
		BCS		loc_3AC6A
		RTS
loc_3AC6A:
		LDX		_scr_idx
		JSR		_players_animB_sub0129_sub04_A
		LDA		#$00
		STA		_obj_y_deltas,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0E:
		LDA		#_apu_mus26_idx
		JSR		_apu_se_req
		LDX		_scr_idx
		LDA		#$0F
		STA		_players_states,X
		LDA		#$78
		STA		_players_vars0B,X
		LDA		#$18
		STA		_players_anim_idxs,X
		JSR		_players_animB_sub0129_sub0E_A

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub0F:
		LDX		_scr_idx
		LDA		_obj_y_deltas,X
		BEQ		loc_3AC98
		BPL		loc_3AC9D
		JSR		_players_animB_sub0129_sub08_A
		BNE		loc_3ACAA
loc_3AC98:
		JSR		_players_animB_sub0129_sub00_A
		BCS		loc_3ACA2
loc_3AC9D:
		JSR		_players_animB_sub0129_sub01_A
		BCC		loc_3ACAA
loc_3ACA2:
		LDA		#$00
		STA		_obj_x_deltas,X
		STA		_obj_y_deltas,X
loc_3ACAA:
		DEC		_players_vars0B,X
		BEQ		loc_3ACAF
		RTS
loc_3ACAF:
		JSR		_players_animB_sub0129_sub0A_B
		JSR		_native_obj_disable_from_idxCs_40_flag
		JMP		_players_animB_sub0129_sub02_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub3_B:
		LDA		#$F8
		STA		_obj_x_deltas,X
		JSR		_players_animB_sub3_B_A
		JSR		_players_animB_sub0129_sub06_B_A
		LDA		_obj_flips,X
		AND		#$7F
		STA		_obj_flips,X
		JMP		_scr_param_80_clear

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub10:
		LDX		_scr_idx
		LDA		_pads,X
		AND		#$3F
		STA		_pads,X
		DEC		_players_vars0B,X
		BEQ		loc_3ACDB
		RTS
loc_3ACDB:
		JSR		_players_animB_sub0129_sub0A_B
		JMP		_players_animB_sub0129_sub02_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub11:
		JSR		_players_animB_sub0129_sub11_A
		JSR		_players_animB_sub0129_sub11_B
		LDA		_players_vars07,X
		AND		#$20
		BNE		loc_3AD13
		INC		_players_states,X
		BNE		loc_3AD13

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12:
		JSR		_players_animB_sub0129_sub11_A
		JSR		_players_animB_sub0129_sub0A_B
		LDA		_obj_y_deltas,X
		BMI		loc_3AD0D
		CMP		#$24
		BCC		loc_3AD0D
		LDA		_players_vars07,X
		AND		#$20
		BNE		loc_3AD09
		JMP		_players_animB_sub0129_sub00
loc_3AD09:
		DEC		_players_states,X
		BNE		loc_3AD13
loc_3AD0D:
		CLC
		ADC		#$06
		STA		_obj_y_deltas,X
loc_3AD13:
		LDA		_scr_vars19,X
		INC		_scr_vars19,X
		LSR
		LSR
		AND		#$06
		CLC
		ADC		#$2A
		STA		_players_anim_idxs,X
		LDA		_nmi_frames_counter
		AND		#$0F
		BNE		loc_3AD2D
		LDA		#_apu_mus47_idx
		JSR		_apu_se_req
loc_3AD2D:
		JSR		_players_animB_sub0129_sub12_A
		BCC		locret_3AD3A
		LDA		#$00
		STA		_obj_y_deltas,X
		JMP		_players_animB_sub0129_sub01_B
locret_3AD3A:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub11_A:
		LDX		_scr_idx
		LDA		_obj_y_deltas,X
		BPL		loc_3AD48
		CMP		#$DC
		BCS		loc_3AD48
		LDA		#$DC
loc_3AD48:
		SEC
		SBC		#$03
		STA		_obj_y_deltas,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12_A:
		CLC
		LDA		_obj_y_deltas,X
		BEQ		locret_3AD5D
		BMI		loc_3AD5A
		JMP		_players_animB_sub0129_sub12_A_A
loc_3AD5A:
		JMP		_players_animB_sub0129_sub12_A_B
locret_3AD5D:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub13:
		LDX		_scr_idx
		LDA		#$00
		STA		_obj_x_deltas,X
		JSR		_players_animB_sub0129_sub06_B_A
		LDA		#$48
		STA		_players_anim_idxs,X
		LDA		_pads+4,X
		AND		#$01
		BEQ		loc_3AD78
		JSR		_players_animB_sub0129_sub0A_B
		JMP		_players_animB_sub0129_sub02_B
loc_3AD78:
		JMP		_players_animB_sub0129_sub00_A

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub15:
		LDX		_scr_idx
		DEC		_obj_y_lo_poss,X
		DEC		_obj_y_lo_poss,X
		LDA		_obj_y_lo_poss,X
		CMP		#$40
		BCS		loc_3AD9D
		INC		_players_states,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub16:
		LDX		_scr_idx
		INC		_obj_y_lo_poss,X
		INC		_obj_y_lo_poss,X
		LDA		_obj_y_lo_poss,X
		CMP		#$B8
		BCC		loc_3AD9D
		DEC		_players_states,X
loc_3AD9D:
		LDA		_pads,X
		AND		#$40
		BEQ		loc_3ADB7
		DEC		_obj_x_lo_poss,X
		DEC		_obj_x_lo_poss,X
		LDA		_obj_x_lo_poss,X
		CMP		#$12
		BCS		loc_3ADCF
		LDA		#$12
		STA		_obj_x_lo_poss,X
		BNE		loc_3ADCF
loc_3ADB7:
		LDA		_pads,X
		AND		#$80
		BEQ		loc_3ADCF
		INC		_obj_x_lo_poss,X
		INC		_obj_x_lo_poss,X
		LDA		_obj_x_lo_poss,X
		CMP		#$EE
		BCC		loc_3ADCF
		LDA		#$EE
		STA		_obj_x_lo_poss,X
loc_3ADCF:
		CPX		byte_AB
		BNE		locret_3ADE8
		DEC		_players_vars0B,X
		BEQ		loc_3ADDD
		LDA		_pads,X
		AND		#$01
		BEQ		locret_3ADE8
loc_3ADDD:
		LDA		_players_vars08,X
		BNE		loc_3ADE6
		JSR		_players_animB_sub0129_sub16_E
		BCC		loc_3ADE9
loc_3ADE6:
		INC		_players_vars0B,X
locret_3ADE8:
		RTS
loc_3ADE9:
		LDA		_obj_flips,X
		AND		#$F3
		STA		_obj_flips,X
		JSR		_players_animB_sub0129_sub0A_B
		JMP		_players_animB_sub0129_sub02_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub17:
		LDX		_scr_idx
		DEC		_players_vars0B,X
		BNE		locret_3AE0C
		LDY		byte_3A72C,X
		LDA		_obj_hps,Y
		BNE		loc_3AE0D
		LDA		_obj_y_hi_poss,Y
		BNE		loc_3AE0D
		INC		_players_vars0B,X
locret_3AE0C:
		RTS
loc_3AE0D:
		LDA		_players_lives,X
		BEQ		loc_3AE4F
		LDY		byte_3A72C,X
		LDA		_obj_hps,Y
		BEQ		loc_3AE5F
		LDA		_players_def_max_hps,X
		STA		_players_max_hps,X
		LDA		byte_E3
		BNE		loc_3AE64
		LDA		_obj_x_lo_poss,Y
		STA		_obj_x_lo_poss,X
		LDA		_obj_y_lo_poss,Y
		SEC
		SBC		#$28
		STA		_obj_y_lo_poss,X
		JSR		_players_obj_insert
		LDA		#$F0
		STA		_players_vars0B,X
		LDA		_obj_flips,X
		ORA		#$0C
		STA		_obj_flips,X
		LDA		#$1C
		STA		_players_anim_idxs,X
		LDA		#$15
		STA		_players_states,X
		LDA		#_apu_mus2C_idx
		JSR		_apu_se_req
		JMP		_players_animB_sub0129_sub04_A
loc_3AE4F:
		LDA		#$00
		STA		_players_rr_ptss,X
		LDY		byte_3A72C,X
		LDA		_players_lives,Y
		BNE		_players_obj_insert_A
		LDA		#$07
		STA		_main_sub_idx
loc_3AE5F:
		LDA		#$40
		STA		_stage_flags
		RTS
loc_3AE64:
		LDY		byte_E3
		SEC
		LDA		_obj_y_lo_poss,Y
		SBC		_obj_heights,Y
		STA		_obj_y_lo_poss,X
		LDA		_obj_x_lo_poss,Y
		LDY		byte_3A72C,X
		CMP		_obj_x_lo_poss,Y
		BCC		loc_3AE87
		CLC
		LDA		_obj_x_lo_poss,Y
		ADC		#$0F
		STA		_obj_x_lo_poss,X
		JMP		loc_3AE90
loc_3AE87:
		SEC
		LDA		_obj_x_lo_poss,Y
		SBC		#$0F
		STA		_obj_x_lo_poss,X
loc_3AE90:
		JSR		_players_obj_insert
		JSR		_scr_flips_04_set
		JSR		_scr_flips_10_set
		LDA		#$3C
		STA		_players_vars0F,X
		JMP		_players_animB_sub0129_sub02_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_B:
		LDX		_scr_idx
		LDA		_obj_y_hi_poss,X
		BMI		locret_3AECA
		BNE		loc_3AEB0
		LDA		_obj_y_lo_poss,X
		CMP		#$E8
		BCC		locret_3AECA
loc_3AEB0:
		JSR		_players_animB_sub0129_sub11_B
		JSR		_native_obj_disable_from_idxCs_40_flag
		LDA		#$3C
		STA		_players_vars0B,X
		LDA		_obj_hps,X
		BEQ		loc_3AEC6
		LDA		#$00
		STA		_obj_hps,X
		DEC		_players_lives,X
loc_3AEC6:
		LDA		#$17
		BNE		_players_obj_insert_ex
locret_3AECA:
		RTS

; =============== S U B R O U T I N E =======================================
_players_obj_insert_A:
		LDA		#$18

; =============== S U B R O U T I N E =======================================
_players_obj_insert_ex:
		STA		_players_states,X
		LDA		#$02
		STA		_obj_y_hi_poss,X
		LDA		_obj_flips,X
		ORA		#$0C
		STA		_obj_flips,X
		JSR		_scr_param_80_set
		JSR		_players_animB_sub0129_sub04_A
		CLC
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub16_E:
		STX		_tmp_ptrE
		LDY		#$0B
loc_3AEE8:
		CPY		_tmp_ptrE
		BEQ		loc_3AF16
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$02
		BCC		loc_3AF16
		BNE		loc_3AF09
		LDA		_scr_idxBs,Y
		AND		#$40
		BEQ		loc_3AF11
		LDA		_scr_idxBs,Y
		AND		#$0F
		CMP		_tmp_ptrE
		BEQ		loc_3AF16
		BNE		loc_3AF11
loc_3AF09:
		CMP		#$05
		BEQ		loc_3AF11
		CMP		#$09
		BNE		loc_3AF16
loc_3AF11:
		JSR		_obj_to_obj_collision_test
		BCS		locret_3AF1A
loc_3AF16:
		DEY
		BPL		loc_3AEE8
		CLC
locret_3AF1A:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub03_A:
		SEC
		LDY		#$32
		LDA		_scr_idxBs,X
		AND		#$40
		BEQ		loc_3AF64
		LDA		_scr_idxBs,X
		AND		#$0F
		TAY
		LDA		_scr_idxBs,Y
		LDY		#$00
		AND		#$10
		BEQ		loc_3AF64
		LDA		_players_vars0B,X
		CMP		#$0B
		BCC		loc_3AF49
		CMP		#$70
		BCS		loc_3AF49
		INC		_players_vars09,X
		LDA		_obj_flips,X
		AND		#$40
		BEQ		loc_3AF49
		INC		_players_vars09,X
loc_3AF49:
		LDA		_players_vars0B,X
		CMP		#$0B
		BCC		loc_3AF51
		LDA		#$0A
loc_3AF51:
		ASL
		CLC
		ADC		#$32
		TAY
		INC		_players_vars0B,X
		LDA		_players_vars0B,X
		CMP		#$80
		BCC		loc_3AF62
		LDA		#$0B
		STA		_players_vars0B,X
loc_3AF62:
		CMP		#$05
loc_3AF64:
		TYA
		STA		_players_anim_idxs,X
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub00_A:
		CLC
		LDX		_scr_idx
		LDA		_obj_hps,X
		BEQ		loc_3AF94
		JSR		_players_animB_sub0129_sub05_A_A
		JSR		_players_animB_sub0129_sub05_A_B
		BCC		loc_3AF81
		PHA
		LDA		#$00
		STA		_obj_y_deltas,X
		PLA
		SEC
		RTS
loc_3AF81:
		LDA		_obj_y_lo_poss,X
		LDY		byte_B0
		JSR		_add_plus16
		AND		#$0F
		BNE		loc_3AF94
		LDY		#$A0
		JSR		_obj_to_tile_collision_test_down
		BCS		loc_3AF96
loc_3AF94:
		CLC
		RTS
loc_3AF96:
		PHA
		LDA		#$00
		STA		_obj_y_deltas,X
		LDA		byte_7F
		JSR		_switch
		.WORD	_players_animB_sub0129_sub05_A_sub0
		.WORD	_players_animB_sub0129_sub05_A_sub1
		.WORD	_players_animB_sub0129_sub05_A_sub2
		.WORD	_players_animB_sub0129_sub05_A_sub3
		.WORD	_players_animB_sub0129_sub05_A_sub4
		.WORD	_players_animB_sub0129_sub05_A_sub5

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_sub2:
		LDA		_tmp_ptr4
		CMP		#$F4
		BCC		loc_3AFB7
		CMP		#$F7
		BCC		loc_3AFD4
loc_3AFB7:
		LDA		_players_states,X
		CMP		#$03
		BEQ		loc_3AFC4
		LDA		_scr_idxCs,X
		AND		#$20
		BEQ		loc_3AFCA
loc_3AFC4:
		LDA		#$00
		STA		_players_vars10,X
		BEQ		loc_3AFD4
loc_3AFCA:
		LDA		_pads,X
		AND		#$C0
		BNE		loc_3AFD4
		LDA		_players_vars10,X
		STA		_players_x_deltas,X
loc_3AFD4:
		JMP		_players_animB_sub0129_sub05_A_sub0

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_sub1:
		LDA		#<[byte_3B049]
		STA		_tmp_ptr0
		LDA		#>[byte_3B049]
		STA		_tmp_ptr0+1
		LDA		#$08
		LDY		#$07
		BNE		_players_animB_sub0129_sub05_A_ex0

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_sub3:
		LDA		#<[byte_3B03D]
		STA		_tmp_ptr0
		LDA		#>[byte_3B03D]
		STA		_tmp_ptr0+1
		LDA		#$18
		LDY		#$0B
		BNE		_players_animB_sub0129_sub05_A_ex0

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_sub4:
		LDA		#<[byte_3B025]
		LDY		#>[byte_3B025]
		JMP		_players_animB_sub0129_sub05_A_ex1

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_sub5:
		LDA		#<[byte_3B031]
		LDY		#>[byte_3B031]

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_ex1:
		STA		_tmp_ptr0
		STY		_tmp_ptr0+1
		LDA		#$18
		LDY		#$0B

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_ex0:
		STA		_tmp_ptr2
		LDA		_tmp_ptr4
loc_3B00A:
		CMP		(_tmp_ptr0),Y
		BEQ		loc_3B013
		DEY
		BPL		loc_3B00A
		BMI		_players_animB_sub0129_sub05_A_sub0
loc_3B013:
		LDA		_tmp_ptr2
		STA		_players_x_deltas,X
		TYA
		LSR
		BCS		_players_animB_sub0129_sub05_A_sub0
		SEC
		LDA		#$00
		SBC		_tmp_ptr2
		STA		_players_x_deltas,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_sub0:
		PLA
		SEC
		RTS

byte_3B025:
		.BYTE	$A3,$A6,$A4,$A7,$A5,$A8,$EB,$E6,$EC,$EE,$ED,$EF
byte_3B031:
		.BYTE	$A6,$A3,$A7,$A4,$A8,$A5,$E6,$EB,$EE,$EC,$EF,$ED
byte_3B03D:
		.BYTE	$A3,$A9,$A4,$AA,$A5,$AB,$A6,$AC,$A7,$AD,$A8,$AE
byte_3B049:
		.BYTE	$B0,$B2,$B1,$CE,$FA,$F2,$FB,$F3

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub01_A:
		LDX		_scr_idx
		CLC
		LDA		_obj_y_deltas,X
		ADC		#$06
		CMP		#$6E
		BCC		loc_3B05F
		LDA		#$6E
loc_3B05F:
		STA		_obj_y_deltas,X
		JMP		_players_animB_sub0129_sub12_A_A

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub08_A:
		LDX		_scr_idx
		JSR		_players_animB_sub0129_sub12_A_B
		BCS		loc_3B077
		CLC
		LDA		_obj_y_deltas,X
		ADC		#$06
		STA		_obj_y_deltas,X
		BMI		locret_3B07C
loc_3B077:
		LDA		#$00
		STA		_obj_y_deltas,X
locret_3B07C:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub01_C:
		LDX		_scr_idx
		LDA		_players_vars07,X
		AND		#$20
		BEQ		locret_3B089
		LDA		#$11
		STA		_players_states,X
locret_3B089:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_A:
		LDA		#_apu_mus25_idx
		JSR		_apu_se_req
		LDA		#$09
		STA		_players_states,X
		JSR		_players_animB_sub0129_A_A
		LDA		#$00
		STA		_players_vars0D,X
		LDA		_debug_invulnerability_flag	; NOTE, original debug leftovers
		BNE		loc_3B0AA
		LDA		_obj_hps,X
		BEQ		loc_3B0AA
		DEC		_obj_hps,X
		BNE		loc_3B0AA
		DEC		_players_lives,X
loc_3B0AA:
		LDA		_players_vars07,X
		AND		#$7F
		STA		_players_vars07,X
		JMP		_native_obj_disable_from_idxCs_40_flag

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_A_A:
		LDA		#$40
		STA		_players_vars0F,X
		JSR		_scr_param_80_clear
		JSR		_scr_flips_10_set
		JMP		_scr_flips_04_set

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_E_sub2_A:
		LDY		_tmp_ptr4
		LDA		byte_E3
		BNE		locret_3B0E0
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$02
		BNE		loc_3B0D5
		LDA		_obj_heights,Y
		CMP		#$16
		RTS
loc_3B0D5:
		CMP		#$06
		BNE		locret_3B0E0
		LDA		_scr_idxCs,Y
		AND		#$30
		CMP		#$30
locret_3B0E0:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_E:
		JSR		_players_animB_sub0129_E_A
		STA		_players_vars0E,X
		STY		_tmp_ptr4
		JSR		_switch
		.WORD	nullsub7
		.WORD	_players_tile_pickup_handlers
		.WORD	_players_animB_sub0129_E_sub2
		.WORD	_players_animB_sub0129_E_sub2

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_E_sub2:
		JSR		_players_animB_sub0129_E_sub2_A
		BNE		loc_3B112
		LDA		_scr_idx
		PHA
		STY		_scr_idx
		LDA		_obj_x_deltas,Y
		PHA
		LDA		#$F0
		STA		_obj_x_deltas,Y
		JSR		_players_animB_sub0129_E_A
		LDY		_scr_idx
		PLA
		STA		_obj_x_deltas,Y
		PLA
		STA		_scr_idx
loc_3B112:
		JMP		loc_3B146

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_F:
		JSR		_players_animB_sub0129_F_A
		STA		_players_vars0E,X
		STY		_tmp_ptr4
		JSR		_switch
		.WORD	nullsub7
		.WORD	_players_tile_pickup_handlers
		.WORD	_players_animB_sub0129_F_sub2
		.WORD	_players_animB_sub0129_F_sub2

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_F_sub2:
		JSR		_players_animB_sub0129_E_sub2_A
		BNE		loc_3B146
		LDA		_scr_idx
		PHA
		STY		_scr_idx
		LDA		_obj_x_deltas,Y
		PHA
		LDA		#$10
		STA		_obj_x_deltas,Y
		JSR		_players_animB_sub0129_F_A
		LDY		_scr_idx
		PLA
		STA		_obj_x_deltas,Y
		PLA
		STA		_scr_idx
loc_3B146:
		JSR		_players_tile_pickup_test
		BEQ		nullsub7
		LDA		_scr_idxBs,Y
		BMI		nullsub7
		AND		#$20
		BNE		nullsub7
		CPY		#$02
		BCS		loc_3B169
		LDA		_obj_hps,Y
		BEQ		nullsub7
		LDA		_scr_idxBs,Y
		AND		#$40
		BNE		nullsub7
		LDA		#$06
		STA		_players_states,Y
loc_3B169:
		JSR		_players_pickup_obj_flags_update
		LDA		#_apu_mus52_idx
		JSR		_apu_se_req

; =============== S U B R O U T I N E =======================================
nullsub7:
		RTS

; =============== S U B R O U T I N E =======================================
_players_tile_pickup_handlers:
		JSR		_players_tile_pickup_test
		BEQ		nullsub8
		LDY		_tmp_ptr4+1						; we have already meta buf pos here
		LDA		_screen_meta_buf,Y				; read the tile we interact
		CMP		#$FC
		BCS		nullsub8						; all above FB not used here
		SEC
		SBC		#$F4
		BCC		nullsub8						; all less than F4 the same
		STA		_tmp_ptr4						; store F4-FB -> 0-7 range converted idx
		LDA		_room_flags						; special box prize room test
		AND		#$08
		BNE		_players_pickup_prize_replace	; always replace with prize only
		LDA		_tmp_ptr4
		JSR		_switch
		.WORD	_players_pickup_prize_replace	; empty box, default handler, if no objects, do nothing
		.WORD	_players_pickup_rr_replace		; box with rr, replace meta with RR meta F9
		.WORD	_players_pickup_prize_replace	; acorn
		.WORD	_players_pickup_prize_replace	; star
		.WORD	_players_pickup_prize_replace	; concrete
		.WORD	_sys_screen_cur_meta_update		; rr itself, only clears the meta
		.WORD	_players_pickup_prize_replace	; red ballA
		.WORD	_players_pickup_prize_replace	; red ballB
nullsub8:
		RTS

; =============== S U B R O U T I N E =======================================
_players_pickup_rr_replace:
		JSR		_sys_screen_rr_meta_draw
		JMP		_players_pickup_obj_load

; =============== S U B R O U T I N E =======================================
_players_pickup_prize_replace:
		JSR		_sys_screen_cur_meta_update
		LDA		_tmp_ptr4
		PHA
		ASL
		TAY
		LDA		_room_flags			; box bonus room flags, different set of prizes
		AND		#$08
		BEQ		loc_3B1BC
		TYA
		CLC
		ADC		#$10
		TAY
loc_3B1BC:
		LDA		_obj_prizes_list+1,Y
		BEQ		loc_3B1BD
		STA		_tmp_ptr0+1
		LDA		_obj_prizes_list,Y
		STA		_tmp_ptr0
		SEC
		LDA		byte_6
		SBC		byte_AC
		CLC
		ADC		#$08
		STA		_tmp_ptr4
		LDA		byte_8
		LDY		byte_B0
		JSR		_sub_minus16
		LDY		#$0F
		JSR		_add_plus16
		STA		_tmp_ptr2
		LDA		#$00
		STA		_tmp_ptr2+1
		STA		_tmp_ptr4+1
		STA		byte_6
		LDY		#_OBJ_SCR_GRAB
		JSR		_scr_load
loc_3B1BD:
		PLA
		STA		_tmp_ptr4

; !FALLTHROUGH!

; =============== S U B R O U T I N E =======================================
_players_pickup_obj_load:
		LDA		_tmp_ptr4
		ASL
		TAY
		LDA		_obj_pickups_list+1,Y
		BEQ		locret_3B21D
		STA		_tmp_ptr0+1
		LDA		_obj_pickups_list,Y
		STA		_tmp_ptr0
		LDA		#$00
		STA		_tmp_ptr2
		STA		_tmp_ptr2+1
		STA		_tmp_ptr4
		STA		_tmp_ptr4+1
		STA		byte_6
		LDY		#_OBJ_SCR_THROW
		JSR		_scr_load
		BCS		locret_3B21D
		TXA
		TAY
		JSR		_players_pickup_obj_flags_update
		LDA		#_apu_mus52_idx
		JSR		_apu_se_req
locret_3B21D:
		RTS

_obj_prizes_list:
		.WORD	0
		.WORD	0
		.WORD	_obj_scr_acorn_prize
		.WORD	_obj_scr1F_star_prize
		.WORD	0
		.WORD	0
		.WORD	0
		.WORD	0
_obj_prizes_listB:
		.WORD	_obj_scr_box_bonus_prize_continue
		.WORD	_obj_scr_box_bonus_prize_1up
		.WORD	_obj_scr_box_bonus_prize_30rrs
		.WORD	_obj_scr_box_bonus_prize_10rrs
		.WORD	0
		.WORD	0
		.WORD	0
		.WORD	0
_obj_pickups_list:
		.WORD	_obj_scr_box
		.WORD	_obj_scr_box
		.WORD	_obj_scr_box
		.WORD	_obj_scr_box
		.WORD	_obj_scr07_concrete_brick
		.WORD	0
		.WORD	_obj_scr_red_ball
		.WORD	_obj_scr_red_ball

; =============== S U B R O U T I N E =======================================
_players_tile_pickup_test:
		LDX		_scr_idx						; fetch cur player idx
		LDA		_pads+4,X						; test if B pressed
		AND		#$02
		BEQ		loc_3B272
		LDA		_scr_idxBs,X					; while colliding with tile object
		AND		#$40
		BNE		loc_3B272
		LDA		_players_vars0D,X				; extra checks...
		BNE		loc_3B272
		JSR		_get_box_bonus_special_pickup	; if ok, then pickup object
		BMI		loc_3B272
		LDA		_pads+4,X						; clear B press
		AND		#$FD
		STA		_pads+4,X
		LDA		_obj_heights,X					; also test if we not crouching
		CMP		#$10
		RTS
loc_3B272:
		LDA		#$00
		RTS

; =============== S U B R O U T I N E =======================================
_get_box_bonus_special_pickup:
		LDA		_room_flags
		AND		#$08
		BEQ		locret_3B27D
		LDA		_timer_frames_cnt
locret_3B27D:
		RTS

; =============== S U B R O U T I N E =======================================
_players_pickup_obj_flags_update:
		LDX		_scr_idx
		TYA
		ORA		#$40
		STA		_scr_idxBs,X
		LDA		_scr_idxBs,Y
		AND		#$F0
		STA		_tmp_ptr0
		TXA
		ORA		#$80
		ORA		_tmp_ptr0
		STA		_scr_idxBs,Y
		LDA		_obj_flips,Y
		ORA		#$0C
		STA		_obj_flips,Y
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub11_B:
		LDA		_scr_idxBs,X
		AND		#$40
		BNE		loc_3B2A6
		RTS
loc_3B2A6:
		JSR		_native_obj_disable_from_idxCs_40_flag
		LDA		#$12
		STA		_pads,X
		STA		_pads+4,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_C:
		LDA		_players_states,X
		CMP		#$05
		BNE		loc_3B2D0
		LDA		_scr_idxBs,X
		AND		#$40
		BEQ		loc_3B2D0
		LDA		_players_x_speeds,X
		BEQ		loc_3B2D0
		LDA		_pads,X
		AND		#$C0
		BEQ		loc_3B2D0
		INC		_players_vars0C,X
		BNE		loc_3B2D4
		LDA		#$1E
		STA		_players_vars0C,X
		BNE		loc_3B2D4
loc_3B2D0:
		LDA		#$00
		STA		_players_vars0C,X
loc_3B2D4:
		LDY		_scr_idxBs,X
		TYA
		AND		#$40
		BNE		loc_3B2DF
		JMP		loc_3B3A7
loc_3B2DF:
		TYA
		AND		#$0F
		TAY
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$06
		BEQ		loc_3B2FE
		LDA		_players_vars0C,X
		CMP		#$1E
		BCC		loc_3B2F9
		LDA		#_OBJ_DMG_STUN
		STA		_obj_damages,Y
		BNE		loc_3B2FE
loc_3B2F9:
		LDA		#_OBJ_DMG_KILL
		STA		_obj_damages,Y
loc_3B2FE:
		LDA		_players_states,X
		CMP		#$04
		BNE		loc_3B307
		JMP		loc_3B3A7
loc_3B307:
		LDA		_scr_idxCs,X
		AND		#$20
		BEQ		loc_3B311
		JMP		loc_3B3A7
loc_3B311:
		LDA		_pads+4,X
		AND		#$02
		BNE		loc_3B31A
		JMP		loc_3B3A7
loc_3B31A:
		LDA		_obj_hps,X
		BEQ		loc_3B346
		LDA		_obj_spr_libs,Y
		CMP		#$03
		BEQ		loc_3B346
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$06
		BEQ		loc_3B346
		STY		byte_96
		LDX		byte_96
		JSR		_players_animB_sub0129_C_A
		JSR		_players_animB_sub0129_C_B
		BCS		loc_3B3A7
		LDX		byte_96
		JSR		_players_animB_sub0129_sub16_E
		BCS		loc_3B3A7
		LDX		_scr_idx
		LDY		byte_96
loc_3B346:
		LDA		_scr_idxBs,X
		AND		#$BF
		STA		_scr_idxBs,X
		LDA		#$01
		STA		_players_vars0D,X
		LDA		_scr_idxBs,Y
		AND		#$7F
		STA		_scr_idxBs,Y
		LDA		_obj_flips,Y
		AND		#$E3
		STA		_obj_flips,Y
		LDA		_obj_heights,X
		BEQ		loc_3B39B
		LDA		#$17
		STA		_tmp_ptr0
		LDA		_obj_spr_libs,Y
		CMP		#$04
		BEQ		loc_3B38A
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$03
		BEQ		loc_3B386
		CMP		#$02
		BNE		loc_3B38A
		LDA		_obj_damages,Y
		CMP		#_OBJ_DMG_STUN
		BNE		loc_3B38A
loc_3B386:
		LDA		#$10
		STA		_tmp_ptr0
loc_3B38A:
		SEC
		LDA		_obj_y_lo_poss,X
		SBC		_tmp_ptr0
		STA		_obj_y_lo_poss,Y
		LDA		_obj_y_hi_poss,X
		SBC		#$00
		STA		_obj_y_hi_poss,Y
loc_3B39B:
		LDA		_obj_damages,Y
		CMP		#_OBJ_DMG_STUN
		BEQ		loc_3B3A7
		LDA		#_OBJ_DMG_NONE
		STA		_obj_damages,Y
loc_3B3A7:
		LDX		_scr_idx
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_D:
		LDX		_scr_idx
		LDA		_pads,X
		AND		#$80
		BEQ		loc_3B3BE
		LDA		_obj_flips,X
		ORA		#$40
		STA		_obj_flips,X
		LDA		#$20
		BNE		loc_3B3CE
loc_3B3BE:
		LDA		_pads,X
		AND		#$40
		BEQ		loc_3B3DC
		LDA		_obj_flips,X
		AND		#$BF
		STA		_obj_flips,X
		LDA		#$E0
loc_3B3CE:
		LDY		_players_states,X
		CPY		#$03
		BEQ		loc_3B3E9
		STA		_obj_x_deltas,X
		STA		_players_vars10,X
		JMP		locret_3B3EE
loc_3B3DC:
		LDA		_players_vars10,X
		BEQ		loc_3B3E9
		BMI		loc_3B3E7
		DEC		_players_vars10,X
		JMP		loc_3B3E9
loc_3B3E7:
		INC		_players_vars10,X
loc_3B3E9:
		LDA		#$00
		STA		_obj_x_deltas,X
locret_3B3EE:
		RTS

; WARNING, both players has the same spr idxes, to switch them only lib idx
; change is used, so this and some others subs uses the same common
; idxes, but since we macrosify them here, if you change one of the libs
; other will be broken. do not change indexes or do it syncronously!
;
byte_3B3EF:
		.BYTE	_spr_lib1_00_idx
		.BYTE	_spr_lib1_16_idx
		.BYTE	_spr_lib1_17_idx
		.BYTE	_spr_lib1_16_idx
		.BYTE	_spr_lib1_01_idx
		.BYTE	_spr_lib1_06_idx
		.BYTE	_spr_lib1_02_idx
		.BYTE	_spr_lib1_07_idx
		.BYTE	_spr_lib1_03_idx
		.BYTE	_spr_lib1_08_idx
		.BYTE	_spr_lib1_02_idx
		.BYTE	_spr_lib1_07_idx
		.BYTE	_spr_lib1_01_idx
		.BYTE	_spr_lib1_06_idx
		.BYTE	_spr_lib1_10_idx
		.BYTE	_spr_lib1_07_idx
		.BYTE	_spr_lib1_03_idx
		.BYTE	_spr_lib1_08_idx
		.BYTE	_spr_lib1_10_idx
		.BYTE	_spr_lib1_07_idx
		.BYTE	_spr_lib1_05_idx
		.BYTE	_spr_lib1_0B_idx
		.BYTE	_spr_lib1_05_idx
		.BYTE	_spr_lib1_0B_idx
		.BYTE	_spr_lib1_0D_idx
		.BYTE	_spr_lib1_0D_idx
		.BYTE	_spr_lib1_0C_idx
		.BYTE	_spr_lib1_0C_idx
		.BYTE	_spr_lib1_22_idx
		.BYTE	_spr_lib1_22_idx
		.BYTE	_spr_lib1_04_idx
		.BYTE	_spr_lib1_04_idx
byte_3B40F:
		.BYTE	_spr_lib1_09_idx
		.BYTE	_spr_lib1_0A_idx
		.BYTE	_spr_lib1_0A_idx
		.BYTE	_spr_lib1_0A_idx
		.BYTE	_spr_lib1_0E_idx
		.BYTE	_spr_lib1_0E_idx
		.BYTE	_spr_lib1_11_idx
		.BYTE	_spr_lib1_11_idx
		.BYTE	_spr_lib1_0F_idx
		.BYTE	_spr_lib1_0F_idx
		.BYTE	_spr_lib1_18_idx
		.BYTE	_spr_lib1_0B_idx
		.BYTE	_spr_lib1_0E_idx
		.BYTE	_spr_lib1_0B_idx
		.BYTE	_spr_lib1_19_idx
		.BYTE	_spr_lib1_0B_idx
		.BYTE	_spr_lib1_1A_idx
		.BYTE	_spr_lib1_0B_idx
		.BYTE	_spr_lib1_04_idx
		.BYTE	_spr_lib1_04_idx
		.BYTE	$00
		.BYTE	$8C
		.BYTE	$00
		.BYTE	$88
		.BYTE	$00
		.BYTE	$84
		.BYTE	$00
		.BYTE	$80
		.BYTE	$00
		.BYTE	$81
		.BYTE	$00
		.BYTE	$82
		.BYTE	$00
		.BYTE	$84
		.BYTE	$00
		.BYTE	$82
		.BYTE	$00
		.BYTE	$80
		.BYTE	$00
		.BYTE	$80
		.BYTE	$96
		.BYTE	$96

; =============== S U B R O U T I N E =======================================
_players_animC:
		LDA		_room_flags
		AND		#$03
		BEQ		loc_3B464
		LDY		#$00
		STY		_obj_global_x_shift
		STY		_obj_global_x_shift+1
		STY		_obj_global_y_shift
		STY		_obj_global_y_shift+1
		AND		#$02
		BEQ		locret_3B463
		LDA		_nmi_frames_counter
		AND		#$03
		BNE		locret_3B463
		DEC		_obj_global_y_shift
		DEC		_obj_global_y_shift+1
		LDA		byte_B1
		LDY		#$01
		JSR		_sub_minus16
		STA		byte_B1
		JMP		loc_3B4EF
locret_3B463:
		RTS
loc_3B464:
		JSR		_players_animC_A
		SEC
		LDA		byte_AD
		SBC		byte_AC
		STA		_obj_global_x_shift
		LDA		_lvl_start_scroll_hor+1
		SBC		_lvl_start_scroll_hor
		STA		_obj_global_x_shift+1
		SEC
		LDA		byte_B1
		SBC		byte_B0
		STA		_obj_global_y_shift
		LDA		_lvl_start_scroll_vert+1
		SBC		_lvl_start_scroll_vert
		STA		_obj_global_y_shift+1
		LDA		_obj_global_x_shift
		BEQ		loc_3B4B7
		BMI		loc_3B49E
		LDA		byte_AC
		EOR		#$FF
		AND		byte_AD
		AND		#$08
		BEQ		loc_3B4B4
		JSR		_room_scroll_pos_calc
		CLC
		LDA		_tmpA
		ADC		#$11
		STA		_tmpA
		JMP		loc_3B4AD
loc_3B49E:
		LDA		byte_AD
		EOR		#$FF
		AND		byte_AC
		AND		#$08
		BEQ		loc_3B4B4
		JSR		_room_scroll_pos_calc
		DEC		_tmpA
loc_3B4AD:
		LDA		#<[_room_drawA]
		LDY		#>[_room_drawA]
		JSR		_farcall
loc_3B4B4:
		JMP		loc_3B4CF
loc_3B4B7:
		LDA		_obj_global_y_shift
		BEQ		loc_3B4CF
		LDA		byte_B1
		EOR		#$FF
		AND		byte_B0
		AND		#$08
		BEQ		loc_3B4CF
		JSR		_room_scroll_pos_calc
		LDA		#<[_room_objects_managerB]
		LDY		#>[_room_objects_managerB]
		JSR		_farcall
loc_3B4CF:
		LDA		_room_drawB_sub_idx
		BNE		loc_3B4E8
		LDA		byte_92
		BEQ		loc_3B4E8
		DEC		byte_92
		LDA		byte_93
		STA		_tmpA
		LDA		byte_94
		STA		_tmpC
		LDA		#<[_room_objects_managerA]
		LDY		#>[_room_objects_managerA]
		JSR		_farcall
loc_3B4E8:
		LDA		#<[_room_drawB]
		LDY		#>[_room_drawB]
		JSR		_farcall
loc_3B4EF:
		LDA		byte_AD
		STA		_ppu_scroll_shadow_lo
		LDA		_lvl_start_scroll_hor+1
		STA		_ppu_scroll_nt_hor
		LDA		byte_B1
		STA		_ppu_scroll_shadow_hi
		LDA		_lvl_start_scroll_vert+1
		STA		_ppu_scroll_nt_vert
		LDX		#$01
		LDY		#$00
		JMP		_sys_scroll_sub00

; =============== S U B R O U T I N E =======================================
_players_animC_A:
		JSR		_get_cur_room_scroll_flag
		LDA		byte_B0
		BEQ		loc_3B510
		JMP		loc_3B585
loc_3B510:
		STY		byte_9D
		TYA
		AND		#$C0
		BEQ		loc_3B581
		CMP		#$40
		BEQ		loc_3B54D
		LDX		#$00
		LDY		#$01
		JSR		_players_animC_A_C
		BCS		loc_3B52B
		INX
		DEY
		JSR		_players_animC_A_C
		BCC		loc_3B581
loc_3B52B:
		SEC
		LDA		_obj_x_lo_poss,X
		SBC		_players_x_poss,X
		CLC
		ADC		byte_AD
		STA		byte_AD
		BCC		locret_3B54C
		INC		_lvl_start_scroll_hor+1
		LDA		_lvl_start_scroll_hor+1
		CMP		#$07
		BEQ		loc_3B548
		JSR		_get_cur_room_scroll_flag
		TYA
		AND		#$80
		BNE		locret_3B54C
loc_3B548:
		LDA		#$00
		STA		byte_AD
locret_3B54C:
		RTS
loc_3B54D:
		LDX		#$00
		LDY		#$01
		JSR		_players_animC_A_A
		BCS		loc_3B55D
		INX
		DEY
		JSR		_players_animC_A_A
		BCC		loc_3B581
loc_3B55D:
		SEC
		LDA		_players_x_poss,X
loc_3B560:
		SBC		_obj_x_lo_poss,X
		STA		_tmp_ptr0
		SEC
		LDA		byte_AD
		SBC		_tmp_ptr0
		STA		byte_AD
		BCS		locret_3B580
		DEC		_lvl_start_scroll_hor+1
		BMI		loc_3B57A
		JSR		_get_cur_room_scroll_flag
		TYA
		AND		#$40
		BNE		locret_3B580
loc_3B57A:
		INC		_lvl_start_scroll_hor+1
		LDA		#$00
		STA		byte_AD
locret_3B580:
		RTS
loc_3B581:
		LDA		byte_AC
		BNE		locret_3B5FB
loc_3B585:
		LDA		byte_9D
		AND		#$30
		BEQ		locret_3B5FB
		LDX		#$00
		LDY		#$01
		JSR		_players_animC_A_B
		BCS		loc_3B59C
		INX
		DEY
		JSR		_players_animC_A_B
		BCS		loc_3B59C
		RTS
loc_3B59C:
		SEC
		LDA		_players_y_poss,X
		SBC		_obj_y_lo_poss,X
		STA		_tmp_ptr0
		SEC
		LDA		byte_B1
		SBC		_tmp_ptr0
		STA		byte_B1
		BEQ		loc_3B5D6
		CMP		#$F0
		BCC		locret_3B5FA
		SEC
		SBC		#$10
		STA		byte_B1
		LDA		_lvl_start_scroll_vert+1
		BEQ		loc_3B5D2
		JSR		_get_cur_room_scroll_flag
		TYA
		AND		#$10
		BEQ		loc_3B5D2
		DEC		_lvl_start_scroll_vert+1
		SEC
		LDA		byte_B0
		SBC		#$10
		STA		byte_B0
		LDA		_lvl_start_scroll_vert
		SBC		#$00
		STA		_lvl_start_scroll_vert
		RTS
loc_3B5D2:
		LDA		#$00
		STA		byte_B1
loc_3B5D6:
		JSR		_get_cur_room_scroll_flag
		TYA
		AND		#$C0
		BEQ		locret_3B5FA
		INC		byte_92
		JSR		_room_scroll_pos_calc
		LDA		_tmpC
		STA		byte_94
		TYA
		AND		#$80
		BEQ		loc_3B5F4
		CLC
		LDA		_tmpA
		ADC		#$10
		STA		byte_93
		RTS
loc_3B5F4:
		DEC		_tmpA
		LDA		_tmpA
		STA		byte_93
locret_3B5FA:
		RTS
locret_3B5FB:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animC_A_C:
		LDA		_players_lives,X
		BEQ		loc_3B622
		LDA		_obj_x_lo_poss,X
		BPL		loc_3B622
		SEC
		SBC		_players_x_poss,X
		BEQ		loc_3B622
		BMI		loc_3B622
		CMP		#$05
		BCS		loc_3B622
		LDA		_players_lives,Y
		BEQ		loc_3B620
		LDA		byte_E3
		BNE		loc_3B620
		LDA		_obj_x_lo_poss,Y
		CMP		#$14
		BCC		loc_3B622
loc_3B620:
		SEC
		RTS
loc_3B622:
		CLC
		RTS

; =============== S U B R O U T I N E =======================================
_players_animC_A_A:
		LDA		_players_lives,X
		BEQ		loc_3B644
		LDA		_obj_x_lo_poss,X
		BMI		loc_3B644
		SEC
		SBC		_players_x_poss,X
		BPL		loc_3B644
		CMP		#$FC
		BCC		loc_3B644
		LDA		_players_lives,Y
		BEQ		loc_3B642
		LDA		_obj_x_lo_poss,Y
		CMP		#$EC
		BCS		loc_3B644
loc_3B642:
		SEC
		RTS
loc_3B644:
		CLC
		RTS

; =============== S U B R O U T I N E =======================================
_players_animC_A_B:
		LDA		_players_lives,X
		BEQ		loc_3B669
		LDA		_obj_flips,X
		AND		#$04
		BNE		loc_3B669
		LDA		_obj_y_lo_poss,X
		BMI		loc_3B669
		SEC
		SBC		_players_y_poss,X
		BPL		loc_3B669
		LDA		_players_lives,Y
		BEQ		loc_3B667
		LDA		_obj_y_lo_poss,Y
		CMP		#$AF
		BCS		loc_3B669
loc_3B667:
		SEC
		RTS
loc_3B669:
		CLC
		RTS

; =============== S U B R O U T I N E =======================================
_players_animA:
		LDX		byte_AB
		LDA		#$FF
		STA		_players_vars08,X
		LDA		_players_vars07,X
		AND		#$DF
		STA		_players_vars07,X
		LDA		_obj_hps,X
		BEQ		locret_3B684
		LDA		_obj_y_hi_poss,X
		ORA		_obj_x_hi_poss,X
		BEQ		loc_3B685
locret_3B684:
		RTS
loc_3B685:
		JSR		_players_animB_sub0129_C_A
		LDX		byte_AB
		LDY		#$05
loc_3B68C:
		LDA		byte_6,Y
		CMP		#$9E
		BEQ		loc_3B6AB
		CMP		#$9F
		BEQ		loc_3B6AB
		DEY
		BPL		loc_3B68C
		LDA		_players_vars07,X
		AND		#$40
		BNE		loc_3B6B3
		LDA		_obj_flips,X
		AND		#$DF
		STA		_obj_flips,X
		JMP		loc_3B6B3
loc_3B6AB:
		LDA		_obj_flips,X
		ORA		#$20
		STA		_obj_flips,X
loc_3B6B3:
		LDA		_obj_flips,X
		AND		#$08
		BEQ		loc_3B6C3
		JSR		_players_animB_sub0129_C_B
		BCS		loc_3B6C3
		LDA		#$00
		STA		_players_vars08,X
loc_3B6C3:
		LDA		_stage
		CMP		#$03
		BNE		loc_3B6DD
		LDY		#$05
loc_3B6CB:
		LDA		byte_6,Y
		CMP		#$9A
		BEQ		loc_3B6D7
		DEY
		BPL		loc_3B6CB
		BMI		loc_3B6DD
loc_3B6D7:
		LDA		_players_vars07,X
		ORA		#$20
		STA		_players_vars07,X
loc_3B6DD:
		LDA		_scr_idxBs,X
		BMI		locret_3B6F2
		LDY		#$05
loc_3B6E4:
		LDA		byte_6,Y
		CMP		#$F9
		BEQ		loc_3B717
		CMP		#$FC
		BCS		loc_3B6F3
		DEY
		BPL		loc_3B6E4
locret_3B6F2:
		RTS
loc_3B6F3:
		LDX		byte_AB
		LDA		_obj_hps,X
		BEQ		locret_3B716
		LDA		_players_vars0F,X
		BNE		locret_3B716
		LDY		#$20
		LDA		_obj_flips,X
		AND		#$40
		BEQ		loc_3B709
		LDY		#$E0
loc_3B709:
		TYA
		STA		_obj_x_deltas,X
		JSR		_players_animB_sub0129_sub06_B_A
		LDA		_players_vars07,X
		ORA		#$80
		STA		_players_vars07,X
locret_3B716:
		RTS
loc_3B717:
		LDX		byte_AB
		LDA		_players_rr_ptss,X
		CMP		#$63
		BCS		loc_3B721
		INC		_players_rr_ptss,X
loc_3B721:
		TYA
		ASL
		ASL
		ASL
		ASL
		AND		#$10
		STA		byte_6
		SEC
		LDA		_obj_x_lo_poss,X
		SBC		_obj_widths,X
		CLC
		ADC		byte_6
		CLC
		ADC		byte_AC
		STA		byte_6
		LDA		_obj_x_hi_poss,X
		ADC		_lvl_start_scroll_hor
		STA		byte_7
		TYA
		ASL
		ASL
		ASL
		AND		#$30
		TAY
		LDA		_obj_y_lo_poss,X
		JSR		_sub_minus16
		LDY		byte_B0
		JSR		_add_plus16
		STA		byte_8
		LDA		_obj_y_hi_poss,X
		ADC		_lvl_start_scroll_vert
		STA		byte_9
		JSR		_sys_screen_cur_meta_update
		LDA		#_apu_mus22_idx
		JSR		_apu_se_req
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_C_A:
		LDY		#$05
		LDA		#$00
loc_3B768:
		STA		byte_6,Y
		DEY
		BPL		loc_3B768
		LDA		_obj_y_lo_poss,X
		LDY		byte_9E
		JSR		_sub_minus16
		AND		#$F0
		STA		_tmp_ptr2
		LDA		_obj_y_lo_poss,X
		LDY		_obj_heights,X
		JSR		_sub_minus16
		LDY		byte_9E
		JSR		_sub_minus16
		LDY		#$10
		JSR		_sub_minus16
		AND		#$F0
		STA		_tmp_ptr2+1
		CLC
		LDA		_obj_x_lo_poss,X
		ADC		_obj_widths,X
		CLC
		ADC		byte_AC
		CLC
		ADC		#$0F
		AND		#$F0
		STA		_tmp_ptr0+1
		SEC
		LDA		_obj_x_lo_poss,X
		SBC		_obj_widths,X
		CLC
		ADC		byte_AC
		AND		#$F0
		STA		_tmp_ptr0
		LSR
		LSR
		LSR
		LSR
		ORA		_tmp_ptr2
		TAY
		LDA		#$00
		STA		_tmp_ptr4+1
loc_3B7BB:
		LDA		_tmp_ptr0
		PHA
		TYA
		PHA
		LDX		_tmp_ptr4+1
loc_3B7C2:
		LDA		_screen_meta_buf,Y
		STA		byte_6,X
		INX
		TYA
		AND		#$F0
		STA		_tmp_ptr4
		INY
		TYA
		AND		#$0F
		ORA		_tmp_ptr4
		TAY
		LDA		_tmp_ptr0
		CMP		_tmp_ptr0+1
		BEQ		loc_3B7E3
		CLC
		ADC		#$10
		STA		_tmp_ptr0
		CMP		_tmp_ptr0+1
		BNE		loc_3B7C2
loc_3B7E3:
		PLA
		SEC
		SBC		#$10
		TAY
		PLA
		STA		_tmp_ptr0
		INC		_tmp_ptr4+1
		INC		_tmp_ptr4+1
		LDA		_tmp_ptr4+1
		CMP		#$06
		BCS		locret_3B808
		STY		_tmp_ptr4
		LDA		_tmp_ptr2
		LDY		#$10
		JSR		_sub_minus16
		BCC		locret_3B808
		STA		_tmp_ptr2
		LDY		_tmp_ptr4
		CMP		_tmp_ptr2+1
		BNE		loc_3B7BB
locret_3B808:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_C_B:
		LDY		#$05
loc_3B80B:
		LDA		byte_6,Y
		CMP		#$F9
		BEQ		loc_3B816
		CMP		#$D0
		BCS		locret_3B81A
loc_3B816:
		DEY
		BPL		loc_3B80B
		CLC
locret_3B81A:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12_A_B:
		LDX		_scr_idx
		LDA		_obj_heights,X
		STA		byte_95
		JSR		_players_animB_sub0129_G
		BMI		loc_3B831
		SEC
		LDA		_obj_heights,X
		ADC		_obj_heights,Y
		STA		_obj_heights,X
loc_3B831:
		STY		byte_96
		JSR		_players_animB_sub0129_sub05_A_A
		LDA		byte_9D
		AND		#$10
		BEQ		loc_3B843
		LDA		_obj_y_lo_poss,X
		CMP		#$1E
		BCC		loc_3B853
loc_3B843:
		JSR		_obj_vert_animate
		LDA		_obj_y_hi_poss,X
		BNE		loc_3B853
		JSR		_obj_to_tile_collision_test_up
		BCC		loc_3B853
		JSR		_players_animB_sub0129_sub12_A_A_A
loc_3B853:
		JSR		_players_animB_sub0129_sub12_A_B_A
		LDA		byte_95
		STA		_obj_heights,X
		BCC		loc_3B872
		SEC
		LDA		_obj_y_lo_poss,X
		SBC		_obj_y_lo_poss,Y
		LDA		_obj_y_hi_poss,X
		SBC		_obj_y_hi_poss,Y
		BCC		loc_3B8C5
		JSR		_players_animB_sub0129_sub12_A_B_B
		JSR		_players_animB_sub0129_sub12_A_B_C
loc_3B872:
		LDY		byte_96
		BMI		loc_3B888
		CLC
		LDA		_obj_y_lo_poss,X
		SBC		_obj_heights,X
		STA		_obj_y_lo_poss,Y
		LDA		_obj_y_hi_poss,X
		SBC		#$00
		STA		_obj_y_hi_poss,Y
loc_3B888:
		JMP		_players_animB_sub0129_sub12_A_B_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12_A_A:
		LDX		_scr_idx
		CLC
		LDA		_obj_y_lo_poss,X
		ADC		byte_B0
		STA		_tmp_ptrE
		JSR		_players_animB_sub0129_sub05_A_A
		JSR		_obj_vert_animate
		BNE		_players_animB_sub0129_sub05_A_B
		LDA		_obj_y_deltas,X
		BEQ		loc_3B8AE
		CLC
		LDA		_obj_y_lo_poss,X
		ADC		byte_B0
		EOR		_tmp_ptrE
		AND		#$F0
		BEQ		_players_animB_sub0129_sub05_A_B
loc_3B8AE:
		LDY		#$A0
		JSR		_obj_to_tile_collision_test_down
		BCC		_players_animB_sub0129_sub05_A_B
		JSR		_players_animB_sub0129_sub12_A_A_A

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_B:
		INC		_obj_y_lo_poss,X
		JSR		_players_animB_sub0129_sub12_A_B_A
		PHP
		DEC		_obj_y_lo_poss,X
		PLP
		BCC		loc_3B8CF
loc_3B8C5:
		TYA
		STA		_scr_vars21,X
		JSR		_players_animB_sub0129_sub05_A_B_A
		JSR		_players_animB_sub0129_sub12_A_B_C
loc_3B8CF:
		JMP		_players_animB_sub0129_sub12_A_B_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_F_A:
		LDX		_scr_idx
		JSR		_players_animB_sub0129_sub05_A_A
		JSR		_obj_move_hor_animate
		LDA		_scr_params,X
		AND		#$0F
		CMP		#$02
		BNE		loc_3B8FD
		LDA		_players_vars07,X
		AND		#$40
		BNE		loc_3B8FD
		CLC
		LDA		_obj_x_lo_poss,X
		ADC		_obj_widths,X
		CMP		#$F4
		BCC		loc_3B8FD
		SEC
		LDA		#$F4
		SBC		_obj_widths,X
		STA		_obj_x_lo_poss,X
loc_3B8FD:
		JSR		_obj_to_tile_collision_test_right
		BCC		loc_3B905
		JSR		_players_animB_sub0129_sub12_A_A_A
loc_3B905:
		JSR		_players_animB_sub0129_sub12_A_B_A
		BCC		loc_3B910
		JSR		_players_animB_sub0129_F_A_A
		JSR		_players_animB_sub0129_F_A_B
loc_3B910:
		JMP		_players_animB_sub0129_sub12_A_B_D

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_E_A:
		LDX		_scr_idx
		JSR		_players_animB_sub0129_sub05_A_A
		JSR		_obj_move_hor_animate
		LDA		_scr_params,X
		AND		#$0F
		CMP		#$02
		BNE		loc_3B93E
		LDA		_players_vars07,X
		AND		#$40
		BNE		loc_3B93E
		SEC
		LDA		_obj_x_lo_poss,X
		SBC		_obj_widths,X
		CMP		#$0C
		BCS		loc_3B93E
		CLC
		LDA		#$0C
		ADC		_obj_widths,X
		STA		_obj_x_lo_poss,X
loc_3B93E:
		JSR		_obj_to_tile_collision_test_left
		BCC		loc_3B946
		JSR		_players_animB_sub0129_sub12_A_A_A
loc_3B946:
		JSR		_players_animB_sub0129_sub12_A_B_A
		BCC		_players_animB_sub0129_sub12_A_B_D
		JSR		_players_animB_sub0129_E_A_A
		JSR		_players_animB_sub0129_F_A_B

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12_A_B_D:
		CLC
		LDA		_tmp_ptrE+1
		BEQ		locret_3B957
		SEC
locret_3B957:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub05_A_A:
		LDA		#$00
		STA		_tmp_ptrE+1
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12_A_A_A:
		LDA		#$01
		STA		_tmp_ptrE+1
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_sub12_A_B_C:
		LDA		_scr_idx
		CMP		#$02
		BCS		_players_animB_sub0129_F_A_B
		LDA		_obj_y_lo_poss,X
		STA		_players_y_poss,X

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_F_A_B:
		LDA		_tmp_ptrE+1
		ORA		#$02
		STA		_tmp_ptrE+1
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_sub0129_G:
		STX		_tmp_ptr0
		LDY		#$0B
loc_3B978:
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$02
		BCC		loc_3B988
		LDA		_scr_vars21,Y
		CMP		_tmp_ptr0
		BEQ		locret_3B98B
loc_3B988:
		DEY
		BPL		loc_3B978
locret_3B98B:
		RTS

; =============== S U B R O U T I N E =======================================
_players_animB_A:
		LDY		#$0B
loc_3B98E:
		CPY		_scr_idx
		BEQ		loc_3B9B0
		LDA		_obj_hps,Y
		BEQ		loc_3B9B0
		LDA		_scr_params,Y
		AND		#$0F
		CMP		#$02
		BCC		loc_3B9B0
		CMP		#$09
		BEQ		loc_3B9B0
		LDA		_obj_flips,Y
		AND		#$04
		BNE		loc_3B9B0
		JSR		_obj_to_obj_collision_test
		BCS		locret_3B9B4
loc_3B9B0:
		DEY
		BPL		loc_3B98E
		CLC
locret_3B9B4:
		RTS

		SECTION_END		04, "PLAYERS AND MAIN ENGINE CODE"

		SECTION_START	05

_room_cfg00:
		.BYTE	$0F,$00				; _chrs
		.BYTE	$00					; _lvl_start_X
		.BYTE	$02					; _lvl_start_Y
		.BYTE	$18					; _players_X
		.BYTE	$C0					; _players_Y
		.BYTE	$00					; _flags
		.WORD	_lvl0_layouts		; _layout_ptr
		.WORD	_lvl0_scrolls		; _scrolls_ptr
		.WORD	_tileset00			; _tiles_ptr
		.WORD	_room_prize00		; _prizes_ptr
		.WORD	_room_objects00		; _enemies_ptr
		.BYTE	$1E					; _mmc1_ctrl
		.BYTE	$F0					; _split_pos
		.BYTE	_apu_mus03_idx		; _music_idx
		.BYTE	$00,$00				; field_14
		.WORD	_room_pal00			; _bg_pal_ptr
		.BYTE	$00					; field_18
_room_cfg01:
		.BYTE	$10,$01
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset00
		.WORD	_room_prize01
		.WORD	_room_objects01
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus03_idx
		.BYTE	$00,$00
		.WORD	_room_pal01
		.BYTE	$00
_room_cfg02:
		.BYTE	$10,$00
		.BYTE	$00
		.BYTE	$05
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset00
		.WORD	_room_prize02
		.WORD	_room_objects02
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus03_idx
		.BYTE	$00,$00
		.WORD	_room_pal01
		.BYTE	$00
_room_cfg03:
		.BYTE	$15,$0E
		.BYTE	$00
		.BYTE	$04
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$05
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset01
		.WORD	_room_prizes_dummy
		.WORD	_room_objects03
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus03_idx
		.BYTE	$00,$00
		.WORD	_room_pal03
		.BYTE	$8C
_room_cfg05:
		.BYTE	$0F,$0C
		.BYTE	$04
		.BYTE	$01
		.BYTE	$18
		.BYTE	$40
		.BYTE	$81
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset00
		.WORD	_room_prizes_dummy
		.WORD	_room_objects05
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$01,$01
		.WORD	_room_pal05
		.BYTE	$07
_room_cfg06:
		.BYTE	$11,$02
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl1_layouts
		.WORD	_lvl1_scrolls
		.WORD	_tileset01
		.WORD	_room_prize06
		.WORD	_room_objects06
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus04_idx
		.BYTE	$00,$02
		.WORD	_room_pal06
		.BYTE	$0E
_room_cfg07:
		.BYTE	$11,$02
		.BYTE	$00
		.BYTE	$04
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl1_layouts
		.WORD	_lvl1_scrolls
		.WORD	_tileset01
		.WORD	_room_prize07
		.WORD	_room_objects07
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus04_idx
		.BYTE	$00,$02
		.WORD	_room_pal06
		.BYTE	$0E
_room_cfg08:
		.BYTE	$11,$0A
		.BYTE	$07
		.BYTE	$02
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$81
		.WORD	_lvl1_layouts
		.WORD	_lvl1_scrolls
		.WORD	_tileset01
		.WORD	_room_prizes_dummy
		.WORD	_room_objects08
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$00
		.WORD	_room_pal06
		.BYTE	$15
_room_cfg0D:
		.BYTE	$12,$03
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl2_layouts
		.WORD	_lvl2_scrolls
		.WORD	_tileset02
		.WORD	_room_prize0D
		.WORD	_room_objects0D
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus05_idx
		.BYTE	$00,$00
		.WORD	_room_pal0D
		.BYTE	$4D
_room_cfg10:
		.BYTE	$12,$03
		.BYTE	$07
		.BYTE	$05
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl2_layouts
		.WORD	_lvl2_scrolls
		.WORD	_tileset02
		.WORD	_room_prize10
		.WORD	_room_objects10
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus05_idx
		.BYTE	$00,$00
		.WORD	_room_pal0D
		.BYTE	$1C
_room_cfg0E:
		.BYTE	$12,$0B
		.BYTE	$07
		.BYTE	$07
		.BYTE	$18
		.BYTE	$80
		.BYTE	$81
		.WORD	_lvl2_layouts
		.WORD	_lvl2_scrolls
		.WORD	_tileset02
		.WORD	_room_prizes_dummy
		.WORD	_room_objects0E
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$00
		.WORD	_room_pal0D
		.BYTE	$23
_room_cfg1F:
		.BYTE	$19,$06
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl3_layouts
		.WORD	_lvl3_scrolls
		.WORD	_tileset03
		.WORD	_room_prize1F
		.WORD	_room_objects1F
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus06_idx
		.BYTE	$03,$03
		.WORD	_room_pal1F
		.BYTE	$2A
_room_cfg20:
		.BYTE	$19,$0C
		.BYTE	$07
		.BYTE	$00
		.BYTE	$18
		.BYTE	$80
		.BYTE	$81
		.WORD	_lvl3_layouts
		.WORD	_lvl3_scrolls
		.WORD	_tileset03
		.WORD	_room_prizes_dummy
		.WORD	_room_objects20
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$03
		.WORD	_room_pal1F
		.BYTE	$31
_room_cfg14:
		.BYTE	$13,$05
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prize14
		.WORD	_room_objects14
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus07_idx
		.BYTE	$00,$04
		.WORD	_room_pal14
		.BYTE	$38
_room_cfg15:
		.BYTE	$13,$05
		.BYTE	$00
		.BYTE	$05
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prize15
		.WORD	_room_objects15
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus07_idx
		.BYTE	$00,$00
		.WORD	_room_pal15
		.BYTE	$38
_room_cfg17:
		.BYTE	$13,$05
		.BYTE	$06
		.BYTE	$04
		.BYTE	$70
		.BYTE	$C0
		.BYTE	$01
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prizes_dummy
		.WORD	_room_objects17
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus07_idx
		.BYTE	$00,$00
		.WORD	_room_pal15
		.BYTE	$38
_room_cfg1A:
		.BYTE	$13,$05
		.BYTE	$06
		.BYTE	$05
		.BYTE	$18
		.BYTE	$80
		.BYTE	$00
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prize1A
		.WORD	_room_objects1A
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus07_idx
		.BYTE	$00,$00
		.WORD	_room_pal15
		.BYTE	$38
_room_cfg16:
		.BYTE	$13,$0D
		.BYTE	$06
		.BYTE	$02
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$A1
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset05
		.WORD	_room_prizes_dummy
		.WORD	_room_objects16
		.BYTE	$1F
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$00
		.WORD	_room_pal16
		.BYTE	$3F
_room_cfg13:
		.BYTE	$15,$04
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$10
		.WORD	_lvl5_layouts
		.WORD	_lvl5_scrolls
		.WORD	_tileset02
		.WORD	_room_prize13
		.WORD	_room_objects13
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0B_idx
		.BYTE	$02,$09
		.WORD	_room_pal13
		.BYTE	$46
_room_cfg21:
		.BYTE	$14,$03
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl6_layouts
		.WORD	_lvl6_scrolls
		.WORD	_tileset03
		.WORD	_room_prize21
		.WORD	_room_objects12
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus08_idx
		.BYTE	$00,$00
		.WORD	_room_pal21
		.BYTE	$4D
_room_cfg22:
		.BYTE	$14,$07
		.BYTE	$00
		.BYTE	$00
		.BYTE	$18
		.BYTE	$AD
		.BYTE	$00
		.WORD	_lvl6_layouts
		.WORD	_lvl6_scrolls
		.WORD	_tileset03
		.WORD	_room_prize22
		.WORD	_room_objects22
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus08_idx
		.BYTE	$00,$00
		.WORD	_room_pal22
		.BYTE	$0E
_room_cfg23:
		.BYTE	$14,$07
		.BYTE	$00
		.BYTE	$01
		.BYTE	$18
		.BYTE	$8D
		.BYTE	$00
		.WORD	_lvl6_layouts
		.WORD	_lvl6_scrolls
		.WORD	_tileset03
		.WORD	_room_prize23
		.WORD	_room_objects23
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus08_idx
		.BYTE	$00,$00
		.WORD	_room_pal22
		.BYTE	$0E
_room_cfg24:
		.BYTE	$14,$07
		.BYTE	$00
		.BYTE	$02
		.BYTE	$18
		.BYTE	$8D
		.BYTE	$00
		.WORD	_lvl6_layouts
		.WORD	_lvl6_scrolls
		.WORD	_tileset03
		.WORD	_room_prize24
		.WORD	_room_objects24
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus08_idx
		.BYTE	$00,$00
		.WORD	_room_pal22
		.BYTE	$0E
_room_cfg25:
		.BYTE	$14,$09
		.BYTE	$00
		.BYTE	$05
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$81
		.WORD	_lvl6_layouts
		.WORD	_lvl6_scrolls
		.WORD	_tileset03
		.WORD	_room_prizes_dummy
		.WORD	_room_objects25
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$00
		.WORD	_room_pal21
		.BYTE	$54
_room_cfg26:
		.BYTE	$16,$00
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl7_layouts
		.WORD	_lvl7_scrolls
		.WORD	_tileset01
		.WORD	_room_prize26
		.WORD	_room_objects26
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus09_idx
		.BYTE	$00,$00
		.WORD	_room_pal26
		.BYTE	$00
_room_cfg27:
		.BYTE	$16,$08
		.BYTE	$00
		.BYTE	$04
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl7_layouts
		.WORD	_lvl7_scrolls
		.WORD	_tileset01
		.WORD	_room_prize27
		.WORD	_room_objects27
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus09_idx
		.BYTE	$00,$00
		.WORD	_room_pal26
		.BYTE	$00
_room_cfg29:
		.BYTE	$16,$08
		.BYTE	$00
		.BYTE	$03
		.BYTE	$18
		.BYTE	$A0
		.BYTE	$00
		.WORD	_lvl7_layouts
		.WORD	_lvl7_scrolls
		.WORD	_tileset01
		.WORD	_room_prize29
		.WORD	_room_objects28
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus09_idx
		.BYTE	$00,$00
		.WORD	_room_pal26
		.BYTE	$69
_room_cfg2A:
		.BYTE	$1A,$0D
		.BYTE	$06
		.BYTE	$01
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$A1
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset05
		.WORD	_room_prizes_dummy
		.WORD	_room_objects2A
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$00
		.WORD	_room_pal2A
		.BYTE	$62
_room_cfg2B:
		.BYTE	$17,$08
		.BYTE	$00
		.BYTE	$07
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prize2B
		.WORD	_room_objects2B
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0C_idx
		.BYTE	$04,$0C
		.WORD	_room_pal2B
		.BYTE	$00
_room_cfg2C:
		.BYTE	$17,$07
		.BYTE	$00
		.BYTE	$05
		.BYTE	$18
		.BYTE	$60
		.BYTE	$00
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prize2C
		.WORD	_room_objects2C
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0C_idx
		.BYTE	$04,$0C
		.WORD	_room_pal2B
		.BYTE	$5B
_room_cfg2E:
		.BYTE	$17,$08
		.BYTE	$00
		.BYTE	$04
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prize2E
		.WORD	_room_objects2E
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0C_idx
		.BYTE	$04,$0C
		.WORD	_room_pal2B
		.BYTE	$69
_room_cfg2F:
		.BYTE	$17,$0A
		.BYTE	$00
		.BYTE	$03
		.BYTE	$18
		.BYTE	$A0
		.BYTE	$00
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prize2F
		.WORD	_room_objects2F
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0C_idx
		.BYTE	$00,$0C
		.WORD	_room_pal2B
		.BYTE	$70
_room_cfg30:
		.BYTE	$17,$01
		.BYTE	$00
		.BYTE	$02
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$00
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prize30
		.WORD	_room_objects30
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus0C_idx
		.BYTE	$00,$0C
		.WORD	_room_pal2B
		.BYTE	$00
_room_cfg32:
		.BYTE	$17,$06
		.BYTE	$05
		.BYTE	$02
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$E5
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects33
		.BYTE	$1F
		.BYTE	$F0
		.BYTE	_apu_mus0D_idx
		.BYTE	$00,$00
		.WORD	_room_pal2B
		.BYTE	$77
_room_cfgB_00:
		.BYTE	$1D,$04
		.BYTE	$00
		.BYTE	$00
		.BYTE	$21
		.BYTE	$C0
		.BYTE	$09
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prizes_dummy
		.WORD	_room_objects0B
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus10_idx
		.BYTE	$00,$91
		.WORD	_room_palB
		.BYTE	$00
_room_cfg18:
		.BYTE	$1D,$04
		.BYTE	$00
		.BYTE	$01
		.BYTE	$28
		.BYTE	$D0
		.BYTE	$0D
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prizes_dummy
		.WORD	_room_objects18
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus1C_idx
		.BYTE	$00,$00
		.WORD	_room_pal18
		.BYTE	$7E
_room_cfg09:
		.BYTE	$1D,$04
		.BYTE	$00
		.BYTE	$02
		.BYTE	$38
		.BYTE	$C0
		.BYTE	$0D
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset05
		.WORD	_room_prizes_dummy
		.WORD	_room_objects09
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus1C_idx
		.BYTE	$00,$00
		.WORD	_room_pal09
		.BYTE	$00
_room_cfg0A:
		.BYTE	$1D,$04
		.BYTE	$00
		.BYTE	$03
		.BYTE	$28
		.BYTE	$80
		.BYTE	$0D
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset04
		.WORD	_room_prizes_dummy
		.WORD	_room_objects0A
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus1C_idx
		.BYTE	$00,$00
		.WORD	_room_pal0A
		.BYTE	$00
_cutscene_cfg12:
		.BYTE	$1B,$0E
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl1_layouts
		.WORD	_lvl1_scrolls
		.WORD	_tileset01
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$F0
		.BYTE	_apu_mus1A_idx
		.BYTE	$00,$00
		.WORD	_room_palA_12
		.BYTE	$8C
_cutscene_cfg00:
		.BYTE	$18,$19
		.BYTE	$06
		.BYTE	$07
		.BYTE	$00
		.BYTE	$00
		.BYTE	$21
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$B0
		.BYTE	_apu_mus0F_idx
		.BYTE	$00,$00
		.WORD	_room_palA_00
		.BYTE	$A1
_cutscene_cfg01:
		.BYTE	$18,$0E
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus02_idx
		.BYTE	$00,$00
		.WORD	_room_palA_01
		.BYTE	$8C
_cutscene_cfg02:
		.BYTE	$10,	$C
		.BYTE	$06
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset00
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus12_idx
		.BYTE	$00,$00
		.WORD	_room_pal01
		.BYTE	$07
_cutscene_cfg03:
		.BYTE	$10,$0E
		.BYTE	$06
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl0_layouts
		.WORD	_lvl0_scrolls
		.WORD	_tileset00
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus17_idx
		.BYTE	$00,$00
		.WORD	_room_pal01
		.BYTE	$8C
_cutscene_cfg04:
		.BYTE	$18,$0E
		.BYTE	$02
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus16_idx
		.BYTE	$00,$00
		.WORD	_room_palA_04
		.BYTE	$8C
_cutscene_cfg06:
		.BYTE	$19,$0E
		.BYTE	$04
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus15_idx
		.BYTE	$00,$00
		.WORD	_room_palA_06
		.BYTE	$8C
_cutscene_cfg05:
		.BYTE	$15,$0E
		.BYTE	$04
		.BYTE	$07
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl5_layouts
		.WORD	_lvl5_scrolls
		.WORD	_tileset02
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus0F_idx
		.BYTE	$00,$00
		.WORD	_room_palA_05
		.BYTE	$8C
_cutscene_cfg07:
		.BYTE	$15,$0E
		.BYTE	$04
		.BYTE	$07
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl5_layouts
		.WORD	_lvl5_scrolls
		.WORD	_tileset02
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus0F_idx
		.BYTE	$00,$00
		.WORD	_room_pal13
		.BYTE	$8C
_cutscene_cfg09:
		.BYTE	$18,$0E
		.BYTE	$06
		.BYTE	$00
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus14_idx
		.BYTE	$00,$00
		.WORD	_room_palA_09
		.BYTE	$8C
_cutscene_cfg0A:
		.BYTE	$13,$0E
		.BYTE	$04
		.BYTE	$02
		.BYTE	$18
		.BYTE	$C0
		.BYTE	$01
		.WORD	_lvl4_layouts
		.WORD	_lvl4_scrolls
		.WORD	_tileset05
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus11_idx
		.BYTE	$00,$00
		.WORD	_room_pal06
		.BYTE	$8C
_cutscene_cfg0B:
		.BYTE	$18,$0E
		.BYTE	$00
		.BYTE	$01
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus15_idx
		.BYTE	$00,$00
		.WORD	_room_palA_0B
		.BYTE	$8C
_cutscene_cfg0C:
		.BYTE	$18,$0E
		.BYTE	$02
		.BYTE	$01
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus0A_idx
		.BYTE	$00,$00
		.WORD	_room_palA_0C
		.BYTE	$8C
_cutscene_cfg0D:
		.BYTE	$18,$0E
		.BYTE	$06
		.BYTE	$01
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus0A_idx
		.BYTE	$00,$00
		.WORD	_room_palA_0D
		.BYTE	$8C
_cutscene_cfg0E:
		.BYTE	$19,$0E
		.BYTE	$06
		.BYTE	$03
		.BYTE	$00
		.BYTE	$00
		.BYTE	$21
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus12_idx
		.BYTE	$00,$00
		.WORD	_room_palA_0E
		.BYTE	$8C
_cutscene_cfg0F:
		.BYTE	$17,$0E
		.BYTE	$02
		.BYTE	$06
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus18_idx
		.BYTE	$00,$00
		.WORD	_room_pal2B
		.BYTE	$8C
_cutscene_cfg10:
		.BYTE	$17,$0E
		.BYTE	$02
		.BYTE	$06
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$FF
		.BYTE	_apu_mus18_idx
		.BYTE	$00,$00
		.WORD	_room_pal2B
		.BYTE	$8C
_cutscene_cfg11:
		.BYTE	$18,$0E
		.BYTE	$00
		.BYTE	$06
		.BYTE	$00
		.BYTE	$00
		.BYTE	$01
		.WORD	_lvl8_layouts
		.WORD	_lvl8_scrolls
		.WORD	_tileset06
		.WORD	_room_prizes_dummy
		.WORD	_room_objects_dummy
		.BYTE	$1E
		.BYTE	$4D
		.BYTE	_apu_mus19_idx
		.BYTE	$00,$00
		.WORD	_room_palA_11
		.BYTE	$8C

		SECTION_END		05, "ROOM CONFIGURATION DATA"

		BANK_END 2,$C000
