
_msg00:
		.BYTE	_N,_e,_w,_s,_c,_a,_s,_t,_e,_r,_ddt,_RET
		.BYTE	_S,_p,_e,_c,_i,_a,_l,__,_B,_u,_l,_l,_e,_t,_i,_n,_ddt,_WAIT
		.BYTE	_P,_o,_l,_i,_c,_e,__,_s,_a,_y,_RET
		.BYTE	_a,__,_d,_o,_w,_n,_t,_o,_w,_n,__,_r,_e,_s,_t,_a,_u,_r,_a,_n,_t,__,_h,_a,_s,_RET
		.BYTE	_r,_e,_c,_e,_i,_v,_e,_d,__,_a,__,_b,_o,_m,_b,__,_t,_h,_r,_e,_a,_t,_dot,_WAIT
		.BYTE	_U,_n,_l,_e,_s,_s,__,_t,_h,_e,__,_t,_i,_m,_e,__,_b,_o,_m,_b,__,_c,_a,_n,_RET
		.BYTE	_b,_e,__,_f,_o,_u,_n,_d,_col,__,_t,_h,_e,__,_r,_e,_s,_t,_a,_u,_r,_a,_n,_t,_RET
		.BYTE	_c,_o,_u,_l,_d,__,_b,_e,__,_d,_e,_s,_t,_r,_o,_y,_e,_d,_dot,_WAIT
		.BYTE	_STOP
_msg01:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_o,_a,_h,_exc,__,__,_A,__,_t,_i,_m,_e,__,_b,_o,_m,_b,_exc,_WAIT
		.BYTE	_STOP
_msg02:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_C,_h,_i,_p,_exc,__,__,_W,_h,_a,_t,__,_i,_s,__,_i,_t,_que,_WAIT
		.BYTE	_STOP
_msg03:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_T,_h,_e,_r,_e,_apo,_s,__,_a,__,_t,_i,_m,_e,__,_b,_o,_m,_b,_RET
		.BYTE	_i,_n,__,_a,__,_r,_e,_s,_t,_a,_u,_r,_a,_n,_t,__,_d,_o,_w,_n,_t,_o,_w,_n,_exc,_WAIT
		.BYTE	_W,_e,_apo,_v,_e,__,_g,_o,_t,__,_t,_o,__,_f,_i,_n,_d,__,_i,_t,_exc,_WAIT
		.BYTE	_STOP
_msg04:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_T,_h,_i,_s,__,_i,_s,__,_a,_n,__,_e,_m,_e,_r,_g,_e,_n,_c,_y,_exc,_WAIT
		.BYTE	_T,_h,_e,_r,_e,_apo,_s,__,_n,_o,__,_t,_i,_m,_e,__,_t,_o,__,_w,_a,_s,_t,_e,_exc,_RET
		.BYTE	_L,_e,_t,_apo,_s,__,_g,_o,_col,__,_M,_a,_t,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg05:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_e,_apo,_v,_e,__,_g,_o,_t,__,_a,__,_b,_o,_m,_b,__,_t,_o,__,_f,_i,_n,_d,_exc,_WAIT
		.BYTE	_STOP
_msg06:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_W,_e,_apo,_l,_l,__,_g,_o,__,_a,_h,_e,_a,_d,_RET
		.BYTE	_t,_o,__,_i,_n,_v,_e,_s,_t,_i,_g,_a,_t,_e,_exc,_WAIT
		.BYTE	_L,_o,_o,_k,__,_f,_o,_r,__,_u,_s,_RET
		.BYTE	_a,_n,_d,__,_w,_e,_apo,_l,_l,__,_g,_i,_v,_e,__,_y,_o,_u,_RET
		.BYTE	_a,_n,_y,__,_c,_l,_u,_e,_s,__,_w,_e,_apo,_v,_e,__,_f,_o,_u,_n,_d,_dot,_WAIT
		.BYTE	_STOP
_msg07:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_O,_r,__,_g,_i,_v,_e,__,_y,_o,_u,__,_s,_o,_m,_e,__,_h,_e,_l,_p,_dot,_dot,_dot,_WAIT
		.BYTE	_N,_e,_v,_e,_r,__,_w,_o,_u,_l,_d,__,_o,_apo,__,_m,_a,_d,_e,__,_i,_t,_RET
		.BYTE	_t,_h,_r,_o,_u,_g,_h,__,_t,_h,_e,__,_b,_a,_t,_t,_l,_e,__,_o,_f,__,_t,_h,_e,_RET
		.BYTE	_b,_r,_i,_e,__,_w,_i,_t,_h,_o,_u,_t,__,_a,__,_b,_i,_t,__,_o,_apo,__,_h,_e,_l,_p,_dot,_WAIT
		.BYTE	_A,_h,_h,_col,__,_t,_h,_o,_s,_e,__,_w,_e,_r,_e,__,_t,_h,_e,__,_d,_a,_y,_s,_dsh,_dsh,_WAIT
		.BYTE	_STOP
_msg08:
		.BYTE	_Z,_i,_p,_p,_e,_r,_ddt,_RET
		.BYTE	_dot,_dot,_dot,__,_dot,_dot,__,_dot,_dot,_dot,_dot,_dot,__,_dot,_dot,_WAIT
		.BYTE	_STOP
_msg09:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_R,_i,_g,_h,_t,_col,__,_Z,_i,_p,_p,_e,_r,_exc,_RET
		.BYTE	_T,_h,_e,_r,_e,_apo,_s,__,_n,_o,__,_t,_i,_m,_e,__,_t,_o,__,_l,_o,_s,_e,_exc,_WAIT
		.BYTE	_D,_a,_l,_e,_col,__,_y,_o,_u,__,_c,_o,_m,_e,__,_w,_i,_t,_h,__,_m,_e,_exc,_WAIT
		.BYTE	_STOP
_msg0A:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_N,_o,_w,_exc,_que,__,__,_B,_u,_t,__,_I,__,_w,_a,_s,__,_a,_b,_o,_u,_t,__,_RET
		.BYTE	_t,_o,__,_s,_t,_a,_r,_t,__,_m,_y,__,_a,_f,_t,_e,_r,_n,_o,_o,_n,__,_n,_a,_p,_exc,_WAIT
		.BYTE	_STOP
_msg0B:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_N,_o,__,_c,_a,_n,__,_d,_o,_col,__,_D,_a,_l,_e,_exc,_WAIT
		.BYTE	_STOP
_msg0C:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_O,_K,_col,__,_P,_a,_r,_t,_n,_e,_r,_exc,__,__,_L,_e,_t,_apo,_s,__,_g,_o,_exc,_WAIT
		.BYTE	_STOP
_msg0D:
		.BYTE	_RET
		.BYTE	_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,__,_a,_w,_a,_y,_exc,_WAIT
		.BYTE	_STOP
_msg0E:
		.BYTE	_N,_e,_w,_s,_c,_a,_s,_t,_e,_r,_ddt,_RET
		.BYTE	_A,_l,_s,_o,__,_i,_n,__,_t,_h,_e,__,_n,_e,_w,_s,_dot,_dot,_dot,_WAIT
		.BYTE	_F,_a,_t,_c,_a,_t,_col,_RET
		.BYTE	_t,_h,_e,__,_n,_o,_t,_o,_r,_i,_o,_u,_s,__,_f,_e,_l,_i,_n,_e,__,_f,_e,_l,_o,_n,_col,_WAIT
		.BYTE	_e,_s,_c,_a,_p,_e,_d,__,_f,_r,_o,_m,__,_p,_r,_i,_s,_o,_n,_RET
		.BYTE	_l,_a,_s,_t,__,_n,_i,_g,_h,_t,_dot,_dot,_dot,_WAIT
		.BYTE	_STOP
_msg0F:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_A,_l,_l,__,_r,_i,_g,_h,_t,_col,__,_s,_p,_i,_l,_l,__,_i,_t,_exc,_RET
		.BYTE	_W,_h,_o,__,_s,_e,_t,__,_t,_h,_e,__,_t,_i,_m,_e,__,_b,_o,_m,_b,_que,_WAIT
		.BYTE	_STOP
_msg10:
		.BYTE	_W,_a,_t,_e,_r,__,_R,_a,_b,_b,_i,_t,_ddt,_RET
		.BYTE	_I,__,_d,_i,_d,_exc,_WAIT
		.BYTE	_F,_a,_t,_c,_a,_t,__,_a,_s,_k,_e,_d,__,_m,_e,_RET
		.BYTE	_t,_o,__,_c,_r,_e,_a,_t,_e,__,_a,__,_d,_i,_v,_e,_r,_s,_i,_o,_n,_col,_RET
		.BYTE	_a,_n,_d,__,_i,_t,__,_w,_o,_r,_k,_e,_d,_exc,_WAIT
		.BYTE	_STOP
_msg11:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_N,_o,__,_w,_a,_y,_exc,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,_apo,_s,__,_i,_n,__,_p,_r,_i,_s,_o,_n,_exc,_WAIT
		.BYTE	_STOP
_msg12:
		.BYTE	_W,_a,_t,_e,_r,__,_R,_a,_b,_b,_i,_t,_ddt,_RET
		.BYTE	_N,_o,_t,__,_a,_n,_y,__,_m,_o,_r,_e,_exc,_RET
		.BYTE	_H,_e,__,_b,_r,_o,_k,_e,__,_o,_u,_t,__,_l,_a,_s,_t,__,_n,_i,_g,_h,_t,_exc,_WAIT
		.BYTE	_H,_e,_apo,_s,__,_p,_l,_a,_n,_n,_i,_n,_g,__,_t,_o,__,_s,_t,_e,_a,_l,_RET
		.BYTE	_t,_h,_e,__,_U,_r,_n,__,_o,_f,__,_t,_h,_e,__,_P,_h,_a,_r,_a,_o,_h,_exc,_RET
		.BYTE	_H,_e,__,_p,_r,_o,_b,_a,_b,_l,_y,__,_h,_a,_s,__,_i,_t,__,_a,_l,_r,_e,_a,_d,_y,_exc,_WAIT
		.BYTE	_Y,_o,_u,_apo,_r,_e,__,_t,_o,_o,__,_l,_a,_t,_e,_exc,_WAIT
		.BYTE	_STOP
_msg13:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_S,_o,__,_w,_h,_e,_r,_e,_apo,_s,__,_t,_h,_e,__,_b,_o,_m,_b,_exc,_que,_WAIT
		.BYTE	_STOP
_msg14:
		.BYTE	_W,_a,_t,_e,_r,__,_R,_a,_b,_b,_i,_t,_ddt,_RET
		.BYTE	_F,_i,_n,_d,__,_i,_t,__,_y,_o,_u,_r,_s,_e,_l,_f,_exc,_RET
		.BYTE	_H,_a,__,_h,_a,__,_h,_a,_exc,_WAIT
		.BYTE	_STOP
_msg15:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_G,_a,_d,_g,_e,_t,_col,_RET
		.BYTE	_h,_a,_v,_e,__,_y,_o,_u,__,_f,_o,_u,_n,_d,__,_t,_h,_e,__,_b,_o,_m,_b,_que,_WAIT
		.BYTE	_STOP
_msg16:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_H,_e,_r,_e,_apo,_s,__,_t,_h,_e,__,_b,_o,_m,_b,_exc,_WAIT
		.BYTE	_L,_o,_o,_k,_col,__,_i,_t,__,_h,_a,_s,_RET
		.BYTE	_b,_l,_u,_e,__,_a,_n,_d,__,_r,_e,_d,__,_w,_i,_r,_e,_s,__,_c,_o,_m,_i,_n,_g,_RET
		.BYTE	_o,_u,_t,__,_o,_f,__,_i,_t,_exc,_WAIT
		.BYTE	_W,_e,__,_h,_a,_v,_e,__,_t,_o,__,_c,_u,_t,_RET
		.BYTE	_o,_n,_e,__,_o,_f,__,_t,_h,_e,__,_w,_i,_r,_e,_s,_RET
		.BYTE	_t,_o,__,_d,_e,_f,_u,_s,_e,__,_i,_t,_exc,_WAIT
		.BYTE	_STOP
_msg17:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_B,_u,_t,_col,__,_u,_h,_col,__,_w,_h,_a,_t,__,_h,_a,_p,_p,_e,_n,_s,_RET
		.BYTE	_i,_f,__,_w,_e,__,_c,_u,_t,__,_t,_h,_e,__,_w,_r,_o,_n,_g,__,_o,_n,_e,_que,_WAIT
		.BYTE	_STOP
_msg18:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_W,_e,_apo,_r,_e,__,_d,_o,_o,_m,_e,_d,_exc,_WAIT
		.BYTE	_STOP
_msg19:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_U,_h,__,_o,_h,_dot,_WAIT
		.BYTE	_STOP
_msg1A:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_W,_h,_i,_c,_h,__,_o,_n,_e,__,_s,_h,_o,_u,_l,_d,__,_I,__,_c,_u,_t,_que,_WAIT
		.BYTE	_R,_e,_d,__,_o,_r,__,_b,_l,_u,_e,_que,__,__,_H,_u,_r,_r,_y,_exc,_RET
		.BYTE	_RET
		.BYTE	__,_rar,_R,_e,_d,__,__,_B,_l,_u,_e,_RET
		.BYTE	_STOP
_msg1B:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_A,_r,_e,__,_y,_o,_u,__,_s,_u,_r,_e,_que,_RET
		.BYTE	__,_rar,_Y,_e,_s,__,__,_N,_o,_RET
		.BYTE	_STOP
_msg1C:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_O,_K,_col,__,_h,_e,_r,_e,__,_g,_o,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg1D:
		.BYTE	_RET
		.BYTE	_B,_O,_O,_O,_O,_M,_exc,_exc,_exc,_WAIT
		.BYTE	_STOP
_msg1E:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_J,_u,_s,_t,__,_k,_i,_d,_d,_i,_n,_g,_dot,_RET
		.BYTE	_W,_e,__,_c,_u,_t,__,_t,_h,_e,__,_r,_i,_g,_h,_t,__,_o,_n,_e,_exc,_WAIT
		.BYTE	_STOP
_msg1F:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_I,__,_t,_h,_i,_n,_k,__,_I,_apo,_m,__,_g,_o,_n,_n,_a,__,_f,_a,_i,_n,_t,_exc,_WAIT
		.BYTE	_STOP
_msg20:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_H,_e,_y,_exc,__,__,_W,_h,_e,_r,_e,_apo,_s,__,_D,_a,_l,_e,_que,_WAIT
		.BYTE	_STOP
_msg21:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_O,_h,_col,__,_h,_e,__,_p,_a,_s,_s,_e,_d,__,_o,_u,_t,_dot,_WAIT
		.BYTE	_STOP
_msg22:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_W,_h,_e,_w,_exc,__,__,_I,__,_g,_u,_e,_s,_s,_RET
		.BYTE	_t,_h,_a,_t,__,_w,_a,_s,__,_t,_h,_e,__,_r,_i,_g,_h,_t,__,_o,_n,_e,_dot,_WAIT
		.BYTE	_STOP
_msg23:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_I,_t,__,_m,_u,_s,_t,__,_h,_a,_v,_e,__,_b,_e,_e,_n,_RET
		.BYTE	_a,__,_f,_a,_k,_e,__,_b,_o,_m,_b,_dot,_WAIT
		.BYTE	_STOP
_msg24:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_H,_u,_r,_r,_y,_exc,__,__,_F,_a,_t,_c,_a,_t,_apo,_s,__,_d,_o,_n,_e,__,_s,_t,_o,_l,_e,_n,_RET
		.BYTE	_t,_h,_e,__,_U,_r,_n,__,_o,_f,__,_t,_h,_e,__,_P,_h,_a,_r,_a,_o,_h,_exc,_WAIT
		.BYTE	_I,_t,_apo,_s,__,_o,_n,__,_a,__,_s,_h,_i,_p,_RET
		.BYTE	_a,_b,_o,_u,_t,__,_t,_o,__,_l,_e,_a,_v,_e,__,_p,_o,_r,_t,_exc,_WAIT
		.BYTE	_STOP
_msg25:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_N,_o,_w,__,_w,_h,_a,_t,__,_d,_o,_e,_s,__,_F,_a,_t,_c,_a,_t,__,_w,_a,_n,_t,_RET
		.BYTE	_w,_i,_t,_h,__,_t,_h,_e,__,_U,_r,_n,__,_o,_f,__,_t,_h,_e,__,_P,_h,_a,_r,_a,_o,_h,_que,_WAIT
		.BYTE	_STOP
_msg26:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_h,_o,__,_k,_n,_o,_w,_s,_que,_WAIT
		.BYTE	_W,_e,_apo,_v,_e,__,_j,_u,_s,_t,__,_g,_o,_t,__,_RET
		.BYTE	_t,_o,__,_g,_e,_t,__,_i,_t,__,_b,_a,_c,_k,_exc,_WAIT
		.BYTE	_STOP
_msg27:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_T,_h,_e,__,_U,_r,_n,__,_o,_f,__,_t,_h,_e,__,_P,_h,_a,_r,_a,_o,_h,_RET
		.BYTE	_i,_s,__,_m,_i,_s,_s,_i,_n,_g,_WAIT
		.BYTE	_a,_n,_d,__,_w,_e,__,_d,_o,_n,_apo,_t,__,_h,_a,_v,_e,__,_a,_n,_y,__,_l,_e,_a,_d,_s,_exc,_WAIT
		.BYTE	_STOP
_msg28:
		.BYTE	_Z,_i,_p,_p,_e,_r,_ddt,_RET
		.BYTE	_dot,_dot,_dot,_dot,_dot,__,_dot,_dot,_dot,__,_dot,_dot,_dot,_dot,_dot,__,_dot,_dot,_WAIT
		.BYTE	_STOP
_msg29:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_M,_o,_n,_t,_e,_y,_exc,_RET
		.BYTE	_W,_h,_a,_t,_apo,_s,__,_Z,_i,_p,_p,_e,_r,__,_s,_a,_y,_i,_n,_g,_exc,_que,_WAIT
		.BYTE	_STOP
_msg2A:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_W,_e,_l,_l,_col,__,_l,_u,_v,_col,__,_h,_e,__,_s,_a,_y,_s,_WAIT
		.BYTE	_t,_h,_a,_t,__,_F,_a,_t,_c,_a,_t,__,_a,_n,_d,__,_h,_i,_s,__,_h,_e,_n,_c,_h,_m,_e,_n,_RET
		.BYTE	_h,_e,_a,_d,_e,_d,__,_i,_n,_t,_o,__,_a,__,_w,_a,_r,_e,_h,_o,_u,_s,_e,_RET
		.BYTE	_b,_y,__,_t,_h,_e,__,_d,_o,_c,_k,_s,_exc,_WAIT
		.BYTE	_STOP
_msg2B:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_R,_e,_a,_l,_l,_y,_que,_RET
		.BYTE	_A,_r,_e,__,_y,_o,_u,__,_s,_u,_r,_e,_col,__,_Z,_i,_p,_p,_e,_r,_que,_WAIT
		.BYTE	_STOP
_msg2C:
		.BYTE	_Z,_i,_p,_p,_e,_r,_ddt,_RET
		.BYTE	_dot,_dot,_dot,_WAIT
		.BYTE	_STOP
_msg2D:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_A,_l,_l,__,_r,_i,_g,_h,_t,_exc,_RET
		.BYTE	_C,_apo,_m,_o,_n,_exc,__,__,_L,_e,_t,_apo,_s,__,_g,_o,_exc,_WAIT
		.BYTE	_F,_a,_t,_c,_a,_t,__,_b,_e,_t,_t,_e,_r,__,_w,_a,_t,_c,_h,__,_o,_u,_t,_exc,_WAIT
		.BYTE	_STOP
_msg2E:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_o,_a,_h,_exc,_RET
		.BYTE	_I,_t,_apo,_s,__,_p,_i,_t,_c,_h,__,_d,_a,_r,_k,__,_i,_n,__,_h,_e,_r,_e,_exc,_WAIT
		.BYTE	_I,__,_c,_a,_n,_apo,_t,__,_s,_e,_e,_RET
		.BYTE	_a,__,_b,_l,_o,_o,_m,_i,_n,_apo,__,_t,_h,_i,_n,_g,_exc,_WAIT
		.BYTE	_STOP
_msg2F:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_H,_e,_y,_exc,__,__,_T,_h,_e,__,_d,_o,_o,_r,__,_s,_h,_u,_t,__,_i,_t,_s,_e,_l,_f,_exc,_WAIT
		.BYTE	_STOP
_msg30:
		.BYTE	_A,_h,_h,_h,__,_h,_a,__,_h,_a,__,_h,_a,_dot,_RET
		.BYTE	_W,_e,_l,_c,_o,_m,_e,_col,_RET
		.BYTE	_m,_y,__,_l,_i,_t,_t,_l,_e,__,_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,_exc,_WAIT
		.BYTE	_I,_apo,_v,_e,__,_w,_a,_i,_t,_e,_d,_RET
		.BYTE	_a,__,_l,_o,_n,_g,__,_t,_i,_m,_e,__,_f,_o,_r,__,_t,_h,_i,_s,_exc,_WAIT
		.BYTE	_STOP
_msg31:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,_que,_que,_WAIT
		.BYTE	_STOP
_msg32:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_T,_h,_e,__,_o,_n,_e,__,_a,_n,_d,__,_o,_n,_l,_y,_exc,_WAIT
		.BYTE	_STOP
_msg33:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,_exc,__,__,_Y,_o,_u,__,_s,_t,_o,_l,_e,_RET
		.BYTE	_t,_h,_e,__,_U,_r,_n,__,_o,_f,__,_t,_h,_e,__,_P,_h,_a,_r,_a,_o,_h,_exc,_WAIT
		.BYTE	_RET
		.BYTE	_STOP
_msg34:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_T,_h,_a,_t,_apo,_s,__,_r,_i,_g,_h,_t,_exc,_WAIT
		.BYTE	_A,_n,_d,__,_i,_t,_apo,_s,__,_f,_u,_l,_l,__,_o,_f,__,_RET
		.BYTE	_a,_n,_c,_i,_e,_n,_t,__,_e,_v,_i,_l,__,_s,_p,_i,_r,_i,_t,_s,_exc,_WAIT
		.BYTE	_W,_h,_e,_n,__,_I,__,_r,_e,_l,_e,_a,_s,_e,__,_t,_h,_e,_m,_col,_RET
		.BYTE	_I,_apo,_l,_l,__,_r,_u,_l,_e,__,_t,_h,_e,__,_w,_o,_r,_l,_d,_exc,_WAIT
		.BYTE	_STOP
_msg35:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_Y,_o,_u,_apo,_l,_l,__,_n,_e,_v,_e,_r,__,_g,_e,_t,__,_a,_w,_a,_y,_RET
		.BYTE	_w,_i,_t,_h,__,_t,_h,_i,_s,_col,__,_F,_a,_t,_c,_a,_t,_exc,_WAIT
		.BYTE	_STOP
_msg36:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_A,_n,_d,__,_w,_h,_a,_t,__,_w,_i,_l,_l,__,_y,_o,_u,__,_d,_o,_RET
		.BYTE	_t,_o,__,_s,_t,_o,_p,__,_m,_e,_exc,_que,_WAIT
		.BYTE	_Y,_o,_u,_apo,_r,_e,__,_i,_n,__,_a,_RET
		.BYTE	_g,_i,_a,_n,_t,__,_r,_e,_f,_r,_i,_g,_e,_r,_a,_t,_o,_r,_exc,_WAIT
		.BYTE	_Y,_o,_u,_apo,_l,_l,__,_b,_e,__,_f,_r,_o,_z,_e,_n,__,_s,_o,_l,_i,_d,_RET
		.BYTE	_i,_n,__,_t,_h,_r,_e,_e,__,_m,_i,_n,_u,_t,_e,_s,_exc,_RET
		.BYTE	_H,_a,__,_h,_a,__,_h,_a,_exc,_WAIT
		.BYTE	_STOP
_msg37:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_A,_w,_col,__,_n,_u,_t,_s,_exc,_RET
		.BYTE	_W,_h,_a,_t,__,_a,_r,_e,__,_w,_e,__,_g,_o,_n,_n,_a,__,_d,_o,__,_n,_o,_w,_que,_WAIT
		.BYTE	_STOP
_msg38:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_I,__,_t,_h,_i,_n,_k,__,_I,__,_s,_e,_e,__,_a,_n,__,_o,_p,_e,_n,_i,_n,_g,_exc,_RET
		.BYTE	_O,_v,_e,_r,__,_t,_h,_e,_r,_e,_exc,_WAIT
		.BYTE	_M,_a,_y,_b,_e,__,_RET
		.BYTE	_w,_e,__,_c,_a,_n,__,_e,_s,_c,_a,_p,_e,__,_t,_h,_r,_o,_u,_g,_h,__,_i,_t,_exc,_RET
		.BYTE	_H,_u,_r,_r,_y,_exc,_WAIT
		.BYTE	_STOP
_msg39:
		.BYTE	_Y,_o,_u,_apo,_l,_l,__,_b,_e,__,_f,_r,_o,_z,_e,_n,__,_s,_o,_l,_i,_d,_RET
		.BYTE	_i,_n,__,_t,_h,_r,_e,_e,__,_m,_i,_n,_u,_t,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg3A:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_C,_r,_i,_k,_e,_y,_exc,_RET
		.BYTE	_T,_h,_e,_r,_e,_apo,_s,__,_g,_h,_o,_s,_t,_s,__,_e,_v,_e,_r,_y,_w,_h,_e,_r,_e,_exc,_WAIT
		.BYTE	_F,_a,_t,_c,_a,_t,__,_m,_u,_s,_t,_apo,_v,_e,_RET
		.BYTE	_o,_p,_e,_n,_e,_d,__,_t,_h,_e,__,_u,_r,_n,_exc,_WAIT
		.BYTE	_STOP
_msg3B:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_L,_o,_o,_k,_exc,__,__,_T,_h,_e,_y,_apo,_r,_e,__,_c,_o,_m,_i,_n,_g,_RET
		.BYTE	_f,_r,_o,_m,__,_t,_h,_e,__,_w,_a,_r,_e,_h,_o,_u,_s,_e,_exc,_WAIT
		.BYTE	_STOP
_msg3C:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_Y,_o,_u,__,_m,_dsh,_m,_dsh,_m,_e,_a,_n,__,_t,_h,_e,__,_w,_dsh,_w,_a,_r,_e,_h,_o,_u,_s,_e,_RET
		.BYTE	_i,_s,__,_h,_dsh,_h,_a,_u,_n,_t,_e,_d,_dot,_dot,_dot,_que,_WAIT
		.BYTE	_STOP
_msg3D:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_P,_u,_l,_l,__,_y,_o,_u,_r,_s,_e,_l,_f,__,_t,_o,_g,_e,_t,_h,_e,_r,_col,_RET
		.BYTE	_D,_a,_l,_e,_exc,__,__,_Y,_o,_u,_apo,_r,_e,__,_a,__,_R,_a,_n,_g,_e,_r,_exc,_RET
		.BYTE	_RET
		.BYTE	_STOP
_msg3E:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_Y,_e,_a,_h,_col,__,_a,_n,_d,__,_t,_h,_dsh,_t,_h,_dsh,_t,_h,_o,_s,_e,_RET
		.BYTE	_a,_r,_e,__,_g,_h,_dsh,_g,_h,_dsh,_g,_h,_o,_s,_t,_s,_exc,_WAIT
		.BYTE	_STOP
_msg3F:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_e,__,_d,_i,_d,__,_i,_t,_exc,__,__,_A,_l,_l,__,_t,_h,_e,__,_g,_h,_o,_s,_t,_s,_RET
		.BYTE	_s,_h,_o,_u,_l,_d,__,_d,_i,_s,_a,_p,_p,_e,_a,_r,__,_s,_o,_o,_n,_exc,_WAIT
		.BYTE	_STOP
_msg40:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_D,_o,_n,_apo,_t,__,_y,_o,_u,__,_R,_e,_s,_c,_u,_e,__,_R,_o,_d,_e,_n,_t,_s,_RET
		.BYTE	_e,_v,_e,_r,__,_l,_e,_a,_r,_n,_que,_WAIT
		.BYTE	_STOP
_msg41:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_U,_h,__,_o,_h,_dot,__,__,_I,_t,_apo,_s,__,_F,_a,_t,_c,_a,_t,_exc,_WAIT
		.BYTE	_STOP
_msg42:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_C,_o,_m,_e,__,_o,_u,_t,__,_h,_e,_r,_e,__,_a,_n,_d,__,_f,_a,_c,_e,__,_u,_s,_exc,_RET
		.BYTE	_A,_r,_e,__,_y,_o,_u,__,_a,__,_c,_a,_t,__,_o,_r,__,_a,__,_m,_o,_u,_s,_e,_exc,_que,_WAIT
		.BYTE	_STOP
_msg43:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_N,_o,_t,__,_s,_o,__,_f,_a,_s,_t,_col,__,_R,_a,_n,_g,_e,_r,_s,_exc,_WAIT
		.BYTE	_I,_f,__,_y,_o,_u,__,_d,_a,_r,_e,__,_t,_o,__,_f,_a,_c,_e,__,_m,_e,_col,_RET
		.BYTE	_c,_o,_m,_e,__,_t,_o,__,_t,_h,_e,__,_a,_m,_u,_s,_e,_m,_e,_n,_t,__,_p,_a,_r,_k,_exc,_RET
		.BYTE	_I,_apo,_l,_l,__,_b,_e,__,_w,_a,_i,_t,_i,_n,_g,_exc,_WAIT
		.BYTE	_STOP
_msg44:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_O,_o,_h,__,_t,_h,_a,_t,__,_F,_a,_t,_c,_a,_t,_exc,_RET
		.BYTE	_W,_e,__,_g,_o,_t,_t,_a,__,_s,_t,_o,_p,__,_h,_i,_m,_exc,_WAIT
		.BYTE	_STOP
_msg45:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_a,_i,_t,_col,__,_D,_a,_l,_e,_exc,_RET
		.BYTE	_I,_t,__,_s,_m,_e,_l,_l,_s,__,_l,_i,_k,_e,__,_a,__,_t,_r,_a,_p,__,_t,_o,__,_m,_e,_exc,_WAIT
		.BYTE	_STOP
_msg46:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_Y,_o,_u,_apo,_r,_e,__,_d,_o,_o,_m,_e,_d,_col,_RET
		.BYTE	_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,_exc,_WAIT
		.BYTE	_I,__,_c,_o,_n,_t,_r,_o,_l,_RET
		.BYTE	_t,_h,_i,_s,__,_e,_n,_t,_i,_r,_e,__,_a,_m,_u,_s,_e,_m,_e,_n,_t,__,_p,_a,_r,_k,_exc,_RET
		.BYTE	_Y,_o,_u,_apo,_l,_l,__,_n,_e,_v,_e,_r,__,_c,_a,_p,_t,_u,_r,_e,__,_m,_e,_exc,_WAIT
		.BYTE	_STOP
_msg47:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_O,_h,__,_y,_e,_a,_h,_que,_RET
		.BYTE	_D,_o,_n,_apo,_t,__,_b,_e,_t,__,_o,_n,__,_i,_t,_col,__,_F,_a,_t,_c,_a,_t,_exc,_WAIT
		.BYTE	_STOP
_msg48:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_H,_a,_exc,__,__,_Y,_o,_u,__,_n,_e,_e,_d,__,_t,_h,_r,_e,_e,__,_k,_e,_y,_s,_RET
		.BYTE	_t,_o,__,_e,_n,_t,_e,_r,__,_m,_y,__,_c,_o,_n,_t,_r,_o,_l,__,_r,_o,_o,_m,_col,_WAIT
		.BYTE	_a,_n,_d,__,_t,_h,_e,_y,_apo,_r,_e,__,_a,_l,_l,__,_h,_i,_d,_d,_e,_n,_RET
		.BYTE	_i,_n,__,_d,_i,_f,_f,_e,_r,_e,_n,_t,__,_p,_a,_r,_t,_s,_RET
		.BYTE	_o,_f,__,_t,_h,_e,__,_p,_a,_r,_k,_exc,__,__,_H,_a,_v,_e,__,_f,_u,_n,_exc,_WAIT
		.BYTE	_STOP
_msg49:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_W,_e,_apo,_v,_e,__,_g,_o,_t,__,_t,_o,__,_g,_e,_t,__,_t,_h,_e,__,_k,_e,_y,_s,_exc,_WAIT
		.BYTE	_STOP
_msg4A:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_R,_i,_g,_h,_t,_o,_col,__,_D,_a,_l,_e,_exc,_RET
		.BYTE	_W,_h,_e,_r,_e,__,_s,_h,_o,_u,_l,_d,__,_w,_e,__,_g,_o,__,_f,_i,_r,_s,_t,_que,_WAIT
		.BYTE	__,_rar,_C,_l,_o,_c,_k,__,_T,_o,_w,_e,_r,_RET
		.BYTE	__,__,_W,_e,_s,_t,_e,_r,_n,__,_W,_o,_r,_l,_d,_RET
		.BYTE	__,__,_F,_u,_t,_u,_r,_e,__,_W,_o,_r,_l,_d,_RET
		.BYTE	_STOP
_msg4B:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_A,_r,_e,__,_y,_o,_u,__,_s,_u,_r,_e,_que,_RET
		.BYTE	__,_rar,_Y,_e,_s,__,__,_N,_o,_RET
		.BYTE	_STOP
_msg4C:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_L,_e,_t,_apo,_s,__,_g,_o,__,_t,_o,__,_t,_h,_e,_RET
		.BYTE	_dict80,__,_f,_i,_r,_s,_t,_exc,_WAIT
		.BYTE	_STOP
_msg4D:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_W,_e,__,_f,_o,_u,_n,_d,__,_t,_h,_e,__,_k,_e,_y,_exc,_RET
		.BYTE	_W,_h,_e,_r,_e,__,_t,_o,__,_n,_e,_x,_t,_exc,_que,_WAIT
		.BYTE	__,_rar,_dict80,_RET
		.BYTE	__,__,_dict81,_RET
		.BYTE	_STOP
_msg4E:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_dict80,_exc,__,_H,_u,_r,_r,_y,_exc,_WAIT
		.BYTE	_STOP
_msg4F:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_W,_e,_apo,_v,_e,__,_g,_o,_t,__,_t,_w,_o,__,_k,_e,_y,_s,_exc,_WAIT
		.BYTE	_T,_h,_a,_t,__,_m,_e,_a,_n,_s,__,_t,_h,_e,__,_l,_a,_s,_t,__,_o,_n,_e,_RET
		.BYTE	_m,_u,_s,_t,__,_b,_e,__,_i,_n,_RET
		.BYTE	_dict80,_exc,_WAIT
		.BYTE	_STOP
_msg50:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_R,_i,_g,_h,_t,_exc,__,__,_L,_e,_t,_apo,_s,__,_g,_o,_exc,_WAIT
		.BYTE	_STOP
_msg51:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_S,_h,_h,_h,_exc,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,__,_i,_s,__,_r,_i,_g,_h,_t,__,_i,_n,_s,_i,_d,_e,_exc,_WAIT
		.BYTE	_STOP
_msg52:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_L,_e,_t,_apo,_s,__,_u,_s,_e,__,_t,_h,_e,__,_k,_e,_y,_s,_exc,_WAIT
		.BYTE	_STOP
_msg53:
		.BYTE	_Z,_i,_p,_p,_e,_r,_ddt,_RET
		.BYTE	_dot,_dot,__,_dot,_dot,_dot,__,_dot,_dot,_WAIT
		.BYTE	_STOP
_msg54:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_I,_t,_apo,_s,__,_u,_n,_l,_o,_c,_k,_e,_d,_exc,_RET
		.BYTE	_O,_p,_e,_n,__,_t,_h,_e,__,_d,_o,_o,_r,_exc,_WAIT
		.BYTE	_STOP
_msg55:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_e,_apo,_v,_e,__,_g,_o,_t,__,_y,_o,_u,__,_n,_o,_w,_col,__,_F,_a,_t,_c,_a,_t,_exc,_RET
		.BYTE	_T,_h,_e,__,_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,__,_a,_r,_e,__,_h,_e,_r,_e,_exc,_WAIT
		.BYTE	_STOP
_msg56:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_H,_e,_y,_exc,__,__,_H,_e,_apo,_s,__,_g,_o,_n,_e,_exc,_RET
		.BYTE	_W,_h,_e,_r,_e,_apo,_d,__,_h,_e,__,_g,_o,_exc,_que,_WAIT
		.BYTE	_STOP
_msg57:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_L,_o,_o,_k,_col,__,_e,_v,_e,_r,_y,_o,_n,_e,_exc,_RET
		.BYTE	_A,__,_s,_e,_c,_r,_e,_t,__,_p,_a,_s,_s,_a,_g,_e,_exc,__,__,_L,_e,_t,_apo,_s,__,_g,_o,_exc,_WAIT
		.BYTE	_STOP
_msg58:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_B,_e,__,_c,_a,_r,_e,_f,_u,_l,_exc,__,__,_T,_h,_i,_s,__,_c,_o,_u,_l,_d,__,_RET
		.BYTE	_b,_e,__,_o,_u,_r,__,_l,_a,_s,_t,__,_s,_t,_a,_n,_d,_exc,_WAIT
		.BYTE	_STOP
_msg59:
		.BYTE	_RET
		.BYTE	_L,_e,_t,_apo,_s,__,_g,_o,__,_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,_exc,_WAIT
		.BYTE	_STOP
_msg5A:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_W,_e,_l,_c,_o,_m,_e,_col,__,_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,_exc,_RET
		.BYTE	_I,_apo,_v,_e,__,_b,_e,_e,_n,__,_w,_a,_i,_t,_i,_n,_g,__,_f,_o,_r,__,_y,_o,_u,_exc,_WAIT
		.BYTE	_STOP
_msg5B:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_Y,_o,_u,_apo,_l,_l,__,_n,_e,_v,_e,_r,__,_g,_e,_t,__,_a,_w,_a,_y,_col,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,_exc,_WAIT
		.BYTE	_STOP
_msg5C:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_S,_u,_r,_r,_e,_n,_d,_e,_r,_exc,_WAIT
		.BYTE	_STOP
_msg5D:
		.BYTE	_F,_a,_t,_c,_a,_t,_ddt,_RET
		.BYTE	_Y,_o,_u,_apo,_l,_l,__,_n,_e,_v,_e,_r,__,_d,_e,_f,_e,_a,_t,__,_m,_e,_col,_RET
		.BYTE	_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,_exc,_WAIT
		.BYTE	_I,__,_h,_a,_v,_e,__,_t,_h,_e,__,_u,_l,_t,_i,_m,_a,_t,_e,__,_w,_e,_a,_p,_o,_n,_ddt,_RET
		.BYTE	_t,_h,_e,__,_F,_a,_t,_c,_a,_t,__,_R,_o,_b,_o,_t,_exc,_WAIT
		.BYTE	_STOP
_msg5E:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_D,_i,_d,__,_y,_o,_u,__,_h,_e,_a,_r,__,_s,_o,_m,_e,_t,_h,_i,_n,_g,_exc,_que,_WAIT
		.BYTE	_STOP
_msg5F:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_L,_o,_o,_k,__,_o,_u,_t,__,_e,_v,_e,_r,_y,_o,_n,_e,_exc,_WAIT
		.BYTE	_STOP
_msg60:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_T,_h,_e,__,_c,_e,_i,_l,_i,_n,_g,_exc,_RET
		.BYTE	_S,_h,_e,_apo,_s,__,_g,_i,_v,_i,_n,_g,__,_w,_a,_y,_exc,_WAIT
		.BYTE	_STOP
_msg61:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_G,_o,__,_f,_i,_n,_d,__,_c,_o,_v,_e,_r,_col,__,_e,_v,_e,_r,_y,_o,_n,_e,_exc,_WAIT
		.BYTE	_D,_a,_l,_e,__,_a,_n,_d,__,_I,__,_w,_i,_l,_l,__,_t,_r,_a,_c,_k,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,_exc,_WAIT
		.BYTE	_STOP
_msg62:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_T,_a,_k,_e,__,_c,_a,_r,_e,__,_o,_f,__,_y,_o,_u,_r,_s,_e,_l,_v,_e,_s,_exc,_WAIT
		.BYTE	_STOP
_msg63:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_C,_h,_i,_p,__,_a,_n,_d,__,_D,_a,_l,_e,__,_a,_r,_e,__,_t,_r,_a,_p,_p,_e,_d,_RET
		.BYTE	_i,_n,_s,_i,_d,_e,_exc,_WAIT
		.BYTE	_W,_e,_apo,_v,_e,__,_l,_o,_s,_t,__,_t,_h,_e,__,_l,_a,_d,_s,__,_f,_o,_r,_e,_v,_e,_r,_dot,_WAIT
		.BYTE	_STOP
_msg64:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_C,_h,_i,_p,_exc,__,__,_D,_a,_l,_e,_exc,_RET
		.BYTE	_T,_h,_a,_n,_k,__,_g,_o,_o,_d,_n,_e,_s,_s,__,_y,_o,_u,_apo,_r,_e,__,_s,_a,_f,_e,_exc,_WAIT
		.BYTE	_STOP
_msg65:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_W,_e,__,_a,_l,_m,_o,_s,_t,__,_d,_i,_d,_n,_apo,_t,__,_m,_a,_k,_e,__,_i,_t,_exc,_WAIT
		.BYTE	_STOP
_msg66:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_A,_n,_d,__,_w,_e,__,_n,_e,_v,_e,_r,__,_d,_i,_d,__,_c,_a,_p,_t,_u,_r,_e,_RET
		.BYTE	_F,_a,_t,_c,_a,_t,_dot,_WAIT
		.BYTE	_H,_e,__,_m,_u,_s,_t,__,_s,_t,_i,_l,_l,_RET
		.BYTE	_b,_e,__,_t,_r,_a,_p,_p,_e,_d,__,_i,_n,_s,_i,_d,_e,_dot,_WAIT
		.BYTE	_STOP
_msg67:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_B,_u,_t,__,_i,_f,__,_I,__,_k,_n,_o,_w,__,_F,_a,_t,_c,_a,_t,_col,__,_h,_e,__,_h,_a,_d,_RET
		.BYTE	_h,_i,_s,__,_e,_s,_c,_a,_p,_e,__,_w,_e,_l,_l,__,_p,_l,_a,_n,_n,_e,_d,_dot,_WAIT
		.BYTE	_STOP
_msg68:
		.BYTE	_M,_o,_n,_t,_e,_r,_e,_y,_ddt,_RET
		.BYTE	_W,_e,_l,_l,_col,__,_i,_f,__,_n,_o,_t,_h,_i,_n,_g,__,_e,_l,_s,_e,_col,_WAIT
		.BYTE	_w,_e,__,_m,_a,_d,_e,_RET
		.BYTE	_t,_h,_a,_t,__,_b,_l,_i,_g,_h,_t,_e,_r,_apo,_s,__,_l,_i,_f,_e,_RET
		.BYTE	_a,__,_l,_i,_t,_t,_l,_e,__,_l,_e,_s,_s,__,_c,_u,_s,_h,_y,_col,__,_e,_h,_que,_WAIT
		.BYTE	_STOP
_msg69:
		.BYTE	_D,_a,_l,_e,_ddt,_RET
		.BYTE	_Y,_o,_u,__,_s,_a,_i,_d,__,_i,_t,_exc,_WAIT
		.BYTE	_STOP
_msg6A:
		.BYTE	_G,_a,_d,_g,_e,_t,_ddt,_RET
		.BYTE	_A,_n,_d,__,_i,_f,_RET
		.BYTE	_h,_e,__,_e,_v,_e,_r,__,_s,_h,_o,_w,_s,__,_u,_p,__,_a,_g,_a,_i,_n,_dot,_dot,_dot,_WAIT
		.BYTE	_STOP
_msg6B:
		.BYTE	_C,_h,_i,_p,_ddt,_RET
		.BYTE	_T,_h,_e,_n,__,_I,__,_g,_u,_e,_s,_s,__,_w,_e,_apo,_l,_l,__,_j,_u,_s,_t,__,_h,_a,_v,_e,_RET
		.BYTE	_t,_o,__,_t,_e,_a,_c,_h,__,_h,_i,_m,__,_a,_n,_o,_t,_h,_e,_r,__,_l,_e,_s,_s,_o,_n,_exc,_WAIT
		.BYTE	_R,_i,_g,_h,_t,__,_R,_a,_n,_g,_e,_r,_s,_que,_exc,_WAIT
		.BYTE	_STOP
_msg6C:
		.BYTE	_RET
		.BYTE	_R,_i,_g,_h,_t,_exc,__,__,_W,_a,_t,_c,_h,__,_o,_u,_t,_col,__,_F,_a,_t,_c,_a,_t,_exc,_WAIT
		.BYTE	_RET
		.BYTE	_W,_e,_apo,_r,_e,__,_t,_h,_e,__,_R,_e,_s,_c,_u,_e,__,_R,_a,_n,_g,_e,_r,_s,_exc,_WAIT
		.BYTE	_STOP
